-- Script Name: UDA Validation Test Suite
-- Purpose: Validates User Defined Attributes (UDA) and their associations with item types
-- Author: [Francis]
-- Date: [26-11-2025]
-- Description: This script performs three validation tests: for DivisionId 20
--              1. Attribute name and description validation
--              2. Attribute-to-item-type association validation  
--              3. Extended rigid container attribute validation
-- =====================================================================================
USE speed_2max;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET NOCOUNT ON;
GO

BEGIN
BEGIN TRY
    -- =====================================================================================
    -- CLEANUP: Drop temporary tables if they exist from previous runs
    -- =====================================================================================
    DROP TABLE IF EXISTS #Updated;
    DROP TABLE IF EXISTS #Inserted;
    DROP TABLE IF EXISTS #Deleted;
     -- Create temporary table for Test 1
    CREATE TABLE #Updated (
        att_idn                 int,            -- Attribute ID from uda_definition
        item_typ_cde           VARCHAR(10),    -- Item type code
        expected_itm_class     VARCHAR(70),    -- Expected item class name
        itm_class              VARCHAR(70),    -- Actual item class name
        expected_att_nme       VARCHAR(70),    -- Expected attribute name
        att_nme                VARCHAR(70),    -- Actual attribute name
        expected_att_dsc       VARCHAR(70),    -- Expected attribute description
        att_dsc                VARCHAR(50),    -- Actual attribute description
        result                 VARCHAR(70),    -- Test result message
        assert                 CHAR(4) DEFAULT 'FAIL'  -- Test status (PASS/FAIL)
    );
        -- Create temporary table for Test 2
    CREATE TABLE #Inserted (
        att_idn                 int,            -- Attribute ID from uda_definition
        item_typ_cde           VARCHAR(10),    -- Item type code
        expected_itm_class     VARCHAR(70),    -- Expected item class name
        itm_class              VARCHAR(70),    -- Actual item class name
        expected_att_nme       VARCHAR(70),    -- Expected attribute name
        att_nme                VARCHAR(70),    -- Actual attribute name
        expected_att_dsc       VARCHAR(70),    -- Expected attribute description
        att_dsc                VARCHAR(50),    -- Actual attribute description
        result                 VARCHAR(70),    -- Test result message
        assert                 CHAR(4) DEFAULT 'FAIL'  -- Test status (PASS/FAIL)
    );
        -- Create temporary table for Test 3
    CREATE TABLE #Deleted (
        att_idn                 int,            -- Attribute ID from uda_definition
        item_typ_cde           VARCHAR(10),    -- Item type code
        expected_itm_class     VARCHAR(70),    -- Expected item class name
        itm_class              VARCHAR(70),    -- Actual item class name
        expected_att_nme       VARCHAR(70),    -- Expected attribute name
        att_nme                VARCHAR(70),    -- Actual attribute name
        expected_att_dsc       VARCHAR(70),    -- Expected attribute description
        att_dsc                VARCHAR(50),    -- Actual attribute description
        result                 VARCHAR(70),    -- Test result message
        assert                 CHAR(4) DEFAULT 'FAIL'  -- Test status (PASS/FAIL)
    );
    -- =====================================================================================
    -- TEST 1: ATTRIBUTE NAME AND DESCRIPTION VALIDATION
    -- Purpose: Validates that specific attributes exist with correct names and descriptions
    -- Focus: Packaging-related attributes for folding cartons and rigid containers
    -- =====================================================================================
    
   
    -- Insert test data: Expected attribute name and description pairs
    INSERT INTO #Updated (itm_class, expected_att_nme, att_nme,expected_att_dsc)
          SELECT 'BAGS_FI','BAG_ASSY_TYPE_FI','BAG_ASSY_TYPE_FI','BAG_ASSY_TYPE'
UNION SELECT 'BLANK_COUPON','BLANK_COUPON_NAME','BLANK_COUPON_NAME','BLANK_COUPON_NAME'
UNION SELECT 'BLANK_COUPON','COUPON_LENGTH_DIM','COUPON_LENGTH_DIM','COUPON_LENGTH_DIM'
UNION SELECT 'BLANK_COUPON','COUPON_WIDTH_DIM','COUPON_WIDTH_DIM','COUPON_WIDTH_DIM'
UNION SELECT 'BLANK_COUPON','COUPON_HEIGHT_DIM','COUPON_HEIGHT_DIM','COUPON_HEIGHT_DIM'
UNION SELECT 'BLANK_COUPON','COUPON_WEIGHT_QTY','COUPON_WEIGHT_QTY','COUPON_WEIGHT_QTY'
UNION SELECT 'BLANK_COUPON','COUPON_TYPE','COUPON_TYPE','COUPON_TYPE'
UNION SELECT 'CARRIER-TRAY','CT_TYPE','CT_TYPE','CT_TYPE'
UNION SELECT 'CARRIER-TRAY','CT_PKG_SIZE_LEADCOUNT','CT_PKG_SIZE_LEADCOUNT','CT_PKG_SIZE_LEADCOUNT'
UNION SELECT 'CARRIER-TRAY','CT_MATERIAL','CT_MATERIAL','CT_MATERIAL'
UNION SELECT 'CARRIER-TRAY','IHS_COMP_IND','IHS_COMP_IND','IHS_COMP_IND'
UNION SELECT 'CARRIER-TRAY','CT_THICKNESS','CT_THICKNESS','CT_THICKNESS'
UNION SELECT 'CARRIER-TRAY','CT_TEMP','CT_TEMP','CT_TEMP'
UNION SELECT 'CARRIER-TRAY','CT_COLOR','CT_COLOR','CT_COLOR'
UNION SELECT 'CARRIER-TRAY','CT_DECK_HEIGHT','CT_DECK_HEIGHT','CT_DECK_HEIGHT'
UNION SELECT 'CARRIER-TRAY','CT_PROCESS_SHIPPER','CT_PROCESS_SHIPPER','CT_PROCESS_SHIPPER'
UNION SELECT 'CARRIER-TRAY','CT_MANUF_PROCESS','CT_MANUF_PROCESS','CT_MANUF_PROCESS'
UNION SELECT 'CARRIER-TRAY','CT_MATRIX_LAYOUT','CT_MATRIX_LAYOUT','CT_MATRIX_LAYOUT'
UNION SELECT 'CARRIER-TRAY','RETAIL_PKG_INDICATOR','RETAIL_PKG_INDICATOR','RETAIL_PKG_INDICATOR'
UNION SELECT 'CARRIER-TRAY','CLS_TYPE','CLS_TYPE','CLS_TYPE'
UNION SELECT 'CARRIER_FOUP','FOUP_SLOT_QTY','FOUP_SLOT_QTY','FOUP_SLOT_QTY'
UNION SELECT 'CARRIER_FOUP','FOUP_SHELL_MATERIAL','FOUP_SHELL_MATERIAL','FOUP_SHELL_MATERIAL'
UNION SELECT 'CARRIER_FOUP','FOUP_SIDE_COLUMN_MTL','FOUP_SIDE_COLUMN_MTL','FOUP_SIDE_COLUMN_MTL'
UNION SELECT 'CARRIER_FOUP','FOUP_TYPE','FOUP_TYPE','FOUP_TYPE'
UNION SELECT 'CFB_CNTR_FI','REPLACEMENT_SPN','REPLACEMENT_SPN','REPLACEMENT_SPN'
UNION SELECT 'CMP','REPAIRABLE','REPAIRABLE','REPAIRABLE'
UNION SELECT 'CMP','CONSUMABLE','CONSUMABLE','CONSUMABLE'
UNION SELECT 'CMP','FTSZ','FTSZ','FTSZ'
UNION SELECT 'CMP','NET_CONTENT_UOM','NET_CONTENT_UOM','NET_CONTENT_UOM'
UNION SELECT 'CMP','CMP_TYPE','CMP_TYPE','CMP_TYPE'
UNION SELECT 'CMP','CHEMICAL_NAME','CHEMICAL_NAME','CHEMICAL_NAME'
UNION SELECT 'CMP','SHIPPING_METHOD_TYPE','SHIPPING_METHOD_TYPE','SHIPPING_METHOD_TYPE'
UNION SELECT 'CMP','SHPNG_SHOCK_TILT_RECORDER_IND','SHPNG_SHOCK_TILT_RECORDER_IND','SHPNG_SHOCK_TILT_RECORDER_IND'
UNION SELECT 'CMP','SHPNG_SECURITY_INDICATOR','SHPNG_SECURITY_INDICATOR','SHPNG_SECURITY_INDICATOR'
UNION SELECT 'CMP','SHIPMENT_RESPONSIBILITY_TYPE','SHIPMENT_RESPONSIBILITY_TYPE','SHIPMENT_RESPONSIBILITY_TYPE'
UNION SELECT 'CMP','RETURNABLE_CONTAINER_IND','RETURNABLE_CONTAINER_IND','RETURNABLE_CONTAINER_IND'
UNION SELECT 'CMP','SHPNG_TEMPERATURE_RECORDER_IND','SHPNG_TEMPERATURE_RECORDER_IND','SHPNG_TEMPERATURE_RECORDER_IND'
UNION SELECT 'CMP','CONFLICT_MINERAL_NAME','CONFLICT_MINERAL_NAME','CONFLICT_MINERAL_NAME'
UNION SELECT 'CONTAINERS_FI','REPLACEMENT_SPN','REPLACEMENT_SPN','REPLACEMENT_SPN'
UNION SELECT 'DIE_BACKSIDE_FILM','WAFER_SIZE','WAFER_SIZE','WAFER_SIZE'
UNION SELECT 'DIE_BACKSIDE_FILM','UV_CURE_IND','UV_CURE_IND','UV_CURE_IND'
UNION SELECT 'DIE_BACKSIDE_FILM','FILM_ADHESIVE_LAYER_THICKNESS','FILM_ADHESIVE_LAYER_THICKNESS','FILM_ADHESIVE_LAYER_THICKNESS'
UNION SELECT 'DIE_BACKSIDE_FILM','LASER_MARKABILITY_IND','LASER_MARKABILITY_IND','LASER_MARKABILITY_IND'
UNION SELECT 'DIE_EJECTOR','MESA_STANDOFF_X_DIMENSION','MESA_STANDOFF_X_DIMENSION','MESA_STANDOFF_X_DIMENSION'
UNION SELECT 'DIE_EJECTOR','MESA_STANDOFF_Y_DIMENSION','MESA_STANDOFF_Y_DIMENSION','MESA_STANDOFF_Y_DIMENSION'
UNION SELECT 'DIE_EJECTOR','DIE_EJECTOR_PART_TYPE','DIE_EJECTOR_PART_TYPE','ANVIL'
UNION SELECT 'DIE_PREP_BLADES','BLADE_KERF_WIDTH_DIM','BLADE_KERF_WIDTH_DIM','BLADE_KERF_WIDTH_DIM'
UNION SELECT 'DIE_PREP_BLADES','DP_BLADE_AXIS_CODE','DP_BLADE_AXIS_CODE','DP_BLADE_AXIS_CODE'
UNION SELECT 'DIE_PREP_BLADES','DP_TOOL_GRIT_NUMBER','DP_TOOL_GRIT_NUMBER','DP_TOOL_GRIT_NUMBER'
UNION SELECT 'DIE_PREP_CHEM','CHEMICAL_TYPE_NM','CHEMICAL_TYPE_NM','ADHESIVE'
UNION SELECT 'DIE_PREP_CHEM','MATERIAL_CATEGORY_NM','MATERIAL_CATEGORY_NM','DIRECT MATERIAL'
UNION SELECT 'DIE_PREP_CHEM','MATERIAL_FORM_FACTOR_NM','MATERIAL_FORM_FACTOR_NM','FILM'
UNION SELECT 'DIE_PREP_CHEM','CONSUMABLE_IND','CONSUMABLE_IND','NO'
UNION SELECT 'DIE_PREP_TAPE','MAX_WFR_SZ','MAX_WFR_SZ','MAX_WFR_SZ'
UNION SELECT 'DIE_PREP_TAPE','DP_TAPE_TYPE','DP_TAPE_TYPE','DP_TAPE_TYPE'
UNION SELECT 'DIE_PREP_TAPE','UV_CURE_IND','UV_CURE_IND','UV_CURE_IND'
UNION SELECT 'DP_RCTNGL_COLLET','DP_COLLET_TOOL_CODE','DP_COLLET_TOOL_CODE','DP_COLLET_TOOL_CODE'
UNION SELECT 'DP_RCTNGL_COLLET','DP_COLLET_TOOL_OPERATION_CODE','DP_COLLET_TOOL_OPERATION_CODE','DP_COLLET_TOOL_OPERATION_CODE'
UNION SELECT 'DP_RCTNGL_COLLET','DP_COLLET_MATRL_DENSITY_NAME','DP_COLLET_MATRL_DENSITY_NAME','DP_COLLET_MATRL_DENSITY_NAME'
UNION SELECT 'DP_RCTNGL_COLLET','DP_COLLET_X_AXIS_DIM','DP_COLLET_X_AXIS_DIM','DP_COLLET_X_AXIS_DIM'
UNION SELECT 'DP_RCTNGL_COLLET','DP_COLLET_Y_AXIS_DIM','DP_COLLET_Y_AXIS_DIM','DP_COLLET_Y_AXIS_DIM'
UNION SELECT 'DP_ROUND_COLLET','DP_COLLET_TOOL_CODE','DP_COLLET_TOOL_CODE','DP_COLLET_TOOL_CODE'
UNION SELECT 'DP_ROUND_COLLET','DP_COLLET_TOOL_OPERATION_CODE','DP_COLLET_TOOL_OPERATION_CODE','DP_COLLET_TOOL_OPERATION_CODE'
UNION SELECT 'DP_ROUND_COLLET','DP_COLLET_DIAMETER_DIM','DP_COLLET_DIAMETER_DIM','DP_COLLET_DIAMETER_DIM'
UNION SELECT 'DP_THINNING_WHEELS','DP_TOOL_GRIT_NUMBER','DP_TOOL_GRIT_NUMBER','DP_TOOL_GRIT_NUMBER'
UNION SELECT 'DP_THINNING_WHEELS','DP_THIN_WHEEL_TOOTH_LENGTH_DIM','DP_THIN_WHEEL_TOOTH_LENGTH_DIM','DP_THIN_WHEEL_TOOTH_LENGTH_DIM'
UNION SELECT 'DP_THINNING_WHEELS','DP_THIN_WHEEL_TYPE_NAME','DP_THIN_WHEEL_TYPE_NAME','DP_THIN_WHEEL_TYPE_NAME'
UNION SELECT 'DP_THINNING_WHEELS','DP_THIN_WHL_POSITION_CODE','DP_THIN_WHL_POSITION_CODE','DP_THIN_WHL_POSITION_CODE'
UNION SELECT 'EDGE_TRIM_BLADE','DP_BLADE_GRIT_DIM','DP_BLADE_GRIT_DIM','DP_BLADE_GRIT_DIM'
UNION SELECT 'EDGE_TRIM_DRSSR_BD','DP_BLADE_GRIT_DIM','DP_BLADE_GRIT_DIM','DP_BLADE_GRIT_DIM'
UNION SELECT 'EMBSD_CARRIER_TAPE','TAPE-PITCH','TAPE-PITCH','TAPE-PITCH'
UNION SELECT 'EMBSD_CARRIER_TAPE','TAPE-WIDTH','TAPE-WIDTH','TAPE-WIDTH'
UNION SELECT 'EMBSD_CARRIER_TAPE','TAPE-THICKNESS','TAPE-THICKNESS','TAPE-THICKNESS'
UNION SELECT 'EMBSD_CARRIER_TAPE','REEL_WNDNG_STYL','REEL_WNDNG_STYL','REEL_WNDNG_STYL'
UNION SELECT 'EMBSD_CARRIER_TAPE','TP_PCKT_LGTH_A0','TP_PCKT_LGTH_A0','TP_PCKT_LGTH_A0'
UNION SELECT 'EMBSD_CARRIER_TAPE','PCKT_TAPE_CAT','PCKT_TAPE_CAT','PCKT_TAPE_CAT'
UNION SELECT 'EMBSD_CARRIER_TAPE','TP_PCKT_WDTH_B0','TP_PCKT_WDTH_B0','TP_PCKT_WDTH_B0'
UNION SELECT 'EMBSD_CARRIER_TAPE','TP_PCKT_DPTH_K0','TP_PCKT_DPTH_K0','TP_PCKT_DPTH_K0'
UNION SELECT 'EMBSD_CARRIER_TAPE','UNQ_PCKT_ID','UNQ_PCKT_ID','UNQ_PCKT_ID'
UNION SELECT 'EMBSD_CARRIER_TAPE','REEL_DIAMETER_DIMENSION','REEL_DIAMETER_DIMENSION','REEL_DIAMETER_DIMENSION'
UNION SELECT 'EMBSD_CARRIER_TAPE','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME'
UNION SELECT 'EMBSD_CARRIER_TAPE','EMBOSSED_CARRIER_TAPE_MATL_NM','EMBOSSED_CARRIER_TAPE_MATL_NM','EMBOSSED_CARRIER_TAPE_MATL_NM'
UNION SELECT 'EMBSD_CARRIER_TAPE','CARRIER_TAPE_PCKT_FEATR_NM','CARRIER_TAPE_PCKT_FEATR_NM','CARRIER_TAPE_PCKT_FEATR_NM'
UNION SELECT 'EMBSD_CARRIER_TAPE','CORNER_RELIEF_CONFIGURATION_NM','CORNER_RELIEF_CONFIGURATION_NM','CORNER_RELIEF_CONFIGURATION_NM'
UNION SELECT 'EMBSD_CARRIER_TAPE','TAPE_LENGTH_QUANTITY','TAPE_LENGTH_QUANTITY','TAPE_LENGTH_QUANTITY'
UNION SELECT 'EMBSD_CARRIER_TAPE','POCKET_REEL_COUNT','POCKET_REEL_COUNT','POCKET_REEL_COUNT'
UNION SELECT 'FILTRATION','MAT_CATEGORY','MAT_CATEGORY','MAT_CATEGORY'
UNION SELECT 'FILTRATION','PACKAGING_SIZE','PACKAGING_SIZE','PACKAGING_SIZE'
UNION SELECT 'FILTRATION','PORESIZE_UOM','PORESIZE_UOM','PORESIZE_UOM'
UNION SELECT 'FILTRATION','PACKAGING_UOM','PACKAGING_UOM','PACKAGING_UOM'
UNION SELECT 'FILTRATION','FILT_CONFIGURATION','FILT_CONFIGURATION','FILT_CONFIGURATION'
UNION SELECT 'FOUNDRY_SERVICES','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'HBI_COLLATERAL','CONFIGURATION','CONFIGURATION','CONFIGURATION'
UNION SELECT 'HBI_COLLATERAL','COLLATERAL_TYPE','COLLATERAL_TYPE','COLLATERAL TYPE'
UNION SELECT 'HBI_COLLATERAL','COLLATERAL_TYPE','COLLATERAL_TYPE','COLLATERAL TYPE'
UNION SELECT 'LABEL_BLANK_FI','BLNK-PRINTER-USAGE','BLNK-PRINTER-USAGE','BLNK-PRINTER-USAGE'
UNION SELECT 'LITHO','NET_CONTENT_UOM','NET_CONTENT_UOM','NET_CONTENT_UOM'
UNION SELECT 'LITHO','CHEMICAL_NAME','CHEMICAL_NAME','CHEMICAL_NAME'
UNION SELECT 'LITHO','SHIPPING_METHOD_TYPE','SHIPPING_METHOD_TYPE','SHIPPING_METHOD_TYPE'
UNION SELECT 'LITHO','RETURNABLE_CONTAINER_IND','RETURNABLE_CONTAINER_IND','RETURNABLE_CONTAINER_IND'
UNION SELECT 'LITHO','SHPNG_TEMPERATURE_RECORDER_IND','SHPNG_TEMPERATURE_RECORDER_IND','SHPNG_TEMPERATURE_RECORDER_IND'
UNION SELECT 'MRF','MRF_FILM_WIDTH','MRF_FILM_WIDTH','MRF_FILM_WIDTH'
UNION SELECT 'MRF','MRF_FILM_LENGTH','MRF_FILM_LENGTH','MRF_FILM_LENGTH'
UNION SELECT 'MRF','MRF_ESD_LAYER','MRF_ESD_LAYER','MRF_ESD_LAYER'
UNION SELECT 'MRF','MRF_NOMINAL_FILM_THICKNESS','MRF_NOMINAL_FILM_THICKNESS','MRF_NOMINAL_FILM_THICKNESS'
UNION SELECT 'MRF','MRF_SUPPLIER_NAME','MRF_SUPPLIER_NAME','MRF_SUPPLIER_NAME'
UNION SELECT 'MRF','MRF_SUPPLIER_MATERIAL_NAME','MRF_SUPPLIER_MATERIAL_NAME','MRF_SUPPLIER_MATERIAL_NAME'
UNION SELECT 'PLASTIC_TAPE_REEL','REEL_WNDNG_STYL','REEL_WNDNG_STYL','REEL_WNDNG_STYL'
UNION SELECT 'PLASTIC_TAPE_REEL','PCKT_TAPE_CAT','PCKT_TAPE_CAT','PCKT_TAPE_CAT'
UNION SELECT 'PLASTIC_TAPE_REEL','REEL_DIAMETER_DIMENSION','REEL_DIAMETER_DIMENSION','REEL_DIAMETER_DIMENSION'
UNION SELECT 'PLASTIC_TAPE_REEL','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME'
UNION SELECT 'PLASTIC_TAPE_REEL','TAPE_REEL_WIDTH_DIM','TAPE_REEL_WIDTH_DIM','TAPE_REEL_WIDTH_DIM'
UNION SELECT 'PLASTIC_TAPE_REEL','TAPE_REEL_MATERIAL_NAME','TAPE_REEL_MATERIAL_NAME','TAPE_REEL_MATERIAL_NAME'
UNION SELECT 'PLASTIC_TAPE_REEL','TP_REEL_HUB_DIAMETER_DIM','TP_REEL_HUB_DIAMETER_DIM','TP_REEL_HUB_DIAMETER_DIM'
UNION SELECT 'PLASTIC_TAPE_REEL','TAPE_REEL_CONFIGURATION_NAME','TAPE_REEL_CONFIGURATION_NAME','TAPE_REEL_CONFIGURATION_NAME'
UNION SELECT 'POCKET_CVR_TAPE','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME'
UNION SELECT 'POCKET_CVR_TAPE','POCKET_COVER_TAPE_SEAL_NAME','POCKET_COVER_TAPE_SEAL_NAME','POCKET_COVER_TAPE_SEAL_NAME'
UNION SELECT 'POCKET_CVR_TAPE','POCKET_COVER_TAPE_WIDTH_DIM','POCKET_COVER_TAPE_WIDTH_DIM','POCKET_COVER_TAPE_WIDTH_DIM'
UNION SELECT 'POCKET_CVR_TAPE','POCKET_COVER_TAPE_LENGTH_DIM','POCKET_COVER_TAPE_LENGTH_DIM','POCKET_COVER_TAPE_LENGTH_DIM'
UNION SELECT 'PRCSS_METAL_CARR','IHS_COMP_IND','IHS_COMP_IND','IHS_COMP_IND'
UNION SELECT 'PRCSS_METAL_CARR','X_SUB_DIM','X_SUB_DIM','X_SUB_DIM'
UNION SELECT 'PRCSS_METAL_CARR','Y_SUB_DIM','Y_SUB_DIM','Y_SUB_DIM'
UNION SELECT 'PRCSS_METAL_CARR','CARRIER_ASSEMBLY_TYPE_NM','CARRIER_ASSEMBLY_TYPE_NM','CARRIER_ASSEMBLY_TYPE_NM'
UNION SELECT 'PRCSS_METAL_CARR','CARRIER_COLUMN_COUNT','CARRIER_COLUMN_COUNT','CARRIER_COLUMN_COUNT'
UNION SELECT 'PRCSS_METAL_CARR','CARRIER_ROW_COUNT','CARRIER_ROW_COUNT','CARRIER_ROW_COUNT'
UNION SELECT 'PRCSS_METAL_CARR','SUBSTRATE_CLAMP_TYPE_NM','SUBSTRATE_CLAMP_TYPE_NM','SUBSTRATE_CLAMP_TYPE_NM'
UNION SELECT 'PRCSS_METAL_CARR','CARRIER_SBSTRT_QTY','CARRIER_SBSTRT_QTY','CARRIER_SBSTRT_QTY'
UNION SELECT 'PRCSS_METAL_CARR','POCKET_COUNT','POCKET_COUNT','POCKET_COUNT'
UNION SELECT 'PRCSS_METAL_CARR','CARRIER_CATEGORY_NAME','CARRIER_CATEGORY_NAME','CARRIER_CATEGORY_NAME'
UNION SELECT 'QUARTZWARE','MATERIAL','MATERIAL','MATERIAL'
UNION SELECT 'QUARTZWARE','CONSUMABLE','CONSUMABLE','CONSUMABLE'
UNION SELECT 'QUARTZWARE','FTSZ','FTSZ','FTSZ'
UNION SELECT 'QUARTZWARE','NET_CONTENT_UOM','NET_CONTENT_UOM','NET_CONTENT_UOM'
UNION SELECT 'QUARTZWARE','WAFER_SIZE','WAFER_SIZE','WAFER_SIZE'
UNION SELECT 'QUARTZWARE','TEMP','TEMP','TEMP'
UNION SELECT 'QUARTZWARE','SUB_TYP','SUB_TYP','SUB_TYP'
UNION SELECT 'QUARTZWARE','PROCESS_TYPE','PROCESS_TYPE','PROCESS_TYPE'
UNION SELECT 'QUARTZWARE','LAYER','LAYER','LAYER'
UNION SELECT 'QUARTZWARE','SURFACE_FINISH','SURFACE_FINISH','SURFACE_FINISH'
UNION SELECT 'REEL','PKG-COMP-MATERIAL','PKG-COMP-MATERIAL','PKG-COMP-MATERIAL'
UNION SELECT 'REEL','TAPE-WIDTH','TAPE-WIDTH','TAPE-WIDTH'
UNION SELECT 'REEL','PCKT_TAPE_CAT','PCKT_TAPE_CAT','PCKT_TAPE_CAT'
UNION SELECT 'REEL','REEL_DIAMETER_DIMENSION','REEL_DIAMETER_DIMENSION','REEL_DIAMETER_DIMENSION'
UNION SELECT 'REEL','REEL_HUB_DIAMETER_DIMENSION','REEL_HUB_DIAMETER_DIMENSION','REEL_HUB_DIAMETER_DIMENSION'
UNION SELECT 'SBSTRT_PANEL_TRAY','TRAY_MATERIAL_NAME','TRAY_MATERIAL_NAME','TRAY_MATERIAL_NAME'
UNION SELECT 'SBSTRT_PANEL_TRAY','Z_TRAY_DIM','Z_TRAY_DIM','Z_TRAY_DIM'
UNION SELECT 'SBSTRT_PANEL_TRAY','TRAY_STACK_TYPE','TRAY_STACK_TYPE','TRAY_STACK_TYPE'
UNION SELECT 'SBSTRT_PANEL_TRAY','SBSTRT_PANEL_TRAY_MAX_TEMP','SBSTRT_PANEL_TRAY_MAX_TEMP','SBSTRT_PANEL_TRAY_MAX_TEMP'
UNION SELECT 'SBSTRT_PANEL_TRAY','X_SBSTRT_PANEL_TRAY_DIM','X_SBSTRT_PANEL_TRAY_DIM','X_SBSTRT_PANEL_TRAY_DIM'
UNION SELECT 'SBSTRT_PANEL_TRAY','Y_SBSTRT_PANEL_TRAY_DIM','Y_SBSTRT_PANEL_TRAY_DIM','Y_SBSTRT_PANEL_TRAY_DIM'
UNION SELECT 'SBSTRT_PANEL_TRAY','X_SBSTRT_PANEL_UNIT_DIM','X_SBSTRT_PANEL_UNIT_DIM','X_SBSTRT_PANEL_UNIT_DIM'
UNION SELECT 'SBSTRT_PANEL_TRAY','Y_SBSTRT_PANEL_UNIT_DIM','Y_SBSTRT_PANEL_UNIT_DIM','Y_SBSTRT_PANEL_UNIT_DIM'
UNION SELECT 'SBSTRT_PKG_TRAY','X_SUB_DIM','X_SUB_DIM','X_SUB_DIM'
UNION SELECT 'SBSTRT_PKG_TRAY','Y_SUB_DIM','Y_SUB_DIM','Y_SUB_DIM'
UNION SELECT 'SBSTRT_PKG_TRAY','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME'
UNION SELECT 'SBSTRT_PKG_TRAY','TRAY_MATERIAL_NAME','TRAY_MATERIAL_NAME','TRAY_MATERIAL_NAME'
UNION SELECT 'SBSTRT_PKG_TRAY','JEDEC_TRAY_STNDRD_DIM_IND','JEDEC_TRAY_STNDRD_DIM_IND','JEDEC_TRAY_STNDRD_DIM_IND'
UNION SELECT 'SBSTRT_PKG_TRAY','SBSTRT_PKG_TRAY_MAX_TEMP_AMT','SBSTRT_PKG_TRAY_MAX_TEMP_AMT','SBSTRT_PKG_TRAY_MAX_TEMP_AMT'
UNION SELECT 'SBSTRT_PKG_TRAY','Z_TRAY_DIM','Z_TRAY_DIM','Z_TRAY_DIM'
UNION SELECT 'SBSTRT_PKG_TRAY','TRAY_PCKT_COLUMN_COUNT','TRAY_PCKT_COLUMN_COUNT','TRAY_PCKT_COLUMN_COUNT'
UNION SELECT 'SBSTRT_PKG_TRAY','TRAY_PCKT_ROW_COUNT','TRAY_PCKT_ROW_COUNT','TRAY_PCKT_ROW_COUNT'
UNION SELECT 'SBSTRT_PKG_TRAY','TRAY_POCKET_COUNT','TRAY_POCKET_COUNT','TRAY_POCKET_COUNT'
UNION SELECT 'SBSTRT_PKG_TRAY','TRAY_CATEGORY_NAME','TRAY_CATEGORY_NAME','TRAY_CATEGORY_NAME'
UNION SELECT 'SBSTRT_PKG_TRAY','SBSTR_PKG_TRAY_PCKT_FEATR_NM','SBSTR_PKG_TRAY_PCKT_FEATR_NM','SBSTR_PKG_TRAY_PCKT_FEATR_NM'
UNION SELECT 'SBSTRT_PKG_TRAY','TRAY_STACK_TYPE','TRAY_STACK_TYPE','TRAY_STACK_TYPE'
UNION SELECT 'SMP','NET_CONTENT_QTY','NET_CONTENT_QTY','NET_CONTENT_QTY'
UNION SELECT 'SMP','NET_CONTENT_UOM','NET_CONTENT_UOM','NET_CONTENT_UOM'
UNION SELECT 'SMP','SMP_CHEMICAL','SMP_CHEMICAL','SMP_CHEMICAL'
UNION SELECT 'SMP','CHEMICAL_NAME','CHEMICAL_NAME','CHEMICAL_NAME'
UNION SELECT 'SMP','SHIPPING_METHOD_TYPE','SHIPPING_METHOD_TYPE','SHIPPING_METHOD_TYPE'
UNION SELECT 'SMP','SHIPMENT_RESPONSIBILITY_TYPE','SHIPMENT_RESPONSIBILITY_TYPE','SHIPMENT_RESPONSIBILITY_TYPE'
UNION SELECT 'SMP','RETURNABLE_CONTAINER_IND','RETURNABLE_CONTAINER_IND','RETURNABLE_CONTAINER_IND'
UNION SELECT 'TARGET_ANODE','MATERIAL','MATERIAL','MATERIAL'
UNION SELECT 'TARGET_ANODE','REPAIRABLE','REPAIRABLE','REPAIRABLE'
UNION SELECT 'TARGET_ANODE','CONSUMABLE','CONSUMABLE','CONSUMABLE'
UNION SELECT 'TARGET_ANODE','FTSZ','FTSZ','FTSZ'
UNION SELECT 'TARGET_ANODE','NET_CONTENT_UOM','NET_CONTENT_UOM','NET_CONTENT_UOM'
UNION SELECT 'TARGET_ANODE','METAL_SHAPE','METAL_SHAPE','METAL_SHAPE'
UNION SELECT 'TC_NOZZLE','MESA_STANDOFF_X_DIMENSION','MESA_STANDOFF_X_DIMENSION','MESA_STANDOFF_X_DIMENSION'
UNION SELECT 'TC_NOZZLE','MESA_STANDOFF_Y_DIMENSION','MESA_STANDOFF_Y_DIMENSION','MESA_STANDOFF_Y_DIMENSION'
UNION SELECT 'TEST_TIM','CLAD_MATL_BARRIER_IND','CLAD_MATL_BARRIER_IND','CLAD_MATL_BARRIER_IND'
UNION SELECT 'TEST_TIM','ALLOY_CODE','ALLOY_CODE','ALLOY_CODE'
UNION SELECT 'TEST_TIM','MATERIAL_HARDNESS_CODE','MATERIAL_HARDNESS_CODE','MATERIAL_HARDNESS_CODE'
UNION SELECT 'TEST_TIM','TEST_TIM_BARRIER_MATL_CODE','TEST_TIM_BARRIER_MATL_CODE','TEST_TIM_BARRIER_MATL_CODE'
UNION SELECT 'TEST_TIM','TEST_TIM_PAD_TYPE','TEST_TIM_PAD_TYPE','TEST_TIM_PAD_TYPE'
UNION SELECT 'TEST_TIM','TEST_TIM_PAD_X_DIM','TEST_TIM_PAD_X_DIM','TEST_TIM_PAD_X_DIM'
UNION SELECT 'TEST_TIM','TEST_TIM_PAD_Y_DIM','TEST_TIM_PAD_Y_DIM','TEST_TIM_PAD_Y_DIM'
UNION SELECT 'TEST_TIM','TEST_TIM_PAD_Z_DIM','TEST_TIM_PAD_Z_DIM','TEST_TIM_PAD_Z_DIM'
UNION SELECT 'TEST_TIM','TEST_TIM_BARRIER_X_DIM','TEST_TIM_BARRIER_X_DIM','TEST_TIM_BARRIER_X_DIM'
UNION SELECT 'TEST_TIM','TEST_TIM_BARRIER_Y_DIM','TEST_TIM_BARRIER_Y_DIM','TEST_TIM_BARRIER_Y_DIM'
UNION SELECT 'TEST_TIM','TEST_TIM_BARRIER_Z_DIM','TEST_TIM_BARRIER_Z_DIM','TEST_TIM_BARRIER_Z_DIM'
UNION SELECT 'TEST_TIM','KIT_INDICATOR','KIT_INDICATOR','KIT_INDICATOR'
UNION SELECT 'TP_REEL_PRTCTV_BND','PCKT_TAPE_CAT','PCKT_TAPE_CAT','PCKT_TAPE_CAT'
UNION SELECT 'TP_REEL_PRTCTV_BND','PRTCTV_BAND_LENGH_DIM','PRTCTV_BAND_LENGH_DIM','PRTCTV_BAND_LENGH_DIM'
UNION SELECT 'TP_REEL_PRTCTV_BND','PRTCTV_BAND_WIDTH_DIM','PRTCTV_BAND_WIDTH_DIM','PRTCTV_BAND_WIDTH_DIM'
UNION SELECT 'TP_REEL_PRTCTV_BND','PRTCTV_BAND_THICKNESS_DIM','PRTCTV_BAND_THICKNESS_DIM','PRTCTV_BAND_THICKNESS_DIM'
UNION SELECT 'TP_REEL_PRTCTV_BND','PRTCTV_BAND_SURFACE_TEXTURE_NM','PRTCTV_BAND_SURFACE_TEXTURE_NM','PRTCTV_BAND_SURFACE_TEXTURE_NM'
UNION SELECT 'TP_REEL_PRTCTV_BND','PRTCTV_BAND_CLIP_INDICATOR','PRTCTV_BAND_CLIP_INDICATOR','PRTCTV_BAND_CLIP_INDICATOR'
UNION SELECT 'TP_REEL_PRTCTV_BND','PRTCTV_BAND_MATERIALS_NM','PRTCTV_BAND_MATERIALS_NM','PRTCTV_BAND_MATERIALS_NM'
UNION SELECT 'TP_REEL_PRTCTV_BND','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME','ESD_APPLICATION_METHOD_NAME'
UNION SELECT 'TRAY_AUTO_FOSB','TRAY_AUTO_FOSB_COLOR_NAME','TRAY_AUTO_FOSB_COLOR_NAME','CLR'
UNION SELECT 'UPI_ASSEMBLY','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_ASSEMBLY','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_ASSEMBLY','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'UPI_ASSEMBLY','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_ASSEMBLY','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_ASSEMBLY','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'UPI_ASSEMBLY','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'UPI_ASSEMBLY','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'UPI_ASSEMBLY','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'UPI_ASSEMBLY','MFG_PKG_CODE','MFG_PKG_CODE','Manufacturing Package Code'
UNION SELECT 'UPI_ASSEMBLY','TOTAL_FUNCTIONAL_CORE_COUNT','TOTAL_FUNCTIONAL_CORE_COUNT','Total Functional Core Count'
UNION SELECT 'UPI_ASSEMBLY','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'UPI_ASSEMBLY','SUPPORTED_WRLS_PROTOCOL_CODE','SUPPORTED_WRLS_PROTOCOL_CODE','Supported Wireless Protocol Code'
UNION SELECT 'UPI_ASSEMBLY','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'UPI_ASSEMBLY','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_ASSEMBLY','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'UPI_ASSEMBLY','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_ASSEMBLY','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'UPI_ASSEMBLY','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'UPI_ASSEMBLY','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'UPI_ASSEMBLY','MEMORY1_CAPACITY_UOM','MEMORY1_CAPACITY_UOM','Memory  1 Capacity Uom'
UNION SELECT 'UPI_ASSEMBLY','INDIVIDUAL_MEMORY_CAPACITY','INDIVIDUAL_MEMORY_CAPACITY','Individual Memory Capacity'
UNION SELECT 'UPI_BUMP','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_BUMP','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_BUMP','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'UPI_BUMP','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_BUMP','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_BUMP','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'UPI_BUMP','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'UPI_BUMP','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_BUMP','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'UPI_BUMP','DIE_SINGULATION_INDICATOR','DIE_SINGULATION_INDICATOR','Die Singulation Indicator'
UNION SELECT 'UPI_BUMP','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_BUMP','DUAL_SALES_INDICATOR','DUAL_SALES_INDICATOR','Dual Sales Indicator'
UNION SELECT 'UPI_BUMP','FRONTSIDE_WAFER_FLAG_INDICATOR','FRONTSIDE_WAFER_FLAG_INDICATOR','Frontside Wafer Flag Indicator'
UNION SELECT 'UPI_BUMP','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'UPI_BUMP','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_BUMP','EXTERNAL_TO_DIEPREP_INDICATOR','EXTERNAL_TO_DIEPREP_INDICATOR','External to DiePrep Indicator'
UNION SELECT 'UPI_BUMP','UNSORTED_EXTERNAL_SILICON_IND','UNSORTED_EXTERNAL_SILICON_IND','Unsorted External Silicon Ind'
UNION SELECT 'UPI_DIE_PREP','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_DIE_PREP','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_DIE_PREP','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'UPI_DIE_PREP','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_DIE_PREP','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_DIE_PREP','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'UPI_DIE_PREP','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_DIE_PREP','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'UPI_DIE_PREP','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'UPI_DIE_PREP','DIE_SINGULATION_INDICATOR','DIE_SINGULATION_INDICATOR','Die Singulation Indicator'
UNION SELECT 'UPI_DIE_PREP','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_DIE_PREP','DUAL_SALES_INDICATOR','DUAL_SALES_INDICATOR','Dual Sales Indicator'
UNION SELECT 'UPI_DIE_PREP','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_FAB','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_FAB','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_FAB','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'UPI_FAB','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_FAB','DISCREET_MEMORY_QTY','DISCREET_MEMORY_QTY','Discreet Memory Qty'
UNION SELECT 'UPI_FAB','DISCREET_MEMORY_UOM','DISCREET_MEMORY_UOM','Discreet Memory UOM'
UNION SELECT 'UPI_FAB','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_FAB','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_FAB','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'UPI_FAB','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP Estimate Physical Core Qty'
UNION SELECT 'UPI_FAB','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP Est Phys Graphics Core Qty'
UNION SELECT 'UPI_FAB','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'UPI_FAB','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_FAB','DUAL_SALES_INDICATOR','DUAL_SALES_INDICATOR','Dual Sales Indicator'
UNION SELECT 'UPI_FAB','FRONTSIDE_WAFER_FLAG_INDICATOR','FRONTSIDE_WAFER_FLAG_INDICATOR','Frontside Wafer Flag Indicator'
UNION SELECT 'UPI_FAB','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'UPI_FAB','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_FAB','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'UPI_FAB','EXTERNAL_TO_DIEPREP_INDICATOR','EXTERNAL_TO_DIEPREP_INDICATOR','External to DiePrep Indicator'
UNION SELECT 'UPI_FAB','UNSORTED_EXTERNAL_SILICON_IND','UNSORTED_EXTERNAL_SILICON_IND','Unsorted External Silicon Ind'
UNION SELECT 'UPI_FAB','MULTI_PRODUCT_WAFER_INDICATOR','MULTI_PRODUCT_WAFER_INDICATOR','Multiple Product Wfr Ind'
UNION SELECT 'UPI_FINISH','MARKETING_PACKAGE_DESIGNATOR','MARKETING_PACKAGE_DESIGNATOR','Marketing Package Designator'
UNION SELECT 'UPI_FINISH','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_FINISH','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'UPI_FINISH','EXTERNAL_STEPPING','EXTERNAL_STEPPING','External Stepping'
UNION SELECT 'UPI_FINISH','TOTAL_FUNCTIONAL_CORE_COUNT','TOTAL_FUNCTIONAL_CORE_COUNT','Total Functional Core Count'
UNION SELECT 'UPI_FINISH','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'UPI_FINISH','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'UPI_FINISH','MULTIPLE_MARK_NAME','MULTIPLE_MARK_NAME','Multiple Mark Name'
UNION SELECT 'UPI_SORT','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_SORT','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_SORT','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'UPI_SORT','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_SORT','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_SORT','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_SORT','DIE_SIZE_LENGTH_Y','DIE_SIZE_LENGTH_Y','Die Size Length Y'
UNION SELECT 'UPI_SORT','DIE_SIZE_LENGTH_UOM','DIE_SIZE_LENGTH_UOM','Die Size Length UOM'
UNION SELECT 'UPI_SORT','DIE_SIZE_WIDTH_UOM','DIE_SIZE_WIDTH_UOM','Die Size Width UOM'
UNION SELECT 'UPI_SORT','DIE_SIZE_WIDTH_X','DIE_SIZE_WIDTH_X','Die Size Width X'
UNION SELECT 'UPI_SORT','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'UPI_SORT','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'UPI_SORT','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'UPI_SORT','DIE_SINGULATION_INDICATOR','DIE_SINGULATION_INDICATOR','Die Singulation Indicator'
UNION SELECT 'UPI_SORT','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_SORT','DUAL_SALES_INDICATOR','DUAL_SALES_INDICATOR','Dual Sales Indicator'
UNION SELECT 'UPI_SORT','FRONTSIDE_WAFER_FLAG_INDICATOR','FRONTSIDE_WAFER_FLAG_INDICATOR','Frontside Wafer Flag Indicator'
UNION SELECT 'UPI_SORT','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'UPI_SORT','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_SORT','EXTERNAL_TO_DIEPREP_INDICATOR','EXTERNAL_TO_DIEPREP_INDICATOR','External to DiePrep Indicator'
UNION SELECT 'UPI_SORT','UNSORTED_EXTERNAL_SILICON_IND','UNSORTED_EXTERNAL_SILICON_IND','Unsorted External Silicon Ind'
UNION SELECT 'UPI_SORT','INTERNAL_FLOW_START_INDICATOR','INTERNAL_FLOW_START_INDICATOR','Internal Flow Start Indicator'
UNION SELECT 'UPI_STACK_COMBO','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_STACK_COMBO','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_STACK_COMBO','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'UPI_STACK_COMBO','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_STACK_COMBO','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'UPI_STACK_COMBO','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'UPI_STACK_COMBO','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'UPI_STACK_COMBO','MFG_PKG_CODE','MFG_PKG_CODE','Manufacturing Package Code'
UNION SELECT 'UPI_STACK_COMBO','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'UPI_STACK_COMBO','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP Estimate Physical Core Qty'
UNION SELECT 'UPI_STACK_COMBO','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP Est Phys Graphics Core Qty'
UNION SELECT 'UPI_STACK_COMBO','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'UPI_STACK_COMBO','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_STACK_COMBO','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'UPI_STACK_COMBO','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'UPI_STACK_COMBO','SOLDER_HEIGHT_TARGET_UM','SOLDER_HEIGHT_TARGET_UM','Solder Height Target Um'
UNION SELECT 'UPI_STACK_COMBO','TRADE_PACKAGE_TYPE','TRADE_PACKAGE_TYPE','Die Footprint for Trade'
UNION SELECT 'UPI_STACK_SILICON','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_STACK_SILICON','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_STACK_SILICON','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'UPI_STACK_SILICON','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_STACK_SILICON','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_STACK_SILICON','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'UPI_STACK_SILICON','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'UPI_STACK_SILICON','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'UPI_STACK_SILICON','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'UPI_STACK_SILICON','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_STACK_SILICON','DUAL_SALES_INDICATOR','DUAL_SALES_INDICATOR','Dual Sales Indicator'
UNION SELECT 'UPI_STACK_SILICON','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'UPI_STACK_SILICON','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_STACK_SILICON','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'UPI_STACK_SILICON','TRADE_PACKAGE_TYPE','TRADE_PACKAGE_TYPE','Die Footprint for Trade'
UNION SELECT 'UPI_TEST','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_TEST','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_TEST','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_TEST','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'UPI_TEST','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'UPI_TEST','TOTAL_FUNCTIONAL_CORE_COUNT','TOTAL_FUNCTIONAL_CORE_COUNT','Total Functional Core Count'
UNION SELECT 'UPI_TEST','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'UPI_TEST','INTEGRATED_GRAPHICS_FUNC_CORES','INTEGRATED_GRAPHICS_FUNC_CORES','Integrated Graphics Func Cores'
UNION SELECT 'UPI_TEST','LRP_EST_FUNCTIONAL_CORE_QTY','LRP_EST_FUNCTIONAL_CORE_QTY','LRP Est Functional Core Qty'
UNION SELECT 'UPI_TEST','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_TEST','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'UPI_TEST','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_TEST','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'UPI_TEST','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'UPI_TEST','INDIVIDUAL_MEMORY_CAPACITY','INDIVIDUAL_MEMORY_CAPACITY','Individual Memory Capacity';


    -- Step 1: Populate actual attribute data from uda_definition table
    UPDATE tgt
    SET tgt.att_idn = src.att_idn,      -- Get attribute ID
        tgt.att_nme = src.att_nme,      -- Get actual attribute name
        tgt.att_dsc = src.att_dsc       -- Get actual attribute description
    FROM #Updated tgt
    LEFT JOIN dbo.uda_definition src 
    ON src.att_nme = tgt.expected_att_nme;

    -- Step 2: Get item type code from uda_item_type table
    UPDATE tgt
    SET tgt.item_typ_cde = ui.item_typ_cde
    FROM #Updated tgt
    LEFT JOIN uda_item_type ui 
    ON ui.att_idn = tgt.att_idn;

    -- Step 3: Get actual item class description from item_type table
    UPDATE tgt
    SET tgt.itm_class = ui.item_typ_dsc
    FROM #Updated tgt
    LEFT JOIN item_type ui 
    ON ui.item_typ_cde = tgt.item_typ_cde;

    -- Step 4: Mark records as PASS when attribute exists and matches expected name
    UPDATE tgt
    SET tgt.assert = 'PASS',
        tgt.result = 'Match Found'
    FROM #Updated tgt
    JOIN dbo.uda_definition src 
    ON src.att_nme = tgt.expected_att_nme
    AND src.att_idn = tgt.att_idn;

    -- Step 5: Mark records as FAIL when attribute doesn't match or doesn't exist
    UPDATE tgt
    SET tgt.assert = 'FAIL',
        tgt.result = 'Match not Found'
    FROM #Updated tgt
    JOIN dbo.uda_definition src 
    ON src.att_nme <> tgt.expected_att_nme
    AND tgt.att_idn IS NULL;

    -- =====================================================================================
    -- TEST 2: ATTRIBUTE-TO-ITEM-TYPE ASSOCIATION VALIDATION
    -- Purpose: Validates that specific attributes are properly associated with item types
    -- Focus: Diverse item classes and their required attributes
    -- =====================================================================================
    

    -- Insert test data: Item class and attribute name combinations to validate
    INSERT INTO #Inserted (itm_class, att_nme,expected_att_nme,expected_att_dsc)
          SELECT 'BAGS_FI','BAG_ASSY_TYPE_FI','BAG_ASSY_TYPE_FI','BAG_ASSY_TYPE'
UNION SELECT 'BAGS_FI','BAG_CLOSURE_FI','BAG_CLOSURE_FI','BAG_CLOSURE'
UNION SELECT 'BAGS_FI','BAG_MATERIAL_ATTRIBUTES_FI','BAG_MATERIAL_ATTRIBUTES_FI','BAG_MATERIAL_ATTRIBUTES'
UNION SELECT 'BAGS_FI','BAG_MATERIAL_FI','BAG_MATERIAL_FI','BAG_MATERIAL'
UNION SELECT 'BAGS_FI','BAG_MATERIAL_GAUGE_FI','BAG_MATERIAL_GAUGE_FI','BAG_MATERIAL_GAUGE'
UNION SELECT 'BAGS_FI','BAG_PRINTED_PLAIN_FI','BAG_PRINTED_PLAIN_FI','BAG_PRINTED_PLAIN'
UNION SELECT 'BAGS_FI','BAG_SIZE_FI','BAG_SIZE_FI','BAG_SIZE'
UNION SELECT 'BAGS_FI','BAG_TYPE_FI','BAG_TYPE_FI','BAG_TYPE'
UNION SELECT 'BAGS_FI','CT_LEVEL_IND_FI','CT_LEVEL_IND_FI','CT_LEVEL_IND'
UNION SELECT 'BAGS_FI','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'BAGS_FI','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'BAGS_FI','MM_SHIP_MED_FI','MM_SHIP_MED_FI','MM_SHIP_MED'
UNION SELECT 'BAGS_FI','RETAIL_PKG_INDICATOR_FI','RETAIL_PKG_INDICATOR_FI','RETAIL_PKG_INDICATOR'
UNION SELECT 'BAGS_FI','RE_USED_FI','RE_USED_FI','RE_USED'
UNION SELECT 'BLANK_COUPON','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'BLANK_COUPON','END_OF_LINE','END_OF_LINE','END_OF_LINE'
UNION SELECT 'BLANK_COUPON','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'CARRIER-TRAY','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'CARRIER-TRAY','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'CARRIER_FOUP','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'CARRIER_FOUP','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'CFB_CNTR_FI','BOX_TYPE_FI','BOX_TYPE_FI','BOX_TYPE'
UNION SELECT 'CFB_CNTR_FI','CFB_CNTR_BREADTH_INTRNL_FI','CFB_CNTR_BREADTH_INTRNL_FI','CFB_CNTR_BREADTH_INTRNL'
UNION SELECT 'CFB_CNTR_FI','CFB_CNTR_HEIGHT_INTRNL_FI','CFB_CNTR_HEIGHT_INTRNL_FI','CFB_CNTR_HEIGHT_INTRNL'
UNION SELECT 'CFB_CNTR_FI','CFB_CNTR_LENGTH_INTRNL_FI','CFB_CNTR_LENGTH_INTRNL_FI','CFB_CNTR_LENGTH_INTRNL'
UNION SELECT 'CFB_CNTR_FI','CONTAINER_PRINTING_FI','CONTAINER_PRINTING_FI','CONTAINER_PRINTING'
UNION SELECT 'CFB_CNTR_FI','CORRUGATED_FIBERBOARD_MATL_FI','CORRUGATED_FIBERBOARD_MATL_FI','CORRUGATEDBERBOARD_MATL'
UNION SELECT 'CFB_CNTR_FI','CT_LEVEL_IND_FI','CT_LEVEL_IND_FI','CT_LEVEL_IND'
UNION SELECT 'CFB_CNTR_FI','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'CFB_CNTR_FI','INTL_FIBERBOARD_CASE_CODE_FI','INTL_FIBERBOARD_CASE_CODE_FI','INTLBERBOARD_CASE_CODE'
UNION SELECT 'CFB_CNTR_FI','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'CFB_CNTR_FI','MM_SHIP_MED_FI','MM_SHIP_MED_FI','MM_SHIP_MED'
UNION SELECT 'CFB_CNTR_FI','OUTERMOST_SHIPPING_CNTR_FI','OUTERMOST_SHIPPING_CNTR_FI','OUTERMOST_SHIPPING_CNTR'
UNION SELECT 'CFB_CNTR_FI','PRODUCT_LEVEL_IDENTIFICATION_FI','PRODUCT_LEVEL_IDENTIFICATION_FI','PRODUCT_LEVEL_IDENTIFICATION'
UNION SELECT 'CMP','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'CMP','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'CONTAINERS_FI','BOX_TYPE_FI','BOX_TYPE_FI','BOX_TYPE'
UNION SELECT 'CONTAINERS_FI','CNTR_ADDL_INFO_FI','CNTR_ADDL_INFO_FI','CNTR_ADDL_INFO'
UNION SELECT 'CONTAINERS_FI','CONTAINER_ASSY_TYPE_FI','CONTAINER_ASSY_TYPE_FI','CONTAINER_ASSY_TYPE'
UNION SELECT 'CONTAINERS_FI','CONTAINER_DEPTH_AMOUNT_FI','CONTAINER_DEPTH_AMOUNT_FI','CONTAINER_DEPTH_AMOUNT'
UNION SELECT 'CONTAINERS_FI','CONTAINER_LENGTH_AMOUNT_FI','CONTAINER_LENGTH_AMOUNT_FI','CONTAINER_LENGTH_AMOUNT'
UNION SELECT 'CONTAINERS_FI','CONTAINER_MATERIAL_FI','CONTAINER_MATERIAL_FI','CONTAINER_MATERIAL'
UNION SELECT 'CONTAINERS_FI','CONTAINER_STYLE_FI','CONTAINER_STYLE_FI','CONTAINER_STYLE'
UNION SELECT 'CONTAINERS_FI','CONTAINER_TYPE_FI','CONTAINER_TYPE_FI','CONTAINER_TYPE'
UNION SELECT 'CONTAINERS_FI','CONTAINER_WIDTH_AMOUNT_FI','CONTAINER_WIDTH_AMOUNT_FI','CONTAINER_WIDTH_AMOUNT'
UNION SELECT 'CONTAINERS_FI','CT_LEVEL_IND_FI','CT_LEVEL_IND_FI','CT_LEVEL_IND'
UNION SELECT 'CONTAINERS_FI','ECC_IND_FI','ECC_IND_FI','ECC_IND'
UNION SELECT 'CONTAINERS_FI','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'CONTAINERS_FI','MATERIAL_ATTRIBUTES_FI','MATERIAL_ATTRIBUTES_FI','MATERIAL_ATTRIBUTES'
UNION SELECT 'CONTAINERS_FI','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'CONTAINERS_FI','MM_SHIP_MED_FI','MM_SHIP_MED_FI','MM_SHIP_MED'
UNION SELECT 'CONTAINERS_FI','OEM_PN_FI','OEM_PN_FI','OEM_PN'
UNION SELECT 'CONTAINERS_FI','PRINTED_GRAPHICS_FI','PRINTED_GRAPHICS_FI','PRINTED_GRAPHICS'
UNION SELECT 'CONTAINERS_FI','PRODUCT_FAMILY_FI','PRODUCT_FAMILY_FI','PRODUCT_FAMILY'
UNION SELECT 'CONTAINERS_FI','RETAIL_PKG_INDICATOR_FI','RETAIL_PKG_INDICATOR_FI','RETAIL_PKG_INDICATOR'
UNION SELECT 'CONTAINERS_FI','RE_USED_FI','RE_USED_FI','RE_USED'
UNION SELECT 'CONTAINERS_FI','SHIP_CONTAINER_INDICATOR_FI','SHIP_CONTAINER_INDICATOR_FI','SHIP_CONTAINER_INDICATOR'
UNION SELECT 'DIE_BACKSIDE_FILM','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'DIE_BACKSIDE_FILM','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'DIE_EJECTOR','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'DIE_EJECTOR','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'DIE_PREP_BLADES','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'DIE_PREP_BLADES','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'DIE_PREP_CHEM','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'DIE_PREP_CHEM','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'DIE_PREP_TAPE','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'DIE_PREP_TAPE','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'DP_RCTNGL_COLLET','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'DP_RCTNGL_COLLET','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'DP_ROUND_COLLET','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'DP_ROUND_COLLET','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'DP_THINNING_WHEELS','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'DP_THINNING_WHEELS','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'EDGE_TRIM_BLADE','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'EDGE_TRIM_BLADE','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'EDGE_TRIM_DRSSR_BD','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'EDGE_TRIM_DRSSR_BD','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'EMBSD_CARRIER_TAPE','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'EMBSD_CARRIER_TAPE','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'FILTRATION','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'FILTRATION','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'FOUNDRY_SERVICES','ADDITIONAL_OFFERING_FEATURE','ADDITIONAL_OFFERING_FEATURE','Additional Offering Feature'
UNION SELECT 'FOUNDRY_SERVICES','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'FOUNDRY_SERVICES','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'FOUNDRY_SERVICES','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'FOUNDRY_SERVICES','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'FOUNDRY_SERVICES','TECHNOLOGY_AREA_VARIANT_TYPE','TECHNOLOGY_AREA_VARIANT_TYPE','Technology Area Variant Type'
UNION SELECT 'HBI_COLLATERAL','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'HBI_COLLATERAL','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'LABEL_BLANK_FI','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'LABEL_BLANK_FI','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'LITHO','ANCILLARY','ANCILLARY','Ancillary'
UNION SELECT 'LITHO','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'LITHO','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'LITHO','PHOTO_IMAGEABLE_DIELECTRIC','PHOTO_IMAGEABLE_DIELECTRIC','Photo Imageable Dielectric'
UNION SELECT 'LITHO','RESIST','RESIST','Resist'
UNION SELECT 'LITHO','TOPCOAT','TOPCOAT','TopCoat'
UNION SELECT 'LITHO','UNDERLAYER','UNDERLAYER','Underlayer'
UNION SELECT 'MRF','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'MRF','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'PKG_COMPONENTS_IF','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'PKG_COMPONENTS_IF','EQUIPMENT_ITEM_SPARE','EQUIPMENT_ITEM_SPARE','EQUIPMENT_ITEM_SPARE'
UNION SELECT 'PKG_COMPONENTS_IF','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'PLASTIC_TAPE_REEL','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'PLASTIC_TAPE_REEL','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'POCKET_CVR_TAPE','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'POCKET_CVR_TAPE','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'PRCSS_METAL_CARR','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'PRCSS_METAL_CARR','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'QUARTZWARE','CONTAMINANT','CONTAMINANT','CONTAMINANT'
UNION SELECT 'QUARTZWARE','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'QUARTZWARE','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'QUARTZWARE','RETURN_REASON_CODE','RETURN_REASON_CODE','RETURN_REASON_CODE'
UNION SELECT 'REEL','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'REEL','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'SBSTRT_PANEL_TRAY','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'SBSTRT_PANEL_TRAY','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'SBSTRT_PKG_TRAY','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'SBSTRT_PKG_TRAY','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'SMP','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'SMP','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'TARGET_ANODE','CONTAMINANT','CONTAMINANT','CONTAMINANT'
UNION SELECT 'TARGET_ANODE','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'TARGET_ANODE','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'TARGET_ANODE','RETURN_REASON_CODE','RETURN_REASON_CODE','RETURN_REASON_CODE'
UNION SELECT 'TC_NOZZLE','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'TC_NOZZLE','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'TEST_TIM','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'TEST_TIM','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'TP_REEL_PRTCTV_BND','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'TP_REEL_PRTCTV_BND','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'TRAY_AUTO_FOSB','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'TRAY_AUTO_FOSB','MAT_CATEGORY_FI','MAT_CATEGORY_FI','MAT_CATEGORY'
UNION SELECT 'UPI_ASSEMBLY','ADDITIONAL_OFFERING_FEATURE','ADDITIONAL_OFFERING_FEATURE','Additional Offering Feature'
UNION SELECT 'UPI_ASSEMBLY','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_ASSEMBLY','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'UPI_ASSEMBLY','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'UPI_ASSEMBLY','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_ASSEMBLY','PACKAGE_PLATFORM_CODE','PACKAGE_PLATFORM_CODE','Package Platform Code'
UNION SELECT 'UPI_ASSEMBLY','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_ASSEMBLY','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'UPI_ASSEMBLY','TECHNOLOGY_AREA_VARIANT_TYPE','TECHNOLOGY_AREA_VARIANT_TYPE','Technology Area Variant Type'
UNION SELECT 'UPI_BUMP','ADDITIONAL_OFFERING_FEATURE','ADDITIONAL_OFFERING_FEATURE','Additional Offering Feature'
UNION SELECT 'UPI_BUMP','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','CAPACITY CORRIDOR'
UNION SELECT 'UPI_BUMP','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','Capacity Corridor'
UNION SELECT 'UPI_BUMP','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_BUMP','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_BUMP','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'UPI_BUMP','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'UPI_BUMP','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_BUMP','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_BUMP','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'UPI_BUMP','TECHNOLOGY_AREA_VARIANT_TYPE','TECHNOLOGY_AREA_VARIANT_TYPE','Technology Area Variant Type'
UNION SELECT 'UPI_DIE_PREP','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','Capacity Corridor'
UNION SELECT 'UPI_DIE_PREP','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_DIE_PREP','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_FAB','ADDITIONAL_OFFERING_FEATURE','ADDITIONAL_OFFERING_FEATURE','Additional Offering Feature'
UNION SELECT 'UPI_FAB','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','CAPACITY CORRIDOR'
UNION SELECT 'UPI_FAB','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','Capacity Corridor'
UNION SELECT 'UPI_FAB','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_FAB','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_FAB','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'UPI_FAB','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'UPI_FAB','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_FAB','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_FAB','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'UPI_FAB','TECHNOLOGY_AREA_VARIANT_TYPE','TECHNOLOGY_AREA_VARIANT_TYPE','Technology Area Variant Type'
UNION SELECT 'UPI_FINISH','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_SORT','ADDITIONAL_OFFERING_FEATURE','ADDITIONAL_OFFERING_FEATURE','Additional Offering Feature'
UNION SELECT 'UPI_SORT','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','Capacity Corridor'
UNION SELECT 'UPI_SORT','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_SORT','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_SORT','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'UPI_SORT','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_SORT','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_SORT','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'UPI_SORT','TECHNOLOGY_AREA_VARIANT_TYPE','TECHNOLOGY_AREA_VARIANT_TYPE','Technology Area Variant Type'
UNION SELECT 'UPI_STACK_COMBO','ADDITIONAL_OFFERING_FEATURE','ADDITIONAL_OFFERING_FEATURE','Additional Offering Feature'
UNION SELECT 'UPI_STACK_COMBO','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','Capacity Corridor'
UNION SELECT 'UPI_STACK_COMBO','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_STACK_COMBO','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_STACK_COMBO','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_STACK_COMBO','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'UPI_STACK_COMBO','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'UPI_STACK_COMBO','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_STACK_COMBO','PACKAGE_PLATFORM_CODE','PACKAGE_PLATFORM_CODE','Package Platform Code'
UNION SELECT 'UPI_STACK_COMBO','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_STACK_COMBO','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'UPI_STACK_COMBO','TECHNOLOGY_AREA_VARIANT_TYPE','TECHNOLOGY_AREA_VARIANT_TYPE','Technology Area Variant Type'
UNION SELECT 'UPI_STACK_SILICON','ADDITIONAL_OFFERING_FEATURE','ADDITIONAL_OFFERING_FEATURE','Additional Offering Feature'
UNION SELECT 'UPI_STACK_SILICON','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','CAPACITY CORRIDOR'
UNION SELECT 'UPI_STACK_SILICON','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','Capacity Corridor'
UNION SELECT 'UPI_STACK_SILICON','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_STACK_SILICON','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_STACK_SILICON','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_STACK_SILICON','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'UPI_STACK_SILICON','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'UPI_STACK_SILICON','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_STACK_SILICON','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_STACK_SILICON','PROC_STACK_SI_GROUPING','PROC_STACK_SI_GROUPING','PROC Stack Si Grouping'
UNION SELECT 'UPI_STACK_SILICON','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'UPI_STACK_SILICON','TECHNOLOGY_AREA_VARIANT_TYPE','TECHNOLOGY_AREA_VARIANT_TYPE','Technology Area Variant Type'
UNION SELECT 'UPI_TEST','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_TEST','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_TEST','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_TEST','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_TEST','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'UPI_TEST','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'UPI_TEST','PINCOUNT','PINCOUNT','Lead Count'
UNION SELECT 'UPI_TEST','PERFORMANCE_GRADE_CODE','PERFORMANCE_GRADE_CODE','BIN Category'
UNION SELECT 'UPI_TEST','TOTAL_FUNCTIONAL_CORE_COUNT','TOTAL_FUNCTIONAL_CORE_COUNT','Total Functional Core Count'
UNION SELECT 'UPI_TEST','PHYSICAL_DIE_PER_PKG_QTY','PHYSICAL_DIE_PER_PKG_QTY','Number of Physical Die per Pac'
UNION SELECT 'UPI_TEST','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core'
UNION SELECT 'UPI_TEST','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'UPI_TEST','INDIVIDUAL_MEMORY_CAPACITY','INDIVIDUAL_MEMORY_CAPACITY','Individual Memory Capacity'


    -- Step 1: Get attribute ID for each attribute name
    UPDATE tgt
    SET tgt.att_idn = ud.att_idn,tgt.att_dsc = ud.att_dsc
    FROM #Inserted tgt
    LEFT JOIN dbo.uda_definition ud 
    ON ud.att_nme = tgt.att_nme;

    -- Step 2: Get item type code from item class description
    UPDATE tgt
    SET tgt.item_typ_cde = ui.item_typ_cde
    FROM #Inserted tgt
    LEFT JOIN item_type ui 
    ON ui.item_typ_dsc = tgt.itm_class;

    -- Step 3: Initialize all records as FAIL by default
    UPDATE #Inserted 
    SET assert = 'FAIL', 
        result = 'Match not Found';

    -- Step 4: Mark as PASS only when the attribute-item type combination exists
    UPDATE tgt
    SET tgt.assert = 'PASS', 
        tgt.result = 'Match Found'
    FROM #Inserted tgt
    INNER JOIN dbo.uda_item_type uit 
    ON uit.att_idn = tgt.att_idn 
       AND uit.item_typ_cde = tgt.item_typ_cde;

   
    -- =====================================================================================
    -- TEST 3: EXTENDED RIGID CONTAINER ATTRIBUTE VALIDATION
    -- Purpose: Validates extended attributes specifically for rigid containers
    -- Focus: Additional rigid container attributes including printing and art specifications
    -- =====================================================================================
    


    -- Insert test data: Extended rigid container attributes to validate
    INSERT INTO #Deleted (itm_class, att_nme, expected_att_nme,expected_att_dsc)
          SELECT 'BAGS_FI','BAG_ASSY_TYPE_FI','BAG_ASSY_TYPE_FI','BAG_ASSY_TYPE'
UNION SELECT 'BAGS_FI','RE_USED_FI','RE_USED_FI','RE_USED'
UNION SELECT 'BLANK_COUPON','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'BLANK_COUPON','COUPON_LENGTH_DIM','COUPON_LENGTH_DIM','COUPON_LENGTH_DIM'
UNION SELECT 'CPU','MEMORY_CHANNELS_QUANTITY','MEMORY_CHANNELS_QUANTITY','Memory Channels Quantity'
UNION SELECT 'CPU','PROCESSOR_BASE_CODE','PROCESSOR_BASE_CODE','Processor Base Code'
UNION SELECT 'CPU','MAX_TURBO_FREQUENCY_RATE','MAX_TURBO_FREQUENCY_RATE','Max Turbo Frequency Rate'
UNION SELECT 'CPU','PEG_SPEED_UNLOCK_INDICATOR','PEG_SPEED_UNLOCK_INDICATOR','PEG Speed Unlock Ind'
UNION SELECT 'CPU','TURBO_2_SMALL_CORE_FREQ_RATE','TURBO_2_SMALL_CORE_FREQ_RATE','Turbo 2 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_7_SMALL_CORE_FREQ_RATE','TURBO_7_SMALL_CORE_FREQ_RATE','Turbo 7 Small Core Freq Rate'
UNION SELECT 'CPU','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'CPU','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'CPU','FINSHED_GOOD_CATEGORY_TYPE','FINSHED_GOOD_CATEGORY_TYPE','Finished Good Category Type'
UNION SELECT 'CPU','MEMORY_ECC_SUPPORT_IND','MEMORY_ECC_SUPPORT_IND','Memory ECC Support Indicator'
UNION SELECT 'CPU','SMALL_CORE_SPEED','SMALL_CORE_SPEED','Small Core Speed'
UNION SELECT 'FILTRATION','FILT_CONFIGURATION','FILT_CONFIGURATION','FILT_CONFIGURATION'
UNION SELECT 'GPU','PACKAGE_SHORT_TEXT','PACKAGE_SHORT_TEXT','Package Short Text'
UNION SELECT 'GPU','TOTAL_CACHE_QTY','TOTAL_CACHE_QTY','Total Cache Qty'
UNION SELECT 'GPU','TOTAL_CACHE_QTY_UOM','TOTAL_CACHE_QTY_UOM','Total Cache Qty Uom Code'
UNION SELECT 'GPU','NULL','NULL','NULL'
UNION SELECT 'GPU','NULL','NULL','NULL'
UNION SELECT 'GPU','CPU_SLOT_TYPE','CPU_SLOT_TYPE','CPU Slot Type'
UNION SELECT 'GPU','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'GPU','COMMENTS','COMMENTS','Comments'
UNION SELECT 'GPU','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'MAT','MM-POW-SUP-FRE','MM-POW-SUP-FRE','Power Supply Frequency'
UNION SELECT 'MAT','TRADEMARK_NAME','TRADEMARK_NAME','Trademark/Family Name'
UNION SELECT 'P_SORT','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core Qty'
UNION SELECT 'P_SORT','MEMORY_CAPACITY','MEMORY_CAPACITY','Memory Capacity'
UNION SELECT 'P_SORT','ESTIMATED_DIE_SIZE_AREA_MM2','ESTIMATED_DIE_SIZE_AREA_MM2','Estimated Die Size Area MM2'
UNION SELECT 'P_SORT','WAFER_THICKNESS_DIMENSION','WAFER_THICKNESS_DIMENSION','Wafer Thickness Dimension'
UNION SELECT 'P_SORT','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_STACK_SILICON','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'P_STACK_SILICON','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'P_STACK_SILICON','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'P_STACK_SILICON','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core Qty'
UNION SELECT 'P_STACK_SILICON','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'P_STACK_SILICON','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_TEST','INDIVIDUAL_MEMORY_CAPACITY_UOM','INDIVIDUAL_MEMORY_CAPACITY_UOM','Individual Memory Capacity UOM'
UNION SELECT 'P_TEST','INTEGRATED_GRAPHICS_CORES_UOM','INTEGRATED_GRAPHICS_CORES_UOM','Integrated Graphics Cores UOM'
UNION SELECT 'P_TEST','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'SILICON_WAFER','NULL','NULL','NULL'
UNION SELECT 'SMP','NULL','NULL','NULL'
UNION SELECT 'SMP','NET_CONTENT_UOM','NET_CONTENT_UOM','NET_CONTENT_UOM'
UNION SELECT 'SMP','CHEMICAL_NAME','CHEMICAL_NAME','CHEMICAL_NAME'
UNION SELECT 'SMP','SHIPPING_METHOD_TYPE','SHIPPING_METHOD_TYPE','SHIPPING_METHOD_TYPE'
UNION SELECT 'SMP','NULL','NULL','NULL'
UNION SELECT 'SV','NULL','NULL','NULL'
UNION SELECT 'SV','NULL','NULL','NULL'
UNION SELECT 'SY','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'SY','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'SY','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'SY','PRODUCT_MODEL_CODE','PRODUCT_MODEL_CODE','Product Model Code'
UNION SELECT 'SY','MM-CPU-TYPE','MM-CPU-TYPE','CPU Processor Type'
UNION SELECT 'SY','MM-SUBCON-CODE','MM-SUBCON-CODE','Subcon Code'
UNION SELECT 'SY','DIE_CODE_NAME','DIE_CODE_NAME','Die Code Name'
UNION SELECT 'SY','MM-VOLT','MM-VOLT','Voltage Tolerance'
UNION SELECT 'SY','MM-CON-NO','MM-CON-NO','Connector Qty'
UNION SELECT 'SY','MM-POW-SUP-VOLT','MM-POW-SUP-VOLT','Power Supply Voltage'
UNION SELECT 'SY','MM-BUS-WIDTH','MM-BUS-WIDTH','Bus Width'
UNION SELECT 'SY','MM-COMM-SIGNAL-INTERFACE-TYPE','MM-COMM-SIGNAL-INTERFACE-TYPE','Comm Signal/Interface Type'
UNION SELECT 'SY','MM-CPU-QTY','MM-CPU-QTY','CPU Processor Qty'
UNION SELECT 'SY','MM-DISK-CONTROLLER-QTY','MM-DISK-CONTROLLER-QTY','Disk Controller Qty'
UNION SELECT 'SY','MM-DISK-DRIVE-AMOUNT','MM-DISK-DRIVE-AMOUNT','Disk Drive Amount'
UNION SELECT 'SY','MM-SLOTS','MM-SLOTS','Slots Qty'
UNION SELECT 'SY','MM-POWER-SUPPLY-QTY','MM-POWER-SUPPLY-QTY','Power Supply Qty'
UNION SELECT 'SY','MM-MEM1-AMT','MM-MEM1-AMT','Memory 1 Amount'
UNION SELECT 'SY','MM-MEM3-AMT','MM-MEM3-AMT','Memory 3 Amount'
UNION SELECT 'SY','MM-MEM2-TYPE','MM-MEM2-TYPE','Memory 2 Type'
UNION SELECT 'SY','MM-GRAPH-MFG-MODEL','MM-GRAPH-MFG-MODEL','Graphic Mfg Model'
UNION SELECT 'SY','MM-GRAPH-MEM-AMT','MM-GRAPH-MEM-AMT','Graphic Memory Amount'
UNION SELECT 'SY','MM-GRAPH-MEM-SPEED','MM-GRAPH-MEM-SPEED','Graphic Memory Speed'
UNION SELECT 'SY','MM-GRAPH-TYPE','MM-GRAPH-TYPE','Graphic Type'
UNION SELECT 'SY','MM-GRAPH-RESOL','MM-GRAPH-RESOL','Graphic Resolution'
UNION SELECT 'SY','MM-GRAPH-3D','MM-GRAPH-3D','Graphic 3D Vector Rate'
UNION SELECT 'SY','MM-ASIC-NAME','MM-ASIC-NAME','ASIC Name'
UNION SELECT 'SY','MM-CHIPSET','MM-CHIPSET','Chipset'
UNION SELECT 'SY','MM-COMMUNICATION-CHIP','MM-COMMUNICATION-CHIP','Comm Chip'
UNION SELECT 'SY','MM-DISK-DRIVE-BAY','MM-DISK-DRIVE-BAY','Drive Bay Qty'
UNION SELECT 'SY','ENCRYPTION','ENCRYPTION','Encryption'
UNION SELECT 'SY','MM-HOT-SWAP-DRIVE','MM-HOT-SWAP-DRIVE','Hot Swap Drive Qty'
UNION SELECT 'SY','MM-MEM1-SPEED','MM-MEM1-SPEED','Memory 1 Speed'
UNION SELECT 'SY','MM-MEM2-SPEED','MM-MEM2-SPEED','Memory 2 Speed'
UNION SELECT 'SY','MM-MEM3-SPEED','MM-MEM3-SPEED','Memory 3 Speed'
UNION SELECT 'SY','MM-POWER-SUPPLY-REDUNDANT','MM-POWER-SUPPLY-REDUNDANT','Power Supply Redundant Qty'
UNION SELECT 'SY','MM-PROD-CAT-SY','MM-PROD-CAT-SY','SY Category Type'
UNION SELECT 'SY','MM-SERVER-MANAGER','MM-SERVER-MANAGER','Server Manager Indicator'
UNION SELECT 'SY','SPEC_CODE','SPEC_CODE','Spec Code'
UNION SELECT 'SY','SPEC_SEQUENTIAL_NUMBER','SPEC_SEQUENTIAL_NUMBER','Spec Sequential Number'
UNION SELECT 'SY','MM-SYS-MEM','MM-SYS-MEM','System Memory'
UNION SELECT 'SY','MM-NETWORK-BANDWIDTH','MM-NETWORK-BANDWIDTH','Network Bandwidth/Interface'
UNION SELECT 'SY','TRADEMARK_NAME','TRADEMARK_NAME','Trademark/Family Name'
UNION SELECT 'SY','MM-MODEL','MM-MODEL','Model'
UNION SELECT 'SY','MM-PERIPHERAL-TYPE','MM-PERIPHERAL-TYPE','Peripheral Type'
UNION SELECT 'SY','MM-PERIPHERAL-CHARACTERISTIC','MM-PERIPHERAL-CHARACTERISTIC','Peripheral Characteristic'
UNION SELECT 'SY','MM-DISK-DRIVE2-AMOUNT','MM-DISK-DRIVE2-AMOUNT','Disk Drive 2 Amount'
UNION SELECT 'SY','MM-DISK-DRIVE2-TYPE','MM-DISK-DRIVE2-TYPE','Disk Drive2 Type'
UNION SELECT 'SY','MM-CLEAN-TAPE','MM-CLEAN-TAPE','Cleaning Tape'
UNION SELECT 'SY','MM-FEATURE','MM-FEATURE','Feature'
UNION SELECT 'SY','MM-CPU-ID','MM-CPU-ID','CPU Processor Id'
UNION SELECT 'SY','MM-CPU-SLOT-QTY','MM-CPU-SLOT-QTY','CPU Slot/Socket Quantity'
UNION SELECT 'SY','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'SY','EPM_ID','EPM_ID','External Product ID'
UNION SELECT 'SY','MARKET_CODE_NAME','MARKET_CODE_NAME','Market Code Name'
UNION SELECT 'SY','PROBE_QTY','PROBE_QTY','PROBE QUANTITY'
UNION SELECT 'TARGET_ANODE','PURITY','PURITY','PURITY'
UNION SELECT 'TARGET_ANODE','METAL_SHAPE','METAL_SHAPE','METAL_SHAPE'
UNION SELECT 'TC_NOZZLE','MESA_STANDOFF_X_DIMENSION','MESA_STANDOFF_X_DIMENSION','MESA_STANDOFF_X_DIMENSION'
UNION SELECT 'TEST_TIM','TEST_TIM_BARRIER_MATL_CODE','TEST_TIM_BARRIER_MATL_CODE','TEST_TIM_BARRIER_MATL_CODE'
UNION SELECT 'TEST_TIM','TEST_TIM_PAD_TYPE','TEST_TIM_PAD_TYPE','TEST_TIM_PAD_TYPE'
UNION SELECT 'TEST_TIM','TEST_TIM_PAD_X_DIM','TEST_TIM_PAD_X_DIM','TEST_TIM_PAD_X_DIM'
UNION SELECT 'TEST_TIM','TEST_TIM_PAD_Y_DIM','TEST_TIM_PAD_Y_DIM','TEST_TIM_PAD_Y_DIM'
UNION SELECT 'TEST_TIM','TEST_TIM_BARRIER_X_DIM','TEST_TIM_BARRIER_X_DIM','TEST_TIM_BARRIER_X_DIM'
UNION SELECT 'TEST_TIM','TEST_TIM_BARRIER_Y_DIM','TEST_TIM_BARRIER_Y_DIM','TEST_TIM_BARRIER_Y_DIM'
UNION SELECT 'TEST_TIM','TEST_TIM_BARRIER_Z_DIM','TEST_TIM_BARRIER_Z_DIM','TEST_TIM_BARRIER_Z_DIM'
UNION SELECT 'TP_REEL_PRTCTV_BND','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER','ECM_ITEM_NUMBER'
UNION SELECT 'TP_REEL_PRTCTV_BND','PRTCTV_BAND_LENGH_DIM','PRTCTV_BAND_LENGH_DIM','PRTCTV_BAND_LENGH_DIM'
UNION SELECT 'TRAY_AUTO_FOSB','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_ASSEMBLY','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'UPI_ASSEMBLY','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_ASSEMBLY','PACKAGE_PLATFORM_CODE','PACKAGE_PLATFORM_CODE','Package Platform Code'
UNION SELECT 'UPI_ASSEMBLY','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_ASSEMBLY','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'UPI_ASSEMBLY','TECHNOLOGY_AREA_VARIANT_TYPE','TECHNOLOGY_AREA_VARIANT_TYPE','Technology Area Variant Type'
UNION SELECT 'UPI_ASSEMBLY','DIE_CODE_NAME','DIE_CODE_NAME','Die Code Name'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','FOUNDRY_CUSTOMER_CODE','FOUNDRY_CUSTOMER_CODE','customer-code'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'UPI_ASSEMBLY','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_ASSEMBLY','SUB_CODE_NAME','SUB_CODE_NAME','Sub-Code Name'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_ASSEMBLY','PRODUCT_LINE','PRODUCT_LINE','Product Line'
UNION SELECT 'UPI_ASSEMBLY','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'UPI_ASSEMBLY','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'UPI_ASSEMBLY','MFG_PKG_CODE','MFG_PKG_CODE','Manufacturing Package Code'
UNION SELECT 'UPI_ASSEMBLY','PINCOUNT','PINCOUNT','Lead Count'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','TOTAL_FUNCTIONAL_CORE_COUNT','TOTAL_FUNCTIONAL_CORE_COUNT','Total Functional Core Count'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NOMEN_PROGRAM_LEVEL_CODE','NOMEN_PROGRAM_LEVEL_CODE','Nomenclature Program Level Cod'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','FOLLOW_ON_GENERATION_NUMBER','FOLLOW_ON_GENERATION_NUMBER','Follow on Generation Number'
UNION SELECT 'UPI_ASSEMBLY','STRATEGIC_ROADMAP_SEGMENT_CODE','STRATEGIC_ROADMAP_SEGMENT_CODE','Strategic Roadmap Segmentation'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','SUPPORTED_WRLS_PROTOCOL_CODE','SUPPORTED_WRLS_PROTOCOL_CODE','Supported Wireless Protocol Code'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','ASSEMBLY_FULL_TOPSIDE_MARK_ID','ASSEMBLY_FULL_TOPSIDE_MARK_ID','Assembly Top Side Mark Flag'
UNION SELECT 'UPI_ASSEMBLY','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_ASSEMBLY','NULL','NULL','NULL'
UNION SELECT 'UPI_BUMP','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_BUMP','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_BUMP','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_BUMP','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'UPI_BUMP','NULL','NULL','NULL'
UNION SELECT 'UPI_BUMP','NULL','NULL','NULL'
UNION SELECT 'UPI_BUMP','FOUNDRY_CUSTOMER_CODE','FOUNDRY_CUSTOMER_CODE','customer-code'
UNION SELECT 'UPI_BUMP','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_BUMP','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'UPI_BUMP','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'UPI_BUMP','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_BUMP','SUB_CODE_NAME','SUB_CODE_NAME','Sub-Code Name'
UNION SELECT 'UPI_BUMP','NULL','NULL','NULL'
UNION SELECT 'UPI_BUMP','FAB_DOT_PROCESS','FAB_DOT_PROCESS','Fab Dot Process'
UNION SELECT 'UPI_BUMP','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'UPI_BUMP','DIE_SINGULATION_INDICATOR','DIE_SINGULATION_INDICATOR','Die Singulation Indicator'
UNION SELECT 'UPI_BUMP','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_BUMP','NULL','NULL','NULL'
UNION SELECT 'UPI_BUMP','DUAL_SALES_INDICATOR','DUAL_SALES_INDICATOR','Dual Sales Indicator'
UNION SELECT 'UPI_DIE_PREP','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_DIE_PREP','SUB_CODE_NAME','SUB_CODE_NAME','Sub-Code Name'
UNION SELECT 'UPI_DIE_PREP','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_DIE_PREP','NULL','NULL','NULL'
UNION SELECT 'UPI_DIE_PREP','NULL','NULL','NULL'
UNION SELECT 'UPI_DIE_PREP','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'UPI_DIE_PREP','NULL','NULL','NULL'
UNION SELECT 'UPI_DIE_PREP','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_DIE_PREP','DUAL_SALES_INDICATOR','DUAL_SALES_INDICATOR','Dual Sales Indicator'
UNION SELECT 'UPI_DIE_PREP','REMNANT_SCRAP_DIE_ALLOWED_IND','REMNANT_SCRAP_DIE_ALLOWED_IND','REMNANT SCRAP DIE ALLOWED'
UNION SELECT 'UPI_DIE_PREP','NULL','NULL','NULL'
UNION SELECT 'UPI_DIE_PREP','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_DIE_PREP','MAX_FABLOT_ALLOWED','MAX_FABLOT_ALLOWED','MAX FABLOT ALLOWED'
UNION SELECT 'UPI_DIE_PREP','WAFER_BANK','WAFER_BANK','WAFER BANK'
UNION SELECT 'UPI_DIE_PREP','WAFER_ASSY_TOP_BOTTOM_INDICATOR','WAFER_ASSY_TOP_BOTTOM_INDICATOR','WAFER ASSY TOP BOTTOM ID'
UNION SELECT 'UPI_DIE_PREP','CUSTOMER_PART_NUMBER','CUSTOMER_PART_NUMBER','CUSTOMER PART NUMBER'
UNION SELECT 'UPI_DIE_PREP','NULL','NULL','NULL'
UNION SELECT 'UPI_DIE_PREP','NULL','NULL','NULL'
UNION SELECT 'UPI_FAB','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_FAB','NULL','NULL','NULL'
UNION SELECT 'UPI_FAB','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_FAB','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_FAB','FAB_DOT_PROCESS','FAB_DOT_PROCESS','Fab Dot Process'
UNION SELECT 'UPI_FAB','FAB_PROCESS_TECHNOLOGY','FAB_PROCESS_TECHNOLOGY','Fab Process Technology'
UNION SELECT 'UPI_SORT','MEMORY_DENSITY_UOM','MEMORY_DENSITY_UOM','Density Unit of Measure'
UNION SELECT 'UPI_SORT','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','FAB_DOT_PROCESS','FAB_DOT_PROCESS','Fab Dot Process'
UNION SELECT 'UPI_SORT','FAB_PROCESS_TECHNOLOGY','FAB_PROCESS_TECHNOLOGY','Fab Process Technology'
UNION SELECT 'UPI_SORT','GROSS_DIE_PER_WAFER','GROSS_DIE_PER_WAFER','Gross Die Per Wafer'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','PRODUCT_LINE','PRODUCT_LINE','Product Line'
UNION SELECT 'UPI_SORT','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_SORT','DIE_SIZE_LENGTH_Y','DIE_SIZE_LENGTH_Y','Die Size Length Y'
UNION SELECT 'UPI_SORT','DIE_SIZE_WIDTH_X','DIE_SIZE_WIDTH_X','Die Size Width X'
UNION SELECT 'UPI_SORT','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','MEMORY_TYPE_NAME','MEMORY_TYPE_NAME','MEMORY TYPE NAME'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'UPI_SORT','MEMORY_SPEED_UOM_CODE','MEMORY_SPEED_UOM_CODE','MEMORY SPEED UOM CODE'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','REMNANT_SCRAP_DIE_ALLOWED_IND','REMNANT_SCRAP_DIE_ALLOWED_IND','REMNANT SCRAP DIE ALLOWED'
UNION SELECT 'UPI_SORT','FRONTSIDE_BACKSIDE_WFR_FLG_IND','FRONTSIDE_BACKSIDE_WFR_FLG_IND','FRONTSIDE BACKSIDE WFR FLG IND'
UNION SELECT 'UPI_SORT','SYNTHETIC_EFUSE_FLAG_INDICATOR','SYNTHETIC_EFUSE_FLAG_INDICATOR','SYNTHETIC EFUSE FLAG IND'
UNION SELECT 'UPI_SORT','SYNTHETIC_EFUSE_PREFIX_DSC','SYNTHETIC_EFUSE_PREFIX_DSC','SYNTHETIC EFUSE PREFIX DSC'
UNION SELECT 'UPI_SORT','FRONTSIDE_WAFER_FLAG_INDICATOR','FRONTSIDE_WAFER_FLAG_INDICATOR','Frontside Wafer Flag Indicator'
UNION SELECT 'UPI_SORT','WAFER_NUM_POSITION_DSC','WAFER_NUM_POSITION_DSC','WAFER NUM POSITION DSC'
UNION SELECT 'UPI_SORT','INCOMING_WAFER_CARRIER_TYPE','INCOMING_WAFER_CARRIER_TYPE','INCOMING WAFER CARRIER TYPE'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'UPI_SORT','WAFER_PREP_PROCESSING_INDICATOR','WAFER_PREP_PROCESSING_INDICATOR','WFR PREP  IND'
UNION SELECT 'UPI_SORT','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_SORT','MAX_FABLOT_ALLOWED','MAX_FABLOT_ALLOWED','MAX FABLOT ALLOWED'
UNION SELECT 'UPI_SORT','WAFER_BANK','WAFER_BANK','WAFER BANK'
UNION SELECT 'UPI_SORT','WAFER_ASSY_TOP_BOTTOM_INDICATOR','WAFER_ASSY_TOP_BOTTOM_INDICATOR','WAFER ASSY TOP BOTTOM ID'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','EXTERNAL_TO_DIEPREP_INDICATOR','EXTERNAL_TO_DIEPREP_INDICATOR','External to DiePrep Indicator'
UNION SELECT 'UPI_SORT','MOISTURE_EXPIRATION_TIMER_IND','MOISTURE_EXPIRATION_TIMER_IND','MOISTURE EXPIRATION TIMER IND'
UNION SELECT 'UPI_SORT','UNSORTED_EXTERNAL_SILICON_IND','UNSORTED_EXTERNAL_SILICON_IND','Unsorted External Silicon Ind'
UNION SELECT 'UPI_SORT','CUSTOMER_PART_NUMBER','CUSTOMER_PART_NUMBER','CUSTOMER PART NUMBER'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','NULL','NULL','NULL'
UNION SELECT 'UPI_SORT','INTERNAL_FLOW_START_INDICATOR','INTERNAL_FLOW_START_INDICATOR','Internal Flow Start Indicator'
UNION SELECT 'UPI_SORT','ITQ_ID','ITQ_ID','ITQ ID'
UNION SELECT 'UPI_STACK_COMBO','ADDITIONAL_OFFERING_FEATURE','ADDITIONAL_OFFERING_FEATURE','Additional Offering Feature'
UNION SELECT 'UPI_STACK_COMBO','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','Capacity Corridor'
UNION SELECT 'UPI_STACK_COMBO','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_STACK_COMBO','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_STACK_COMBO','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'UPI_STACK_COMBO','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'UPI_STACK_COMBO','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'UPI_STACK_COMBO','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_STACK_COMBO','PACKAGE_PLATFORM_CODE','PACKAGE_PLATFORM_CODE','Package Platform Code'
UNION SELECT 'UPI_STACK_COMBO','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_STACK_COMBO','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type'
UNION SELECT 'UPI_STACK_COMBO','TECHNOLOGY_AREA_VARIANT_TYPE','TECHNOLOGY_AREA_VARIANT_TYPE','Technology Area Variant Type'
UNION SELECT 'UPI_STACK_COMBO','DIE_CODE_NAME','DIE_CODE_NAME','Die Code Name'
UNION SELECT 'UPI_STACK_COMBO','CUSTOM_INDICATOR','CUSTOM_INDICATOR','Custom Indicator'
UNION SELECT 'UPI_STACK_COMBO','CUSTOMER_CUSTOM_PRODUCT','CUSTOMER_CUSTOM_PRODUCT','Customer Custom Product'
UNION SELECT 'UPI_STACK_COMBO','FOUNDRY_CUSTOMER_CODE','FOUNDRY_CUSTOMER_CODE','customer-code'
UNION SELECT 'UPI_STACK_COMBO','ENCRYPTION_CODE_NAME','ENCRYPTION_CODE_NAME','Encryption Code Name'
UNION SELECT 'UPI_STACK_COMBO','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'UPI_STACK_COMBO','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'UPI_STACK_COMBO','FAB_DOT_PROCESS','FAB_DOT_PROCESS','Fab Dot Process'
UNION SELECT 'UPI_STACK_COMBO','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'UPI_STACK_COMBO','PRODUCT_LINE','PRODUCT_LINE','Product Line'
UNION SELECT 'UPI_STACK_COMBO','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'UPI_STACK_COMBO','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'UPI_STACK_COMBO','MFG_PKG_CODE','MFG_PKG_CODE','Manufacturing Package Code'
UNION SELECT 'UPI_STACK_COMBO','NOMEN_PROGRAM_LEVEL_CODE','NOMEN_PROGRAM_LEVEL_CODE','Nomenclature Program Level Cod'
UNION SELECT 'UPI_STACK_COMBO','NOMEN_PROGRAM_SCOPE_CODE','NOMEN_PROGRAM_SCOPE_CODE','Nomenclature Program Scope Cod'
UNION SELECT 'UPI_STACK_COMBO','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'UPI_STACK_COMBO','FOLLOW_ON_GENERATION_NUMBER','FOLLOW_ON_GENERATION_NUMBER','Follow on Generation Number'
UNION SELECT 'UPI_STACK_COMBO','DIE_ARCHITECTURE_CODE','DIE_ARCHITECTURE_CODE','Die Architecture Code'
UNION SELECT 'UPI_STACK_COMBO','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP Estimate Physical Core Qty'
UNION SELECT 'UPI_STACK_COMBO','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP Est Phys Graphics Core Qty'
UNION SELECT 'UPI_STACK_COMBO','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'UPI_STACK_COMBO','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'UPI_STACK_COMBO','MASTER_STACK_ID','MASTER_STACK_ID','MASTER BUMP INDICATOR'
UNION SELECT 'UPI_STACK_COMBO','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'UPI_STACK_COMBO','CUSTOMER_PART_NUMBER','CUSTOMER_PART_NUMBER','CUSTOMER PART NUMBER'
UNION SELECT 'UPI_STACK_COMBO','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'UPI_STACK_COMBO','SOLDER_ON_DIE_INDICATOR','SOLDER_ON_DIE_INDICATOR','PSB SOLDER ON DIE INDICATOR'
UNION SELECT 'UPI_STACK_COMBO','BACKSIDE_METAL_INDICATOR','BACKSIDE_METAL_INDICATOR','BACKSIDE METAL INDICATOR'
UNION SELECT 'UPI_STACK_COMBO','TRADE_PACKAGE_TYPE','TRADE_PACKAGE_TYPE','Die Footprint for Trade'
UNION SELECT 'UPI_STACK_COMBO','ADVANCED_PKG_PROCESS_TECH_CODE','ADVANCED_PKG_PROCESS_TECH_CODE','ADVANCED PACKAGE PROCESS TECH'
UNION SELECT 'UPI_STACK_COMBO','ITQ_ID','ITQ_ID','ITQ ID'
UNION SELECT 'UPI_STACK_SILICON','CAPACITY_CORRIDOR','CAPACITY_CORRIDOR','Capacity Corridor'
UNION SELECT 'UPI_STACK_SILICON','CAPACITY_GROUP','CAPACITY_GROUP','Capacity Group'
UNION SELECT 'UPI_STACK_SILICON','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'UPI_STACK_SILICON','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'UPI_STACK_SILICON','OFFERING_AREA_TYPE','OFFERING_AREA_TYPE','Offering Area Type'
UNION SELECT 'UPI_STACK_SILICON','OFFERING_FEATURE_GROUPING','OFFERING_FEATURE_GROUPING','Offering Feature Grouping'
UNION SELECT 'UPI_STACK_SILICON','PORTFOLIO_TYPE','PORTFOLIO_TYPE','Portfolio Type'
UNION SELECT 'UPI_STACK_SILICON','PROC_STACK_SI_GROUPING','PROC_STACK_SI_GROUPING','PROC Stack Si Grouping'
UNION SELECT 'UPI_STACK_SILICON','TECHNOLOGY_AREA_TYPE','TECHNOLOGY_AREA_TYPE','Technology Area Type';



    -- Step 1: Get attribute ID for each attribute name
    UPDATE tgt
    SET tgt.att_idn = ud.att_idn
    FROM #Deleted tgt
    LEFT JOIN dbo.uda_definition ud 
    ON ud.att_nme = tgt.att_nme;

    -- Step 2: Get item type code from item class description
    UPDATE tgt
    SET tgt.item_typ_cde = ui.item_typ_cde
    FROM #Deleted tgt
    LEFT JOIN item_type ui 
    ON ui.item_typ_dsc = tgt.itm_class;

    -- Step 3: Initialize all records as FAIL by default
    UPDATE #Deleted 
    SET assert = 'FAIL', 
        result = 'Match not Found';

    -- Alternative error handling (commented out): Specific error messages for NULL cases
    -- Handle NULL cases with specific messages
    --UPDATE #Deleted 
    --SET result = 'Attribute not found in uda_definition'
    --WHERE att_idn IS NULL;

    --UPDATE #Deleted 
    --SET result = 'Item type not found'
    --WHERE item_typ_cde IS NULL AND att_idn IS NOT NULL;

    -- Step 4: Mark as PASS only when the attribute-item type combination exists
    UPDATE tgt
    SET tgt.assert = 'PASS', 
        tgt.result = 'Match Found'
    FROM #Deleted tgt
    INNER JOIN dbo.uda_item_type uit 
    ON uit.att_idn = tgt.att_idn 
       AND uit.item_typ_cde = tgt.item_typ_cde;

    -- =====================================================================================
    -- RESULTS: Display validation results for all three tests
    -- =====================================================================================
    
    -- Test 1 Results: Attribute name and description validation
    SELECT 
        att_idn,                -- Attribute ID
        item_typ_cde,          -- Item type code
        itm_class,             -- Item class name
        expected_att_nme,      -- Expected attribute name
        att_nme,               -- Actual attribute name
        expected_att_dsc,      -- Expected attribute description
        att_dsc,               -- Actual attribute description
        assert,                -- Test result (PASS/FAIL)
        result                 -- Result message
    FROM #Updated;

    -- Test 2 Results: Attribute-to-item-type association validation
    SELECT 
        att_idn,                -- Attribute ID
        item_typ_cde,          -- Item type code
        itm_class,             -- Item class name
        expected_att_nme,      -- Expected attribute name
        att_nme,               -- Actual attribute name
        expected_att_dsc,      -- Expected attribute description
        att_dsc,               -- Actual attribute description
        assert,                -- Test result (PASS/FAIL)
        result                 -- Result message
    FROM #Inserted;

    -- Test 3 Results: Extended rigid container attribute validation
    SELECT 
        att_idn,                -- Attribute ID
        item_typ_cde,          -- Item type code
        itm_class,             -- Item class name
        expected_att_nme,      -- Expected attribute name
        att_nme,               -- Actual attribute name
        expected_att_dsc,      -- Expected attribute description
        att_dsc,               -- Actual attribute description
        assert,                -- Test result (PASS/FAIL)
        result                 -- Result message
    FROM #Deleted;

END TRY
BEGIN CATCH
    -- =====================================================================================
    -- ERROR HANDLING: Display error information if any step fails
    -- =====================================================================================
    PRINT 'Error occurred during execution.';
    PRINT 'Message     : ' + ERROR_MESSAGE();
    PRINT 'Line        : ' + CAST(ERROR_LINE() AS VARCHAR);
        
END CATCH
END

