-- Script Name: UDA Validation Test Suite
-- Purpose: Validates User Defined Attributes (UDA) and their associations with item types
-- Author: [Francis]
-- Date: [26-11-2025]
-- Description: This script performs three validation tests: for DivisionId 10
--              1. Attribute name and description validation
--              2. Attribute-to-item-type association validation  
--              3. Extended rigid container attribute validation
-- =====================================================================================
USE speed_2max;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET NOCOUNT ON;
GO

BEGIN
BEGIN TRY
    -- =====================================================================================
    -- CLEANUP: Drop temporary tables if they exist from previous runs
    -- =====================================================================================
    DROP TABLE IF EXISTS #Updated;
    DROP TABLE IF EXISTS #Inserted;
    DROP TABLE IF EXISTS #Deleted;
     -- Create temporary table for Test 1
    CREATE TABLE #Updated (
        att_idn                 int,            -- Attribute ID from uda_definition
        item_typ_cde           VARCHAR(10),    -- Item type code
        expected_itm_class     VARCHAR(70),    -- Expected item class name
        itm_class              VARCHAR(70),    -- Actual item class name
        expected_att_nme       VARCHAR(70),    -- Expected attribute name
        att_nme                VARCHAR(70),    -- Actual attribute name
        expected_att_dsc       VARCHAR(70),    -- Expected attribute description
        att_dsc                VARCHAR(50),    -- Actual attribute description
        result                 VARCHAR(70),    -- Test result message
        assert                 CHAR(4) DEFAULT 'FAIL'  -- Test status (PASS/FAIL)
    );
        -- Create temporary table for Test 2
    CREATE TABLE #Inserted (
        att_idn                 int,            -- Attribute ID from uda_definition
        item_typ_cde           VARCHAR(10),    -- Item type code
        expected_itm_class     VARCHAR(70),    -- Expected item class name
        itm_class              VARCHAR(70),    -- Actual item class name
        expected_att_nme       VARCHAR(70),    -- Expected attribute name
        att_nme                VARCHAR(70),    -- Actual attribute name
        expected_att_dsc       VARCHAR(70),    -- Expected attribute description
        att_dsc                VARCHAR(50),    -- Actual attribute description
        result                 VARCHAR(70),    -- Test result message
        assert                 CHAR(4) DEFAULT 'FAIL'  -- Test status (PASS/FAIL)
    );
        -- Create temporary table for Test 3
    CREATE TABLE #Deleted (
        att_idn                 int,            -- Attribute ID from uda_definition
        item_typ_cde           VARCHAR(10),    -- Item type code
        expected_itm_class     VARCHAR(70),    -- Expected item class name
        itm_class              VARCHAR(70),    -- Actual item class name
        expected_att_nme       VARCHAR(70),    -- Expected attribute name
        att_nme                VARCHAR(70),    -- Actual attribute name
        expected_att_dsc       VARCHAR(70),    -- Expected attribute description
        att_dsc                VARCHAR(50),    -- Actual attribute description
        result                 VARCHAR(70),    -- Test result message
        assert                 CHAR(4) DEFAULT 'FAIL'  -- Test status (PASS/FAIL)
    );
    -- =====================================================================================
    -- TEST 1: ATTRIBUTE NAME AND DESCRIPTION VALIDATION
    -- Purpose: Validates that specific attributes exist with correct names and descriptions
    -- Focus: Packaging-related attributes for folding cartons and rigid containers
    -- =====================================================================================
    
   
    -- Insert test data: Expected attribute name and description pairs
    INSERT INTO #Updated (itm_class, expected_att_nme, att_nme,expected_att_dsc)
          SELECT 'ASIC_FG','EXTERNAL_REVISION','EXTERNAL_REVISION','External Revision'
UNION SELECT 'ASIC_FG','TRANSISTOR_FAB_PROCESS_TECH','TRANSISTOR_FAB_PROCESS_TECH','Transistor Fab Process Tech'
UNION SELECT 'ASIC_FG','MARKETING_PACKAGE_DESIGNATOR','MARKETING_PACKAGE_DESIGNATOR','Marketing Package Designator'
UNION SELECT 'ASIC_FG','TRADEMARK_NAME','TRADEMARK_NAME','Trademark Name'
UNION SELECT 'ASIC_FG','PACKAGE_SHORT_TEXT','PACKAGE_SHORT_TEXT','Package Short Text'
UNION SELECT 'ASIC_FG','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'ASIC_FG','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'ASIC_FG','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'ASIC_FG','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'ASIC_FG','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'ASIC_FG','EXTERNAL_STEPPING','EXTERNAL_STEPPING','External Stepping'
UNION SELECT 'ASIC_FG','FINISHED_GOOD_TYPE','FINISHED_GOOD_TYPE','Finished Good Type'
UNION SELECT 'ASIC_FG','ULT_SCAN_FOR_DC_OPEN_BOX','ULT_SCAN_FOR_DC_OPEN_BOX','ULT Scan for DC Open Box'
UNION SELECT 'ASIC_FG','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'ASIC_FG','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'ASIC_FG','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'ASIC_FG','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'ASIC_FG','FINSHED_GOOD_CATEGORY_TYPE','FINSHED_GOOD_CATEGORY_TYPE','Finished Good Category Type'
UNION SELECT 'ASIC_FG','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'ASIC_FG','MULTIPLE_MARK_NAME','MULTIPLE_MARK_NAME','Multiple Mark Name'
UNION SELECT 'ASIC_FG','INTERNAL_PLANNING_DESCRIPTOR','INTERNAL_PLANNING_DESCRIPTOR','Internal Planning Descriptor'
UNION SELECT 'ASIC_FG','TRADE_PACKAGE_TYPE','TRADE_PACKAGE_TYPE','Die Footprint for Trade'
UNION SELECT 'BD','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'BD','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'CHIPSETS_IC','EXTERNAL_REVISION','EXTERNAL_REVISION','External Revision'
UNION SELECT 'CHIPSETS_IC','TRANSISTOR_FAB_PROCESS_TECH','TRANSISTOR_FAB_PROCESS_TECH','Transistor Fab Process Tech'
UNION SELECT 'CHIPSETS_IC','MARKETING_PACKAGE_DESIGNATOR','MARKETING_PACKAGE_DESIGNATOR','Marketing Package Designator'
UNION SELECT 'CHIPSETS_IC','TRADEMARK_NAME','TRADEMARK_NAME','Trademark Name'
UNION SELECT 'CHIPSETS_IC','PACKAGE_SHORT_TEXT','PACKAGE_SHORT_TEXT','Package Short Text'
UNION SELECT 'CHIPSETS_IC','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'CHIPSETS_IC','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'CHIPSETS_IC','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'CHIPSETS_IC','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'CHIPSETS_IC','EXTERNAL_STEPPING','EXTERNAL_STEPPING','External Stepping'
UNION SELECT 'CHIPSETS_IC','FINISHED_GOOD_TYPE','FINISHED_GOOD_TYPE','Finished Good Type'
UNION SELECT 'CHIPSETS_IC','ULT_SCAN_FOR_DC_OPEN_BOX','ULT_SCAN_FOR_DC_OPEN_BOX','ULT Scan for DC Open Box'
UNION SELECT 'CHIPSETS_IC','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'CHIPSETS_IC','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'CHIPSETS_IC','DYNAMIC_SKUING_INDICATOR','DYNAMIC_SKUING_INDICATOR','Dynamic Skuing Indicator'
UNION SELECT 'CHIPSETS_IC','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'CHIPSETS_IC','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'CHIPSETS_IC','FINSHED_GOOD_CATEGORY_TYPE','FINSHED_GOOD_CATEGORY_TYPE','Finished Good Category Type'
UNION SELECT 'CONNECTIVITY','EXTERNAL_REVISION','EXTERNAL_REVISION','External Revision'
UNION SELECT 'CONNECTIVITY','TRANSISTOR_FAB_PROCESS_TECH','TRANSISTOR_FAB_PROCESS_TECH','Transistor Fab Process Tech'
UNION SELECT 'CONNECTIVITY','MARKETING_PACKAGE_DESIGNATOR','MARKETING_PACKAGE_DESIGNATOR','Marketing Package Designator'
UNION SELECT 'CONNECTIVITY','TRADEMARK_NAME','TRADEMARK_NAME','Trademark Name'
UNION SELECT 'CONNECTIVITY','PACKAGE_SHORT_TEXT','PACKAGE_SHORT_TEXT','Package Short Text'
UNION SELECT 'CONNECTIVITY','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'CONNECTIVITY','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'CONNECTIVITY','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'CONNECTIVITY','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'CONNECTIVITY','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'CONNECTIVITY','EXTERNAL_STEPPING','EXTERNAL_STEPPING','External Stepping'
UNION SELECT 'CONNECTIVITY','FINISHED_GOOD_TYPE','FINISHED_GOOD_TYPE','Finished Good Type'
UNION SELECT 'CONNECTIVITY','ULT_SCAN_FOR_DC_OPEN_BOX','ULT_SCAN_FOR_DC_OPEN_BOX','ULT Scan for DC Open Box'
UNION SELECT 'CONNECTIVITY','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'CONNECTIVITY','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'CONNECTIVITY','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'CONNECTIVITY','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'CONNECTIVITY','FINSHED_GOOD_CATEGORY_TYPE','FINSHED_GOOD_CATEGORY_TYPE','Finished Good Category Type'
UNION SELECT 'CONNECTIVITY','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'CONNECTIVITY','MULTIPLE_MARK_NAME','MULTIPLE_MARK_NAME','Multiple Mark Name'
UNION SELECT 'CONNECTIVITY','INTERNAL_PLANNING_DESCRIPTOR','INTERNAL_PLANNING_DESCRIPTOR','Internal Planning Descriptor'
UNION SELECT 'CONNECTIVITY','TRADE_PACKAGE_TYPE','TRADE_PACKAGE_TYPE','Die Footprint for Trade'
UNION SELECT 'CPU','SPEED_UOM','SPEED_UOM','Speed UOM'
UNION SELECT 'CPU','EXTERNAL_REVISION','EXTERNAL_REVISION','External Revision'
UNION SELECT 'CPU','TRANSISTOR_FAB_PROCESS_TECH','TRANSISTOR_FAB_PROCESS_TECH','Transistor Fab Process Tech'
UNION SELECT 'CPU','MARKETING_PACKAGE_DESIGNATOR','MARKETING_PACKAGE_DESIGNATOR','Marketing Package Designator'
UNION SELECT 'CPU','TRADEMARK_NAME','TRADEMARK_NAME','Trademark Name'
UNION SELECT 'CPU','PACKAGE_SHORT_TEXT','PACKAGE_SHORT_TEXT','Package Short Text'
UNION SELECT 'CPU','TOTAL_CACHE_QTY','TOTAL_CACHE_QTY','Total Cache Qty'
UNION SELECT 'CPU','TOTAL_CACHE_QTY_UOM','TOTAL_CACHE_QTY_UOM','Total Cache Qty Uom Code'
UNION SELECT 'CPU','CPU_SLOT_TYPE','CPU_SLOT_TYPE','CPU Slot Type'
UNION SELECT 'CPU','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'CPU','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'CPU','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'CPU','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'CPU','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'CPU','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'CPU','EXTERNAL_STEPPING','EXTERNAL_STEPPING','External Stepping'
UNION SELECT 'CPU','TOTAL_FUNCTIONAL_CORE_COUNT','TOTAL_FUNCTIONAL_CORE_COUNT','Total Functional Core Count'
UNION SELECT 'CPU','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core Qty'
UNION SELECT 'CPU','THERMAL_DESIGN_POWER_UOM','THERMAL_DESIGN_POWER_UOM','Thermal Design Power UOM'
UNION SELECT 'CPU','MEMORY_MODULES_PER_CHANNEL','MEMORY_MODULES_PER_CHANNEL','Memory Modules per Channel'
UNION SELECT 'CPU','MEMORY_CHANNELS_QUANTITY','MEMORY_CHANNELS_QUANTITY','Memory Channels Quantity'
UNION SELECT 'CPU','MEMORY_CAPACITY','MEMORY_CAPACITY','Memory Capacity'
UNION SELECT 'CPU','MEMORY_CAPACITY_UOM','MEMORY_CAPACITY_UOM','Memory Capacity UOM'
UNION SELECT 'CPU','INTEL_HYPER_THREAD_TECH_IND','INTEL_HYPER_THREAD_TECH_IND','Intel Hyper Thread Tech Ind'
UNION SELECT 'CPU','MAX_TURBO_FREQUENCY_UOM','MAX_TURBO_FREQUENCY_UOM','Max Turbo Frequency Rate UOM'
UNION SELECT 'CPU','MAX_THREADS_PER_PROCESSOR_QTY','MAX_THREADS_PER_PROCESSOR_QTY','Max Threads per Processor Qty'
UNION SELECT 'CPU','ERROR_CORRECTION_CODE_IND','ERROR_CORRECTION_CODE_IND','Error Correction Code Ind'
UNION SELECT 'CPU','MAX_NUMBER_OF_PEG_LANES','MAX_NUMBER_OF_PEG_LANES','Max Number of PEG Lanes'
UNION SELECT 'CPU','TURBO_FREQUENCY_UNLOCKED_IND','TURBO_FREQUENCY_UNLOCKED_IND','Turbo Frequency Unlocked Ind'
UNION SELECT 'CPU','MEMORY_BUS_SPEED_UNLOCK_IND','MEMORY_BUS_SPEED_UNLOCK_IND','Memory Bus Speed Unlock Ind'
UNION SELECT 'CPU','PEG_SPEED_UNLOCK_INDICATOR','PEG_SPEED_UNLOCK_INDICATOR','PEG Speed Unlock Ind'
UNION SELECT 'CPU','TURBO_5_CORE_FREQ_RTE','TURBO_5_CORE_FREQ_RTE','Turbo 5 Core Freq Rate'
UNION SELECT 'CPU','TURBO_6_CORE_FREQ_RTE','TURBO_6_CORE_FREQ_RTE','Turbo 6 Core Freq Rate'
UNION SELECT 'CPU','TURBO_7_CORE_FREQ_RTE','TURBO_7_CORE_FREQ_RTE','Turbo 7 Core Freq Rate'
UNION SELECT 'CPU','TURBO_8_CORE_FREQ_RTE','TURBO_8_CORE_FREQ_RTE','Turbo 8 Core Freq Rate'
UNION SELECT 'CPU','MAX_TARGET_SOCKET_CODE','MAX_TARGET_SOCKET_CODE','Max Target Socket Code'
UNION SELECT 'CPU','TURBO_2_CORE_FREQ_RTE','TURBO_2_CORE_FREQ_RTE','Turbo 2 Core Freq Rate'
UNION SELECT 'CPU','TURBO_3_CORE_FREQ_RTE','TURBO_3_CORE_FREQ_RTE','Turbo 3 Core Freq Rate'
UNION SELECT 'CPU','TURBO_4_CORE_FREQ_RTE','TURBO_4_CORE_FREQ_RTE','Turbo 4 Core Freq Rate'
UNION SELECT 'CPU','CPU_SPEED_LOW_FREQ_MODE','CPU_SPEED_LOW_FREQ_MODE','CPU in Low Freq Mode'
UNION SELECT 'CPU','CPU_SPEED_LOW_FREQ_MODE_UOM','CPU_SPEED_LOW_FREQ_MODE_UOM','CPU in Low Freq Mode UOM'
UNION SELECT 'CPU','INTEGRATED_GRAPHICS_FREQUENCY','INTEGRATED_GRAPHICS_FREQUENCY','Integrated Graphics Frequency'
UNION SELECT 'CPU','INTEGRATED_GRAPHICS_FREQ_UOM','INTEGRATED_GRAPHICS_FREQ_UOM','Integrated Graphics Freq UOM'
UNION SELECT 'CPU','INTG_GRAPHICS_TURBO_FREQ_UOM','INTG_GRAPHICS_TURBO_FREQ_UOM','Intg Graphics Turbo Freq UOM'
UNION SELECT 'CPU','INTEGRATED_GRAPHICS_TURBO_FREQ','INTEGRATED_GRAPHICS_TURBO_FREQ','Integrated Graphics Turbo Freq'
UNION SELECT 'CPU','FUNCTIONAL_MEMORY_CHANNELS','FUNCTIONAL_MEMORY_CHANNELS','Functional Memeory Channels'
UNION SELECT 'CPU','FINISHED_GOOD_TYPE','FINISHED_GOOD_TYPE','Finished Good Type'
UNION SELECT 'CPU','MEMORY_FREQUENCY_UOM','MEMORY_FREQUENCY_UOM','Memory Frequency UOM'
UNION SELECT 'CPU','LOWEST_CORE_SLEEP_STATE','LOWEST_CORE_SLEEP_STATE','Lowest Core Sleep State'
UNION SELECT 'CPU','GRAPHICS_LFM_FREQUENCY','GRAPHICS_LFM_FREQUENCY','Graphics LFM Frequency'
UNION SELECT 'CPU','GRAPHICS_TECH_FREQ_LFM_UOM','GRAPHICS_TECH_FREQ_LFM_UOM','Graphics Tech Frequency LFM UOM'
UNION SELECT 'CPU','GRAPHICS_TECH_FREQ_UNLOCK_IND','GRAPHICS_TECH_FREQ_UNLOCK_IND','Graphics Tech Freq Unlock Ind'
UNION SELECT 'CPU','TUNABLE_THERMAL_DESIGN_PWR_IND','TUNABLE_THERMAL_DESIGN_PWR_IND','Tunable Thermal Design Pwr Ind'
UNION SELECT 'CPU','MIN_THERMAL_DESIGN_POWER_RATE','MIN_THERMAL_DESIGN_POWER_RATE','Min Thermal Design Power Rate'
UNION SELECT 'CPU','MAX_THERMAL_DESIGN_POWER_RATE','MAX_THERMAL_DESIGN_POWER_RATE','Max Thermal Design Power Rate'
UNION SELECT 'CPU','MINIMUM_IA_FREQUENCY_RATE','MINIMUM_IA_FREQUENCY_RATE','Minimum IA Frequency Rate'
UNION SELECT 'CPU','MAXIMUM_IA_FREQUENCY_RATE','MAXIMUM_IA_FREQUENCY_RATE','Maximum IA Frequency Rate'
UNION SELECT 'CPU','PROTECTED_AUDIO_VIDEO_PATH','PROTECTED_AUDIO_VIDEO_PATH','Protected Audio Visual Path'
UNION SELECT 'CPU','HIGH_BNDWDT_DGTL_CONTENT_PRTCT','HIGH_BNDWDT_DGTL_CONTENT_PRTCT','High Bndwd Digital Content Prtct'
UNION SELECT 'CPU','ULT_SCAN_FOR_DC_OPEN_BOX','ULT_SCAN_FOR_DC_OPEN_BOX','ULT Scan for DC Open Box'
UNION SELECT 'CPU','FUNCTIONAL_EXECUTION_UNIT_QTY','FUNCTIONAL_EXECUTION_UNIT_QTY','Functional Execution Unit Qty'
UNION SELECT 'CPU','TRNS_SYNCH_EXTENSION_HLE_IND','TRNS_SYNCH_EXTENSION_HLE_IND','Trns Synch Extension HLE Ind'
UNION SELECT 'CPU','VIRTL_MCHN_CTRL_STRC_SHDW_IND','VIRTL_MCHN_CTRL_STRC_SHDW_IND','Virtl Mchn Ctrl Shdw Ind'
UNION SELECT 'CPU','CACHE_QOS_ENFORCEMENT_IND','CACHE_QOS_ENFORCEMENT_IND','Cache QOS Enforcement Ind'
UNION SELECT 'CPU','LOWEST_PACKAGE_CORE_STATE_CODE','LOWEST_PACKAGE_CORE_STATE_CODE','Lowest Package Core State'
UNION SELECT 'CPU','CPU_DIE_TJMAX_NUMBER','CPU_DIE_TJMAX_NUMBER','CPU Die TJMax Number'
UNION SELECT 'CPU','BOOT_GUARD_INDICATOR','BOOT_GUARD_INDICATOR','Boot Guard Indicator'
UNION SELECT 'CPU','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'CPU','INTEL_SOFTWARE_GUARD_EXTN_IND','INTEL_SOFTWARE_GUARD_EXTN_IND','Intel Software Guard Extn Ind'
UNION SELECT 'CPU','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'CPU','GFX_GT1_TURBO_FREQ_GHZ_RATE','GFX_GT1_TURBO_FREQ_GHZ_RATE','GFX GT1 Turbo Freq Rate'
UNION SELECT 'CPU','DYNAMIC_SKUING_INDICATOR','DYNAMIC_SKUING_INDICATOR','Dynamic Skuing Indicator'
UNION SELECT 'CPU','BASE_CLOCK_MAX_MHZ_RATE','BASE_CLOCK_MAX_MHZ_RATE','Base Clock Max MHz Rate'
UNION SELECT 'CPU','LOW_POWER_DDR5_FREQ_RATE','LOW_POWER_DDR5_FREQ_RATE','Low Power DDR5 Freq Rate'
UNION SELECT 'CPU','TOTAL_PHYSICAL_SMALL_CORE_QTY','TOTAL_PHYSICAL_SMALL_CORE_QTY','Physical Small Core Qty'
UNION SELECT 'CPU','FUNCTIONAL_BIG_CORE_COUNT','FUNCTIONAL_BIG_CORE_COUNT','Functional Big Core'
UNION SELECT 'CPU','FUNCTIONAL_SMALL_CORE','FUNCTIONAL_SMALL_CORE','Functional Small Core'
UNION SELECT 'CPU','TOTAL_PHYSICAL_BIG_CORE_QTY','TOTAL_PHYSICAL_BIG_CORE_QTY','Physical Big Core Qty'
UNION SELECT 'CPU','SMALL_CORE_MAX_TURBO_FREQ_RATE','SMALL_CORE_MAX_TURBO_FREQ_RATE','Small Core Max Turbo Freq Rate'
UNION SELECT 'CPU','TURBO_2_SMALL_CORE_FREQ_RATE','TURBO_2_SMALL_CORE_FREQ_RATE','Turbo 2 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_3_SMALL_CORE_FREQ_RATE','TURBO_3_SMALL_CORE_FREQ_RATE','Turbo 3 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_4_SMALL_CORE_FREQ_RATE','TURBO_4_SMALL_CORE_FREQ_RATE','Turbo 4 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_5_SMALL_CORE_FREQ_RATE','TURBO_5_SMALL_CORE_FREQ_RATE','Turbo 5 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_6_SMALL_CORE_FREQ_RATE','TURBO_6_SMALL_CORE_FREQ_RATE','Turbo 6 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_7_SMALL_CORE_FREQ_RATE','TURBO_7_SMALL_CORE_FREQ_RATE','Turbo 7 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_8_SMALL_CORE_FREQ_RATE','TURBO_8_SMALL_CORE_FREQ_RATE','Turbo 8 Small Core Freq Rate'
UNION SELECT 'CPU','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'CPU','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'CPU','FINSHED_GOOD_CATEGORY_TYPE','FINSHED_GOOD_CATEGORY_TYPE','Finished Good Category Type'
UNION SELECT 'CPU','MEMORY_ECC_SUPPORT_IND','MEMORY_ECC_SUPPORT_IND','Memory ECC Support Indicator'
UNION SELECT 'CPU','SMALL_CORE_SPEED','SMALL_CORE_SPEED','Small Core Speed'
UNION SELECT 'CPU','TURBO_9_SMALL_CORE_FREQ_RATE','TURBO_9_SMALL_CORE_FREQ_RATE','Turbo 9 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_10_SMALL_CORE_FREQ_RATE','TURBO_10_SMALL_CORE_FREQ_RATE','Turbo 10 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_11_SMALL_CORE_FREQ_RATE','TURBO_11_SMALL_CORE_FREQ_RATE','Turbo 11 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_12_SMALL_CORE_FREQ_RATE','TURBO_12_SMALL_CORE_FREQ_RATE','Turbo 12 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_13_SMALL_CORE_FREQ_RATE','TURBO_13_SMALL_CORE_FREQ_RATE','Turbo 13 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_14_SMALL_CORE_FREQ_RATE','TURBO_14_SMALL_CORE_FREQ_RATE','Turbo 14 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_15_SMALL_CORE_FREQ_RATE','TURBO_15_SMALL_CORE_FREQ_RATE','Turbo 15 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_16_SMALL_CORE_FREQ_RATE','TURBO_16_SMALL_CORE_FREQ_RATE','Turbo 16 Small Core Freq Rate'
UNION SELECT 'CPU','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'CPU','MEMORY1_CAPACITY_UOM','MEMORY1_CAPACITY_UOM','Memory  1 Capacity Uom'
UNION SELECT 'CPU','MEMORY2_CAPACITY_UOM','MEMORY2_CAPACITY_UOM','Memory 2  Capacity Uom'
UNION SELECT 'CPU','MEMORY1_DATA_RATE_UOM','MEMORY1_DATA_RATE_UOM','Memory1  Data Rate UOM'
UNION SELECT 'CPU','MEMORY2_DATA_RATE_UOM','MEMORY2_DATA_RATE_UOM','Memory2  Data Rate UOM'
UNION SELECT 'CPU','MEMORY1_CHANNEL_CONFIG','MEMORY1_CHANNEL_CONFIG','Memory1  Channel Config'
UNION SELECT 'CPU','MEMORY2_CHANNEL_CONFIG','MEMORY2_CHANNEL_CONFIG','Memory2  Channel Config'
UNION SELECT 'CPU','MEMORY1_ECC_SUPPORT_IND','MEMORY1_ECC_SUPPORT_IND','Memory1  ECC Support Ind'
UNION SELECT 'CPU','MEMORY2_ECC_SUPPORT_IND','MEMORY2_ECC_SUPPORT_IND','Memory2  ECC Support Ind'
UNION SELECT 'CPU','MEMORY1_INBAND_ECC_IND','MEMORY1_INBAND_ECC_IND','Memory1  Inband ECC Ind'
UNION SELECT 'CPU','MEMORY2_INBAND_ECC_IND','MEMORY2_INBAND_ECC_IND','Memory2  Inband ECC Ind'
UNION SELECT 'CPU','MEMORY1_SUPPLIER','MEMORY1_SUPPLIER','Memory1  Supplier'
UNION SELECT 'CPU','MEMORY1_TECHNOLOGY','MEMORY1_TECHNOLOGY','Memory1  Technology'
UNION SELECT 'CPU','MEMORY2_SUPPLIER','MEMORY2_SUPPLIER','Memory2  Supplier'
UNION SELECT 'CPU','MEMORY2_TECHNOLOGY','MEMORY2_TECHNOLOGY','Memory2  Technology'
UNION SELECT 'CPU','MEMORY1_CATEGORY_TYPE','MEMORY1_CATEGORY_TYPE','Memory1  Category Type'
UNION SELECT 'CPU','MEMORY2_CATEGORY_TYPE','MEMORY2_CATEGORY_TYPE','Memory2  Category Type'
UNION SELECT 'CPU','MEMORY1_CAPACITY','MEMORY1_CAPACITY','Memory1  Capacity'
UNION SELECT 'CPU','MEMORY2_CAPACITY','MEMORY2_CAPACITY','Memory2  Capacity'
UNION SELECT 'CPU','MEMORY1_DATA_RATE','MEMORY1_DATA_RATE','Memory1  Data Rate'
UNION SELECT 'CPU','MEMORY1_FUNCT_CHANNELS','MEMORY1_FUNCT_CHANNELS','Memory1  Funct Channels'
UNION SELECT 'CPU','MEMORY2_DATA_RATE','MEMORY2_DATA_RATE','Memory2  Data Rate'
UNION SELECT 'CPU','MEMORY1_MODULES_PER_CHANNEL','MEMORY1_MODULES_PER_CHANNEL','Memory1  Modules Per Channel'
UNION SELECT 'CPU','MEMORY2_FUNCT_CHANNELS','MEMORY2_FUNCT_CHANNELS','Memory2  Funct Channels'
UNION SELECT 'CPU','MEMORY2_MODULES_PER_CHANNEL','MEMORY2_MODULES_PER_CHANNEL','Memory2  Modules Per Channel'
UNION SELECT 'CPU','GFX_TURBO_FREQ_UOM','GFX_TURBO_FREQ_UOM','GFX Turbo Freq UOM'
UNION SELECT 'CPU','MAX_IA_FREQ_UOM','MAX_IA_FREQ_UOM','Max IA Freq UOM'
UNION SELECT 'CPU','MINIMUM_IA_FREQUENCY_UOM','MINIMUM_IA_FREQUENCY_UOM','Minimum IA Frequency UOM'
UNION SELECT 'CPU','TURBO_CORE_FREQ_UOM','TURBO_CORE_FREQ_UOM','Turbo Core Freq UOM'
UNION SELECT 'CPU','TURBO_SMALL_CORE_FREQ_UOM','TURBO_SMALL_CORE_FREQ_UOM','Turbo Small Core Freq UOM'
UNION SELECT 'CPU','TURBO_17_SMALL_CORE_FREQ_RATE','TURBO_17_SMALL_CORE_FREQ_RATE','Turbo 17 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_18_SMALL_CORE_FREQ_RATE','TURBO_18_SMALL_CORE_FREQ_RATE','Turbo 18 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_19_SMALL_CORE_FREQ_RATE','TURBO_19_SMALL_CORE_FREQ_RATE','Turbo 19 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_20_SMALL_CORE_FREQ_RATE','TURBO_20_SMALL_CORE_FREQ_RATE','Turbo 20 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_21_SMALL_CORE_FREQ_RATE','TURBO_21_SMALL_CORE_FREQ_RATE','Turbo 21 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_23_SMALL_CORE_FREQ_RATE','TURBO_23_SMALL_CORE_FREQ_RATE','Turbo 23 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_24_SMALL_CORE_FREQ_RATE','TURBO_24_SMALL_CORE_FREQ_RATE','Turbo 24 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_25_SMALL_CORE_FREQ_RATE','TURBO_25_SMALL_CORE_FREQ_RATE','Turbo 25 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_26_SMALL_CORE_FREQ_RATE','TURBO_26_SMALL_CORE_FREQ_RATE','Turbo 26 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_27_SMALL_CORE_FREQ_RATE','TURBO_27_SMALL_CORE_FREQ_RATE','Turbo 27 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_28_SMALL_CORE_FREQ_RATE','TURBO_28_SMALL_CORE_FREQ_RATE','Turbo 28 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_29_SMALL_CORE_FREQ_RATE','TURBO_29_SMALL_CORE_FREQ_RATE','Turbo 29 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_30_SMALL_CORE_FREQ_RATE','TURBO_30_SMALL_CORE_FREQ_RATE','Turbo 30 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_31_SMALL_CORE_FREQ_RATE','TURBO_31_SMALL_CORE_FREQ_RATE','Turbo 31 Small Core Freq Rate'
UNION SELECT 'CPU','TURBO_32_SMALL_CORE_FREQ_RATE','TURBO_32_SMALL_CORE_FREQ_RATE','Turbo 32 Small Core Freq Rate'
UNION SELECT 'CPU','MEMORY_SUPPLIER','MEMORY_SUPPLIER','Memory Supplier'
UNION SELECT 'CPU','MULTIPLE_MARK_NAME','MULTIPLE_MARK_NAME','Multiple Mark Name'
UNION SELECT 'CPU','MEMORY1_RANK','MEMORY1_RANK','Memory1  Rank'
UNION SELECT 'CPU','MEMORY2_RANK','MEMORY2_RANK','Memory2  Rank'
UNION SELECT 'CPU','TURBO_22_SMALL_CORE_FREQ_RATE','TURBO_22_SMALL_CORE_FREQ_RATE','Turbo 22 Small Core Freq Rate'
UNION SELECT 'CPU','PHYSICAL_LP_ECORE_PROCESSOR_QTY','PHYSICAL_LP_ECORE_PROCESSOR_QTY','Physical LP Ecore Prcsr Qty'
UNION SELECT 'CPU','FUNCTIONAL_LP_ECORE_PRCSR_QTY','FUNCTIONAL_LP_ECORE_PRCSR_QTY','Functional LP Ecore Prcsr Qty'
UNION SELECT 'CPU','TRADE_PACKAGE_TYPE','TRADE_PACKAGE_TYPE','Die Footprint for Trade'
UNION SELECT 'DEVICE_CARRY_CASE','CASE_OUTER_SHELL_WOVEN_IND','CASE_OUTER_SHELL_WOVEN_IND','CASE INSIDE SHELL WOVEN IND'
UNION SELECT 'GPU','SPEED_UOM','SPEED_UOM','Speed UOM'
UNION SELECT 'GPU','EXTERNAL_REVISION','EXTERNAL_REVISION','External Revision'
UNION SELECT 'GPU','TRANSISTOR_FAB_PROCESS_TECH','TRANSISTOR_FAB_PROCESS_TECH','Transistor Fab Process Tech'
UNION SELECT 'GPU','MARKETING_PACKAGE_DESIGNATOR','MARKETING_PACKAGE_DESIGNATOR','Marketing Package Designator'
UNION SELECT 'GPU','TRADEMARK_NAME','TRADEMARK_NAME','Trademark Name'
UNION SELECT 'GPU','PACKAGE_SHORT_TEXT','PACKAGE_SHORT_TEXT','Package Short Text'
UNION SELECT 'GPU','TOTAL_CACHE_QTY','TOTAL_CACHE_QTY','Total Cache Qty'
UNION SELECT 'GPU','TOTAL_CACHE_QTY_UOM','TOTAL_CACHE_QTY_UOM','Total Cache Qty Uom Code'
UNION SELECT 'GPU','CPU_SLOT_TYPE','CPU_SLOT_TYPE','CPU Slot Type'
UNION SELECT 'GPU','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'GPU','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'GPU','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'GPU','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'GPU','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'GPU','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'GPU','EXTERNAL_STEPPING','EXTERNAL_STEPPING','External Stepping'
UNION SELECT 'GPU','THERMAL_DESIGN_POWER_UOM','THERMAL_DESIGN_POWER_UOM','Thermal Design Power UOM'
UNION SELECT 'GPU','MEMORY_CAPACITY','MEMORY_CAPACITY','Memory Capacity'
UNION SELECT 'GPU','MEMORY_CAPACITY_UOM','MEMORY_CAPACITY_UOM','Memory Capacity UOM'
UNION SELECT 'GPU','ERROR_CORRECTION_CODE_IND','ERROR_CORRECTION_CODE_IND','Error Correction Code Ind'
UNION SELECT 'GPU','MAX_END_USER_OVERCLOCK_FREQ','MAX_END_USER_OVERCLOCK_FREQ','Max End User Overclock Freq'
UNION SELECT 'GPU','EXTERNAL_GRAPHICS_SUPPORT_IND','EXTERNAL_GRAPHICS_SUPPORT_IND','External Graphics Suppt Ind'
UNION SELECT 'GPU','FUNCTIONAL_MEMORY_CHANNELS','FUNCTIONAL_MEMORY_CHANNELS','Functional Memeory Channels'
UNION SELECT 'GPU','FINISHED_GOOD_TYPE','FINISHED_GOOD_TYPE','Finished Good Type'
UNION SELECT 'GPU','ULT_SCAN_FOR_DC_OPEN_BOX','ULT_SCAN_FOR_DC_OPEN_BOX','ULT Scan for DC Open Box'
UNION SELECT 'GPU','FUNCTIONAL_EXECUTION_UNIT_QTY','FUNCTIONAL_EXECUTION_UNIT_QTY','Functional Execution Unit Qty'
UNION SELECT 'GPU','PHYS_GFX_EXECUTION_UNIT_QTY','PHYS_GFX_EXECUTION_UNIT_QTY','Physical GFX Execution Unit Qty'
UNION SELECT 'GPU','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'GPU','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'GPU','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'GPU','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'GPU','FINSHED_GOOD_CATEGORY_TYPE','FINSHED_GOOD_CATEGORY_TYPE','Finished Good Category Type'
UNION SELECT 'GPU','MEMORY_ECC_SUPPORT_IND','MEMORY_ECC_SUPPORT_IND','Memory ECC Support Indicator'
UNION SELECT 'GPU','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'GPU','MEMORY1_CAPACITY_UOM','MEMORY1_CAPACITY_UOM','Memory  1 Capacity Uom'
UNION SELECT 'GPU','MEMORY2_CAPACITY_UOM','MEMORY2_CAPACITY_UOM','Memory 2  Capacity Uom'
UNION SELECT 'GPU','MEMORY1_DATA_RATE_UOM','MEMORY1_DATA_RATE_UOM','Memory1  Data Rate UOM'
UNION SELECT 'GPU','MEMORY2_DATA_RATE_UOM','MEMORY2_DATA_RATE_UOM','Memory2  Data Rate UOM'
UNION SELECT 'GPU','MEMORY1_CHANNEL_CONFIG','MEMORY1_CHANNEL_CONFIG','Memory1  Channel Config'
UNION SELECT 'GPU','MEMORY2_CHANNEL_CONFIG','MEMORY2_CHANNEL_CONFIG','Memory2  Channel Config'
UNION SELECT 'GPU','MEMORY1_ECC_SUPPORT_IND','MEMORY1_ECC_SUPPORT_IND','Memory1  ECC Support Ind'
UNION SELECT 'GPU','MEMORY2_ECC_SUPPORT_IND','MEMORY2_ECC_SUPPORT_IND','Memory2  ECC Support Ind'
UNION SELECT 'GPU','MEMORY1_INBAND_ECC_IND','MEMORY1_INBAND_ECC_IND','Memory1  Inband ECC Ind'
UNION SELECT 'GPU','MEMORY2_INBAND_ECC_IND','MEMORY2_INBAND_ECC_IND','Memory2  Inband ECC Ind'
UNION SELECT 'GPU','MEMORY1_SUPPLIER','MEMORY1_SUPPLIER','Memory1  Supplier'
UNION SELECT 'GPU','MEMORY1_TECHNOLOGY','MEMORY1_TECHNOLOGY','Memory1  Technology'
UNION SELECT 'GPU','MEMORY2_SUPPLIER','MEMORY2_SUPPLIER','Memory2  Supplier'
UNION SELECT 'GPU','MEMORY2_TECHNOLOGY','MEMORY2_TECHNOLOGY','Memory2  Technology'
UNION SELECT 'GPU','MEMORY1_CATEGORY_TYPE','MEMORY1_CATEGORY_TYPE','Memory1  Category Type'
UNION SELECT 'GPU','MEMORY2_CATEGORY_TYPE','MEMORY2_CATEGORY_TYPE','Memory2  Category Type'
UNION SELECT 'GPU','MEMORY1_CAPACITY','MEMORY1_CAPACITY','Memory1  Capacity'
UNION SELECT 'GPU','MEMORY2_CAPACITY','MEMORY2_CAPACITY','Memory2  Capacity'
UNION SELECT 'GPU','MEMORY1_DATA_RATE','MEMORY1_DATA_RATE','Memory1  Data Rate'
UNION SELECT 'GPU','MEMORY1_FUNCT_CHANNELS','MEMORY1_FUNCT_CHANNELS','Memory1  Funct Channels'
UNION SELECT 'GPU','MEMORY2_DATA_RATE','MEMORY2_DATA_RATE','Memory2  Data Rate'
UNION SELECT 'GPU','MEMORY1_MODULES_PER_CHANNEL','MEMORY1_MODULES_PER_CHANNEL','Memory1  Modules Per Channel'
UNION SELECT 'GPU','MEMORY2_FUNCT_CHANNELS','MEMORY2_FUNCT_CHANNELS','Memory2  Funct Channels'
UNION SELECT 'GPU','MEMORY2_MODULES_PER_CHANNEL','MEMORY2_MODULES_PER_CHANNEL','Memory2  Modules Per Channel'
UNION SELECT 'GPU','MEMORY_SUPPLIER','MEMORY_SUPPLIER','Memory Supplier'
UNION SELECT 'GPU','MULTIPLE_MARK_NAME','MULTIPLE_MARK_NAME','Multiple Mark Name'
UNION SELECT 'GPU','TARGETED_GRAPHICS_POWER','TARGETED_GRAPHICS_POWER','Targeted Graphics Power'
UNION SELECT 'GPU','TARGETED_GRAPHICS_POWER_UOM','TARGETED_GRAPHICS_POWER_UOM','Targeted Graphics Power UOM'
UNION SELECT 'GPU','INTERNAL_PLANNING_DESCRIPTOR','INTERNAL_PLANNING_DESCRIPTOR','Internal Planning Descriptor'
UNION SELECT 'GPU','GPU_DIE_TJMAX_NUMBER','GPU_DIE_TJMAX_NUMBER','GPU Die TJMax Number'
UNION SELECT 'GPU','TRADE_PACKAGE_TYPE','TRADE_PACKAGE_TYPE','Die Footprint for Trade'
UNION SELECT 'MAT','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'MAT','MARKET_CODE_NAME','MARKET_CODE_NAME','Branded Product Indicator'
UNION SELECT 'MEMORY_FG','SPEED_UOM','SPEED_UOM','Speed UOM'
UNION SELECT 'MEMORY_FG','EXTERNAL_REVISION','EXTERNAL_REVISION','External Revision'
UNION SELECT 'MEMORY_FG','TRANSISTOR_FAB_PROCESS_TECH','TRANSISTOR_FAB_PROCESS_TECH','Transistor Fab Process Tech'
UNION SELECT 'MEMORY_FG','MARKETING_PACKAGE_DESIGNATOR','MARKETING_PACKAGE_DESIGNATOR','Marketing Package Designator'
UNION SELECT 'MEMORY_FG','TRADEMARK_NAME','TRADEMARK_NAME','Trademark Name'
UNION SELECT 'MEMORY_FG','PACKAGE_SHORT_TEXT','PACKAGE_SHORT_TEXT','Package Short Text'
UNION SELECT 'MEMORY_FG','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'MEMORY_FG','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'MEMORY_FG','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'MEMORY_FG','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'MEMORY_FG','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'MEMORY_FG','EXTERNAL_STEPPING','EXTERNAL_STEPPING','External Stepping'
UNION SELECT 'MEMORY_FG','MEMORY_CAPACITY','MEMORY_CAPACITY','Memory Capacity'
UNION SELECT 'MEMORY_FG','MEMORY_CAPACITY_UOM','MEMORY_CAPACITY_UOM','Memory Capacity UOM'
UNION SELECT 'MEMORY_FG','FINISHED_GOOD_TYPE','FINISHED_GOOD_TYPE','Finished Good Type'
UNION SELECT 'MEMORY_FG','MEMORY_FREQUENCY_UOM','MEMORY_FREQUENCY_UOM','Memory Frequency UOM'
UNION SELECT 'MEMORY_FG','ULT_SCAN_FOR_DC_OPEN_BOX','ULT_SCAN_FOR_DC_OPEN_BOX','ULT Scan for DC Open Box'
UNION SELECT 'MEMORY_FG','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'MEMORY_FG','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'MEMORY_FG','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'MEMORY_FG','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'MEMORY_FG','FINSHED_GOOD_CATEGORY_TYPE','FINSHED_GOOD_CATEGORY_TYPE','Finished Good Category Type'
UNION SELECT 'MEMORY_FG','MEMORY_ECC_SUPPORT_IND','MEMORY_ECC_SUPPORT_IND','Memory ECC Support Indicator'
UNION SELECT 'MEMORY_FG','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'MEMORY_FG','MEMORY1_CAPACITY_UOM','MEMORY1_CAPACITY_UOM','Memory  1 Capacity Uom'
UNION SELECT 'MEMORY_FG','MEMORY1_DATA_RATE_UOM','MEMORY1_DATA_RATE_UOM','Memory1  Data Rate UOM'
UNION SELECT 'MEMORY_FG','MEMORY1_ECC_SUPPORT_IND','MEMORY1_ECC_SUPPORT_IND','Memory1  ECC Support Ind'
UNION SELECT 'MEMORY_FG','MEMORY1_INBAND_ECC_IND','MEMORY1_INBAND_ECC_IND','Memory1  Inband ECC Ind'
UNION SELECT 'MEMORY_FG','MEMORY1_SUPPLIER','MEMORY1_SUPPLIER','Memory1  Supplier'
UNION SELECT 'MEMORY_FG','MEMORY1_CAPACITY','MEMORY1_CAPACITY','Memory1  Capacity'
UNION SELECT 'MEMORY_FG','MEMORY1_DATA_RATE','MEMORY1_DATA_RATE','Memory1  Data Rate'
UNION SELECT 'MEMORY_FG','MEMORY_SUPPLIER','MEMORY_SUPPLIER','Memory Supplier'
UNION SELECT 'MEMORY_FG','MULTIPLE_MARK_NAME','MULTIPLE_MARK_NAME','Multiple Mark Name'
UNION SELECT 'MEMORY_FG','INTERNAL_PLANNING_DESCRIPTOR','INTERNAL_PLANNING_DESCRIPTOR','Internal Planning Descriptor'
UNION SELECT 'MEMORY_FG','TRADE_PACKAGE_TYPE','TRADE_PACKAGE_TYPE','Die Footprint for Trade'
UNION SELECT 'P_ASSEMBLY','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'P_ASSEMBLY','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_ASSEMBLY','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_ASSEMBLY','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'P_ASSEMBLY','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'P_ASSEMBLY','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'P_ASSEMBLY','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'P_ASSEMBLY','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'P_ASSEMBLY','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'P_ASSEMBLY','MFG_PKG_CODE','MFG_PKG_CODE','Manufacturing Package Code'
UNION SELECT 'P_ASSEMBLY','PINCOUNT','PINCOUNT','Pincount'
UNION SELECT 'P_ASSEMBLY','TOTAL_FUNCTIONAL_CORE_COUNT','TOTAL_FUNCTIONAL_CORE_COUNT','Total Functional Core Count'
UNION SELECT 'P_ASSEMBLY','PHYSICAL_DIE_PER_PKG_QTY','PHYSICAL_DIE_PER_PKG_QTY','Physical Die Per Pkg'
UNION SELECT 'P_ASSEMBLY','FUNCTIONAL_DIE_PER_PACKAGE','FUNCTIONAL_DIE_PER_PACKAGE','Functional Die Per Package'
UNION SELECT 'P_ASSEMBLY','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core Qty'
UNION SELECT 'P_ASSEMBLY','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'P_ASSEMBLY','FOLLOW_ON_GENERATION_NUMBER','FOLLOW_ON_GENERATION_NUMBER','Variant Iteration Number'
UNION SELECT 'P_ASSEMBLY','STRATEGIC_ROADMAP_SEGMENT_CODE','STRATEGIC_ROADMAP_SEGMENT_CODE','Strategic Roadmap Segment Code'
UNION SELECT 'P_ASSEMBLY','ASSEMBLY_FULL_TOPSIDE_MARK_ID','ASSEMBLY_FULL_TOPSIDE_MARK_ID','Assembly Full Topside Mark ID'
UNION SELECT 'P_ASSEMBLY','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'P_ASSEMBLY','NUMBER_COLUMNS_PER_STRIP_QTY','NUMBER_COLUMNS_PER_STRIP_QTY','NUMBER_COLUMNS_PER_STRIP_QTY'
UNION SELECT 'P_ASSEMBLY','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_ASSEMBLY','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'P_ASSEMBLY','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_ASSEMBLY','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'P_ASSEMBLY','MAX_FPO_MARK_LOT_NBRS_ALLOWED','MAX_FPO_MARK_LOT_NBRS_ALLOWED','Max FPO Mark Lot Nbrs Allowed'
UNION SELECT 'P_ASSEMBLY','MAX_NUMBER_OF_LOT_SEAL_DATES','MAX_NUMBER_OF_LOT_SEAL_DATES','Max Number of Lot Seal Dates'
UNION SELECT 'P_ASSEMBLY','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'P_ASSEMBLY','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'P_ASSEMBLY','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'P_ASSEMBLY','MEMORY1_CAPACITY_UOM','MEMORY1_CAPACITY_UOM','Memory  1 Capacity Uom'
UNION SELECT 'P_ASSEMBLY','MEMORY1_CAPACITY','MEMORY1_CAPACITY','Memory1  Capacity'
UNION SELECT 'P_ASSEMBLY','INDIVIDUAL_MEMORY_CAPACITY','INDIVIDUAL_MEMORY_CAPACITY','Individual Memory Capacity'
UNION SELECT 'P_BUMP','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'P_BUMP','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_BUMP','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_BUMP','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'P_BUMP','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'P_BUMP','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'P_BUMP','FOLLOW_ON_GENERATION_NUMBER','FOLLOW_ON_GENERATION_NUMBER','Variant Iteration Number'
UNION SELECT 'P_BUMP','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'P_BUMP','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_BUMP','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_BUMP','DIE_SINGULATION_INDICATOR','DIE_SINGULATION_INDICATOR','Die Singulation Indicator'
UNION SELECT 'P_BUMP','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'P_BUMP','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_BUMP','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'P_BUMP','EXTERNAL_TO_DIEPREP_INDICATOR','EXTERNAL_TO_DIEPREP_INDICATOR','External to DiePrep Indicator'
UNION SELECT 'P_BUMP','UNSORTED_EXTERNAL_SILICON_IND','UNSORTED_EXTERNAL_SILICON_IND','Unsorted External Silicon Ind'
UNION SELECT 'P_DIE_PREP','TOTAL_CACHE_QTY','TOTAL_CACHE_QTY','Total Cache Qty'
UNION SELECT 'P_DIE_PREP','TOTAL_CACHE_QTY_UOM','TOTAL_CACHE_QTY_UOM','Total Cache Qty Uom Code'
UNION SELECT 'P_DIE_PREP','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'P_DIE_PREP','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_DIE_PREP','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'P_DIE_PREP','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'P_DIE_PREP','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'P_DIE_PREP','DIE_SIZE_LENGTH_Y','DIE_SIZE_LENGTH_Y','Die Size Length Y'
UNION SELECT 'P_DIE_PREP','DIE_SIZE_LENGTH_UOM','DIE_SIZE_LENGTH_UOM','Die Size Length UOM'
UNION SELECT 'P_DIE_PREP','DIE_SIZE_WIDTH_UOM','DIE_SIZE_WIDTH_UOM','Die Size Width UOM'
UNION SELECT 'P_DIE_PREP','DIE_SIZE_WIDTH_X','DIE_SIZE_WIDTH_X','Die Size Width X'
UNION SELECT 'P_DIE_PREP','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core Qty'
UNION SELECT 'P_DIE_PREP','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'P_DIE_PREP','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'P_DIE_PREP','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'P_DIE_PREP','DIE_SIZE_THICKNESS','DIE_SIZE_THICKNESS','Die Size Thickness'
UNION SELECT 'P_DIE_PREP','DIE_SIZE_THICKNESS_UOM','DIE_SIZE_THICKNESS_UOM','Die Size Thickness UOM'
UNION SELECT 'P_DIE_PREP','PHYS_GFX_EXECUTION_UNIT_QTY','PHYS_GFX_EXECUTION_UNIT_QTY','Physical GFX Execution Unit Qty'
UNION SELECT 'P_DIE_PREP','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_DIE_PREP','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_DIE_PREP','DIE_SINGULATION_INDICATOR','DIE_SINGULATION_INDICATOR','Die Singulation Indicator'
UNION SELECT 'P_DIE_PREP','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'P_DIE_PREP','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_DIE_PREP','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'P_FAB','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'P_FAB','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_FAB','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'P_FAB','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'P_FAB','SUB_CODE_NAME','SUB_CODE_NAME','Sub Code Name'
UNION SELECT 'P_FAB','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'P_FAB','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'P_FAB','FOLLOW_ON_GENERATION_NUMBER','FOLLOW_ON_GENERATION_NUMBER','Variant Iteration Number'
UNION SELECT 'P_FAB','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP Estimate Physical Core Qty'
UNION SELECT 'P_FAB','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP Est Phys Graphics Core Qty'
UNION SELECT 'P_FAB','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_FAB','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_FAB','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'P_FAB','MULTIPLE_WAFER_THINNING_IND','MULTIPLE_WAFER_THINNING_IND','Multiple Wafer Thinning Ind'
UNION SELECT 'P_FAB','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_FAB','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'P_FAB','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Graphics Phys Execution Qty'
UNION SELECT 'P_FAB','EXTERNAL_TO_DIEPREP_INDICATOR','EXTERNAL_TO_DIEPREP_INDICATOR','External to DiePrep Indicator'
UNION SELECT 'P_FAB','UNSORTED_EXTERNAL_SILICON_IND','UNSORTED_EXTERNAL_SILICON_IND','Unsorted External Silicon Ind'
UNION SELECT 'P_FAB','MULTI_PRODUCT_WAFER_INDICATOR','MULTI_PRODUCT_WAFER_INDICATOR','Multiple Product Wfr Ind'
UNION SELECT 'P_SORT','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'P_SORT','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_SORT','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_SORT','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'P_SORT','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'P_SORT','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'P_SORT','DIE_SIZE_LENGTH_Y','DIE_SIZE_LENGTH_Y','Die Size Length Y'
UNION SELECT 'P_SORT','DIE_SIZE_LENGTH_UOM','DIE_SIZE_LENGTH_UOM','Die Size Length UOM'
UNION SELECT 'P_SORT','DIE_SIZE_WIDTH_UOM','DIE_SIZE_WIDTH_UOM','Die Size Width UOM'
UNION SELECT 'P_SORT','DIE_SIZE_WIDTH_X','DIE_SIZE_WIDTH_X','Die Size Width X'
UNION SELECT 'P_SORT','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core Qty'
UNION SELECT 'P_SORT','MEMORY_CAPACITY','MEMORY_CAPACITY','Memory Capacity'
UNION SELECT 'P_SORT','MEMORY_CAPACITY_UOM','MEMORY_CAPACITY_UOM','Memory Capacity UOM'
UNION SELECT 'P_SORT','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'P_SORT','ESTIMATED_DIE_SIZE_AREA_MM2','ESTIMATED_DIE_SIZE_AREA_MM2','Estimated Die Size Area MM2'
UNION SELECT 'P_SORT','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'P_SORT','DIE_SIZE_THICKNESS','DIE_SIZE_THICKNESS','Die Size Thickness'
UNION SELECT 'P_SORT','DIE_SIZE_THICKNESS_UOM','DIE_SIZE_THICKNESS_UOM','Die Size Thickness UOM'
UNION SELECT 'P_SORT','MEMORY_TYPE_NAME','MEMORY_TYPE_NAME','Memory Type Name'
UNION SELECT 'P_SORT','PHYS_GFX_EXECUTION_UNIT_QTY','PHYS_GFX_EXECUTION_UNIT_QTY','Physical GFX Execution Unit Qty'
UNION SELECT 'P_SORT','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_SORT','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_SORT','DIE_SINGULATION_INDICATOR','DIE_SINGULATION_INDICATOR','Die Singulation Indicator'
UNION SELECT 'P_SORT','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'P_SORT','WAFER_THICKNESS_DIMENSION','WAFER_THICKNESS_DIMENSION','Wafer Thickness Dimension'
UNION SELECT 'P_SORT','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_SORT','EXTERNAL_TO_DIEPREP_INDICATOR','EXTERNAL_TO_DIEPREP_INDICATOR','External to DiePrep Indicator'
UNION SELECT 'P_SORT','UNSORTED_EXTERNAL_SILICON_IND','UNSORTED_EXTERNAL_SILICON_IND','Unsorted External Silicon Ind'
UNION SELECT 'P_SORT','MEMORY1_CAPACITY_UOM','MEMORY1_CAPACITY_UOM','Memory  1 Capacity Uom'
UNION SELECT 'P_SORT','MEMORY1_CAPACITY','MEMORY1_CAPACITY','Memory1  Capacity'
UNION SELECT 'P_SORT','PHYSICAL_LP_ECORE_PROCESSOR_QTY','PHYSICAL_LP_ECORE_PROCESSOR_QTY','Physical LP Ecore Prcsr Qty'
UNION SELECT 'P_SORT','PHYSICAL_ECORE_PROCESSOR_QTY','PHYSICAL_ECORE_PROCESSOR_QTY','Physical Ecore Processor Qty'
UNION SELECT 'P_SORT','PHYSICAL_P_CORE_PROCESSOR_QTY','PHYSICAL_P_CORE_PROCESSOR_QTY','Physical P Core Processor Qty'
UNION SELECT 'P_SORT','PHYSICAL_S_ECORE_PROCESSOR_QTY','PHYSICAL_S_ECORE_PROCESSOR_QTY','Physical S ECore Processor Qty'
UNION SELECT 'P_SORT','INTERNAL_FLOW_START_INDICATOR','INTERNAL_FLOW_START_INDICATOR','Internal Flow Start Indicator'
UNION SELECT 'P_STACK_COMBO','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'P_STACK_COMBO','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_STACK_COMBO','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'P_STACK_COMBO','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'P_STACK_COMBO','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'P_STACK_COMBO','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'P_STACK_COMBO','FOLLOW_ON_GENERATION_NUMBER','FOLLOW_ON_GENERATION_NUMBER','Variant Iteration Number'
UNION SELECT 'P_STACK_COMBO','ESTIMATED_DIE_SIZE_AREA_MM2','ESTIMATED_DIE_SIZE_AREA_MM2','Estimated Die Size Area MM2'
UNION SELECT 'P_STACK_COMBO','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP_ESTIMATE_PHYSICAL_CORE_QTY','LRP Estimate Physical Core Qty'
UNION SELECT 'P_STACK_COMBO','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP_EST_PHYS_GRAPHICS_CORE_QTY','LRP Est Phys Graphics Core Qty'
UNION SELECT 'P_STACK_COMBO','PHYS_GFX_EXECUTION_UNIT_QTY','PHYS_GFX_EXECUTION_UNIT_QTY','Physical GFX Execution Unit Qty'
UNION SELECT 'P_STACK_COMBO','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_STACK_COMBO','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_STACK_COMBO','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'P_STACK_COMBO','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_STACK_COMBO','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'P_STACK_COMBO','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'P_STACK_COMBO','METROLOGY_TYPE','METROLOGY_TYPE','Metrology Type'
UNION SELECT 'P_STACK_COMBO','SOLDER_ON_DIE_INDICATOR','SOLDER_ON_DIE_INDICATOR','Solder On Die Indicator'
UNION SELECT 'P_STACK_COMBO','STACK_HEIGHT','STACK_HEIGHT','Stack Height'
UNION SELECT 'P_STACK_COMBO','TOP_DIE_THICKNESS_AT_TCW_UM','TOP_DIE_THICKNESS_AT_TCW_UM','Top Die Thickness At Tcw Um'
UNION SELECT 'P_STACK_COMBO','SOLDER_HEIGHT_TARGET_UM','SOLDER_HEIGHT_TARGET_UM','Solder Height Target Um'
UNION SELECT 'P_STACK_SILICON','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'P_STACK_SILICON','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_STACK_SILICON','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_STACK_SILICON','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'P_STACK_SILICON','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'P_STACK_SILICON','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'P_STACK_SILICON','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core Qty'
UNION SELECT 'P_STACK_SILICON','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'P_STACK_SILICON','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'P_STACK_SILICON','PHYS_GFX_EXECUTION_UNIT_QTY','PHYS_GFX_EXECUTION_UNIT_QTY','Physical GFX Execution Unit Qty'
UNION SELECT 'P_STACK_SILICON','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_STACK_SILICON','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_STACK_SILICON','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'P_STACK_SILICON','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_TEST','MANUFACTURING_DEVICE_NAME','MANUFACTURING_DEVICE_NAME','Manufacturing Device Name'
UNION SELECT 'P_TEST','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_TEST','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'P_TEST','INTERNAL_REVISION','INTERNAL_REVISION','Internal Revision'
UNION SELECT 'P_TEST','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'P_TEST','SUB_CODE_NAME','SUB_CODE_NAME','Sub Code Name'
UNION SELECT 'P_TEST','SPECIAL_FLOW_TYPE','SPECIAL_FLOW_TYPE','Special Flow Type'
UNION SELECT 'P_TEST','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'P_TEST','DLCP_PROCESS_CODE','DLCP_PROCESS_CODE','Die Level Cherry Pick Code'
UNION SELECT 'P_TEST','MFG_PKG_TECHNOLOGY','MFG_PKG_TECHNOLOGY','MFG Package Technology'
UNION SELECT 'P_TEST','MFG_PKG_CODE','MFG_PKG_CODE','Manufacturing Package Code'
UNION SELECT 'P_TEST','PINCOUNT','PINCOUNT','Pincount'
UNION SELECT 'P_TEST','SPECIAL_PRODUCT_CONFIG_CODE','SPECIAL_PRODUCT_CONFIG_CODE','Special Product Config Code'
UNION SELECT 'P_TEST','TOTAL_FUNCTIONAL_CORE_COUNT','TOTAL_FUNCTIONAL_CORE_COUNT','Total Functional Core Count'
UNION SELECT 'P_TEST','PHYSICAL_DIE_PER_PKG_QTY','PHYSICAL_DIE_PER_PKG_QTY','Physical Die Per Pkg'
UNION SELECT 'P_TEST','FUNCTIONAL_DIE_PER_PACKAGE','FUNCTIONAL_DIE_PER_PACKAGE','Functional Die Per Package'
UNION SELECT 'P_TEST','TOTAL_PHYSICAL_CORE_COUNT','TOTAL_PHYSICAL_CORE_COUNT','Physical Core Qty'
UNION SELECT 'P_TEST','MEMORY_CAPACITY','MEMORY_CAPACITY','Memory Capacity'
UNION SELECT 'P_TEST','MEMORY_CAPACITY_UOM','MEMORY_CAPACITY_UOM','Memory Capacity UOM'
UNION SELECT 'P_TEST','PRODUCTION_ENGINEERING_CODE','PRODUCTION_ENGINEERING_CODE','Production Engineering Code'
UNION SELECT 'P_TEST','STRATEGIC_ROADMAP_SEGMENT_CODE','STRATEGIC_ROADMAP_SEGMENT_CODE','Strategic Roadmap Segment Code'
UNION SELECT 'P_TEST','INTEGRATED_GRAPHICS_PHYS_CORES','INTEGRATED_GRAPHICS_PHYS_CORES','Integrated Graphics Phys Cores'
UNION SELECT 'P_TEST','INTEGRATED_GRAPHICS_FUNC_CORES','INTEGRATED_GRAPHICS_FUNC_CORES','Integrated Graphics Func Cores'
UNION SELECT 'P_TEST','LRP_EST_FUNCTIONAL_CORE_QTY','LRP_EST_FUNCTIONAL_CORE_QTY','LRP Est Functional Core Qty'
UNION SELECT 'P_TEST','LRP_EST_FUNC_GRAPHICS_CORE_QTY','LRP_EST_FUNC_GRAPHICS_CORE_QTY','LRP Est Func Graphics Core Qty'
UNION SELECT 'P_TEST','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'P_TEST','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'P_TEST','PREVIOUS_REFERENCE_ID','PREVIOUS_REFERENCE_ID','Previous Reference ID'
UNION SELECT 'P_TEST','MFG_RESTRICTION_CD','MFG_RESTRICTION_CD','MFG Restriction Code'
UNION SELECT 'P_TEST','MAX_FPO_MARK_LOT_NBRS_ALLOWED','MAX_FPO_MARK_LOT_NBRS_ALLOWED','Max FPO Mark Lot Nbrs Allowed'
UNION SELECT 'P_TEST','MAX_NUMBER_OF_LOT_SEAL_DATES','MAX_NUMBER_OF_LOT_SEAL_DATES','Max Number of Lot Seal Dates'
UNION SELECT 'P_TEST','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'P_TEST','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'P_TEST','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'P_TEST','MEMORY1_CAPACITY_UOM','MEMORY1_CAPACITY_UOM','Memory  1 Capacity Uom'
UNION SELECT 'P_TEST','MEMORY1_CAPACITY','MEMORY1_CAPACITY','Memory1  Capacity'
UNION SELECT 'P_TEST','INDIVIDUAL_MEMORY_CAPACITY','INDIVIDUAL_MEMORY_CAPACITY','Individual Memory Capacity'
UNION SELECT 'P_TEST','PHYSICAL_LP_ECORE_PROCESSOR_QTY','PHYSICAL_LP_ECORE_PROCESSOR_QTY','Physical LP Ecore Prcsr Qty'
UNION SELECT 'P_TEST','FUNCTIONAL_LP_ECORE_PRCSR_QTY','FUNCTIONAL_LP_ECORE_PRCSR_QTY','Functional LP Ecore Prcsr Qty'
UNION SELECT 'P_TEST','PHYSICAL_ECORE_PROCESSOR_QTY','PHYSICAL_ECORE_PROCESSOR_QTY','Physical Ecore Processor Qty'
UNION SELECT 'P_TEST','PHYSICAL_P_CORE_PROCESSOR_QTY','PHYSICAL_P_CORE_PROCESSOR_QTY','Physical P Core Processor Qty'
UNION SELECT 'P_TEST','PHYSICAL_S_ECORE_PROCESSOR_QTY','PHYSICAL_S_ECORE_PROCESSOR_QTY','Physical S ECore Processor Qty'
UNION SELECT 'P_TEST','FUNCTIONAL_P_CORE_PRCSR_QTY','FUNCTIONAL_P_CORE_PRCSR_QTY','Functional P Core Prcsr Qty'
UNION SELECT 'P_TEST','FUNCTIONAL_ECORE_PROCESSOR_QTY','FUNCTIONAL_ECORE_PROCESSOR_QTY','Functional Ecore Processor Qty'
UNION SELECT 'P_TEST','FUNCTIONAL_S_ECORE_PRCSR_QTY','FUNCTIONAL_S_ECORE_PRCSR_QTY','Functional S ECore Prcsr Qty'
UNION SELECT 'SY','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'SY','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'WAFER','TRANSISTOR_FAB_PROCESS_TECH','TRANSISTOR_FAB_PROCESS_TECH','Transistor Fab Process Tech'
UNION SELECT 'WAFER','BRANDED_INDICATOR','BRANDED_INDICATOR','Branded Indicator'
UNION SELECT 'WAFER','MARKETING_PACKAGE_DESIGNATOR','MARKETING_PACKAGE_DESIGNATOR','Marketing Package Designator'
UNION SELECT 'WAFER','TRADEMARK_NAME','TRADEMARK_NAME','Trademark Name'
UNION SELECT 'WAFER','PACKAGE_SHORT_TEXT','PACKAGE_SHORT_TEXT','Package Short Text'
UNION SELECT 'WAFER','CUSTOMER-CODE','CUSTOMER-CODE','Customer-code'
UNION SELECT 'WAFER','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'WAFER','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'WAFER','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'WAFER','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'WAFER','FAB_PROCESS_TECHNOLOGY','FAB_PROCESS_TECHNOLOGY','Fab Process Technology'
UNION SELECT 'WAFER','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'WAFER','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'WAFER','EXTERNAL_STEPPING','EXTERNAL_STEPPING','External Stepping'
UNION SELECT 'WAFER','FINISHED_GOOD_TYPE','FINISHED_GOOD_TYPE','Finished Good Type'
UNION SELECT 'WAFER','ULT_SCAN_FOR_DC_OPEN_BOX','ULT_SCAN_FOR_DC_OPEN_BOX','ULT Scan for DC Open Box'
UNION SELECT 'WAFER','DESIGNED_FUNCTION_CODE','DESIGNED_FUNCTION_CODE','Designed Function Code'
UNION SELECT 'WAFER','FUNCTIONAL_DESIGN_NAME','FUNCTIONAL_DESIGN_NAME','Functional Design Name'
UNION SELECT 'WAFER','FORM_FACTOR_CODE','FORM_FACTOR_CODE','Form Factor Code'
UNION SELECT 'WAFER','FORM_FACTOR_DIMENSION','FORM_FACTOR_DIMENSION','Form Factor Dimension'
UNION SELECT 'WAFER','FINSHED_GOOD_CATEGORY_TYPE','FINSHED_GOOD_CATEGORY_TYPE','Finished Good Category Type'
UNION SELECT 'WAFER','PRIMARY_SILICON_CODE_NAME','PRIMARY_SILICON_CODE_NAME','Primary Silicon Code Name'
UNION SELECT 'WAFER','MULTIPLE_MARK_NAME','MULTIPLE_MARK_NAME','Multiple Mark Name'


    -- Step 1: Populate actual attribute data from uda_definition table
    UPDATE tgt
    SET tgt.att_idn = src.att_idn,      -- Get attribute ID
        tgt.att_nme = src.att_nme,      -- Get actual attribute name
        tgt.att_dsc = src.att_dsc       -- Get actual attribute description
    FROM #Updated tgt
    LEFT JOIN dbo.uda_definition src 
    ON src.att_nme = tgt.expected_att_nme;

    -- Step 2: Get item type code from uda_item_type table
    UPDATE tgt
    SET tgt.item_typ_cde = ui.item_typ_cde
    FROM #Updated tgt
    LEFT JOIN uda_item_type ui 
    ON ui.att_idn = tgt.att_idn;

    -- Step 3: Get actual item class description from item_type table
    UPDATE tgt
    SET tgt.itm_class = ui.item_typ_dsc
    FROM #Updated tgt
    LEFT JOIN item_type ui 
    ON ui.item_typ_cde = tgt.item_typ_cde;

    -- Step 4: Mark records as PASS when attribute exists and matches expected name
    UPDATE tgt
    SET tgt.assert = 'PASS',
        tgt.result = 'Match Found'
    FROM #Updated tgt
    JOIN dbo.uda_definition src 
    ON src.att_nme = tgt.expected_att_nme
    AND src.att_idn = tgt.att_idn;

    -- Step 5: Mark records as FAIL when attribute doesn't match or doesn't exist
    UPDATE tgt
    SET tgt.assert = 'FAIL',
        tgt.result = 'Match not Found'
    FROM #Updated tgt
    JOIN dbo.uda_definition src 
    ON src.att_nme <> tgt.expected_att_nme
    AND tgt.att_idn IS NULL;

    -- =====================================================================================
    -- TEST 2: ATTRIBUTE-TO-ITEM-TYPE ASSOCIATION VALIDATION
    -- Purpose: Validates that specific attributes are properly associated with item types
    -- Focus: Diverse item classes and their required attributes
    -- =====================================================================================
    

    -- Insert test data: Item class and attribute name combinations to validate
    INSERT INTO #Inserted (itm_class, att_nme,expected_att_nme,expected_att_dsc)
       SELECT 'ASIC_FG','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'ASIC_FG','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'ASIC_FG','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'ASIC_FG','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'ASIC_FG','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'ASIC_FG','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'ASIC_FG','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'ASIC_FG','MARKETING_PERFORMANCE_CODE','MARKETING_PERFORMANCE_CODE','Marketing Performance Code'
UNION SELECT 'ASIC_FG','MARKET_SEGMENT_CODE','MARKET_SEGMENT_CODE','Market Segment Code'
UNION SELECT 'ASIC_FG','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'ASIC_FG','PHYSICAL_PERFORMANCE_PROFILE','PHYSICAL_PERFORMANCE_PROFILE','Physical Performance Profile'
UNION SELECT 'ASIC_FG','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'ASIC_FG','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'ASIC_FG','PRODUCT_MODEL_CODE','PRODUCT_MODEL_CODE','Product Model Code'
UNION SELECT 'ASIC_FG','SILICON_DIE_COUNT','SILICON_DIE_COUNT','Silicon Die Count'
UNION SELECT 'BD','BOX_LABEL','BOX_LABEL','Box Label'
UNION SELECT 'BD','BRAND_LEVEL','BRAND_LEVEL','Brand Level'
UNION SELECT 'BD','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'BD','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'BD','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'BD','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'BD','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'BD','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'BD','MARKETING_GENERATION','MARKETING_GENERATION','Marketing Generation'
UNION SELECT 'BD','MARKETING_PERFORMANCE_CODE','MARKETING_PERFORMANCE_CODE','Marketing Performance Code'
UNION SELECT 'BD','MARKET_SEGMENT_CODE','MARKET_SEGMENT_CODE','Market Segment Code'
UNION SELECT 'BD','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'BD','PHYSICAL_PERFORMANCE_PROFILE','PHYSICAL_PERFORMANCE_PROFILE','Physical Performance Profile'
UNION SELECT 'BD','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'BD','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'BD','PRODUCT_MODEL_CODE','PRODUCT_MODEL_CODE','Product Model Code'
UNION SELECT 'CHIPSETS_IC','BRAND_LEVEL','BRAND_LEVEL','Brand Level'
UNION SELECT 'CHIPSETS_IC','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'CHIPSETS_IC','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'CHIPSETS_IC','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'CHIPSETS_IC','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'CHIPSETS_IC','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'CHIPSETS_IC','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'CHIPSETS_IC','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'CHIPSETS_IC','MARKETING_GENERATION','MARKETING_GENERATION','Marketing Generation'
UNION SELECT 'CHIPSETS_IC','MARKETING_PERFORMANCE_CODE','MARKETING_PERFORMANCE_CODE','Marketing Performance Code'
UNION SELECT 'CHIPSETS_IC','MARKET_SEGMENT_CODE','MARKET_SEGMENT_CODE','Market Segment Code'
UNION SELECT 'CHIPSETS_IC','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'CHIPSETS_IC','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'CHIPSETS_IC','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'CHIPSETS_IC','PRODUCT_MODEL_CODE','PRODUCT_MODEL_CODE','Product Model Code'
UNION SELECT 'CHIPSETS_IC','SILICON_DIE_COUNT','SILICON_DIE_COUNT','Silicon Die Count'
UNION SELECT 'CONNECTIVITY','BRAND_LEVEL','BRAND_LEVEL','Brand Level'
UNION SELECT 'CONNECTIVITY','CONNECTIVITY_FUNCTION','CONNECTIVITY_FUNCTION','Connectivity Function'
UNION SELECT 'CONNECTIVITY','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'CONNECTIVITY','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'CONNECTIVITY','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'CONNECTIVITY','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'CONNECTIVITY','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'CONNECTIVITY','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'CONNECTIVITY','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'CONNECTIVITY','MARKET_SEGMENT_CODE','MARKET_SEGMENT_CODE','Market Segment Code'
UNION SELECT 'CONNECTIVITY','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'CONNECTIVITY','PHYSICAL_PERFORMANCE_PROFILE','PHYSICAL_PERFORMANCE_PROFILE','Physical Performance Profile'
UNION SELECT 'CONNECTIVITY','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'CONNECTIVITY','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'CONNECTIVITY','PRODUCT_MODEL_CODE','PRODUCT_MODEL_CODE','Product Model Code'
UNION SELECT 'CONNECTIVITY','SILICON_DIE_COUNT','SILICON_DIE_COUNT','Silicon Die Count'
UNION SELECT 'CONNECTIVITY','VPRO_ELIGIBILITY','VPRO_ELIGIBILITY','vPro Eligibility'
UNION SELECT 'CPU','BOX_LABEL','BOX_LABEL','Box Label'
UNION SELECT 'CPU','BRAND_LEVEL','BRAND_LEVEL','Brand Level'
UNION SELECT 'CPU','COMPUTE_CORE_TYPE','COMPUTE_CORE_TYPE','Compute Core Type'
UNION SELECT 'CPU','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'CPU','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'CPU','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'CPU','FALL_OUT_INDICATOR','FALL_OUT_INDICATOR','Fall Out Indicator'
UNION SELECT 'CPU','IMAGE_PROCESSING_UNIT_INDICATR','IMAGE_PROCESSING_UNIT_INDICATR','Image Processing Unit Indicator'
UNION SELECT 'CPU','INTEGRATED_GRAPHICS_CORES_UOM','INTEGRATED_GRAPHICS_CORES_UOM','Integrated Graphics Cores UOM'
UNION SELECT 'CPU','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'CPU','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'CPU','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'CPU','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'CPU','LOW_POWER_DDR5_FREQ_RATE_UOM','LOW_POWER_DDR5_FREQ_RATE_UOM','Low Power DDR5 Freq Rate UOM'
UNION SELECT 'CPU','MARKETING_GENERATION','MARKETING_GENERATION','Marketing Generation'
UNION SELECT 'CPU','MARKETING_PERFORMANCE_CODE','MARKETING_PERFORMANCE_CODE','Marketing Performance Code'
UNION SELECT 'CPU','MARKET_SEGMENT_CODE','MARKET_SEGMENT_CODE','Market Segment Code'
UNION SELECT 'CPU','MEMORY_DATA_RATE','MEMORY_DATA_RATE','Memory Data Rate'
UNION SELECT 'CPU','MEMORY_DATA_RATE_UOM','MEMORY_DATA_RATE_UOM','Memory Data Rate UOM'
UNION SELECT 'CPU','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'CPU','PHYSICAL_PERFORMANCE_PROFILE','PHYSICAL_PERFORMANCE_PROFILE','Physical Performance Profile'
UNION SELECT 'CPU','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'CPU','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'CPU','PRODUCT_MODEL_CODE','PRODUCT_MODEL_CODE','Product Model Code'
UNION SELECT 'CPU','SILICON_DIE_COUNT','SILICON_DIE_COUNT','Silicon Die Count'
UNION SELECT 'CPU','VPRO_ELIGIBILITY','VPRO_ELIGIBILITY','vPro Eligibility'
UNION SELECT 'GPU','BRAND_LEVEL','BRAND_LEVEL','Brand Level'
UNION SELECT 'GPU','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'GPU','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'GPU','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'GPU','FALL_OUT_INDICATOR','FALL_OUT_INDICATOR','Fall Out Indicator'
UNION SELECT 'GPU','INTEGRATED_GRAPHICS_CORES_UOM','INTEGRATED_GRAPHICS_CORES_UOM','Integrated Graphics Cores UOM'
UNION SELECT 'GPU','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'GPU','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'GPU','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'GPU','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'GPU','MARKETING_GENERATION','MARKETING_GENERATION','Marketing Generation'
UNION SELECT 'GPU','MARKETING_PERFORMANCE_CODE','MARKETING_PERFORMANCE_CODE','Marketing Performance Code'
UNION SELECT 'GPU','MARKET_SEGMENT_CODE','MARKET_SEGMENT_CODE','Market Segment Code'
UNION SELECT 'GPU','MEMORY_DATA_RATE','MEMORY_DATA_RATE','Memory Data Rate'
UNION SELECT 'GPU','MEMORY_DATA_RATE_UOM','MEMORY_DATA_RATE_UOM','Memory Data Rate UOM'
UNION SELECT 'GPU','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'GPU','PHYSICAL_PERFORMANCE_PROFILE','PHYSICAL_PERFORMANCE_PROFILE','Physical Performance Profile'
UNION SELECT 'GPU','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'GPU','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'GPU','PRODUCT_MODEL_CODE','PRODUCT_MODEL_CODE','Product Model Code'
UNION SELECT 'GPU','SILICON_DIE_COUNT','SILICON_DIE_COUNT','Silicon Die Count'
UNION SELECT 'LITERATURE','LITERATURE_ARTWORK','LITERATURE_ARTWORK','Literature Artwork'
UNION SELECT 'LITERATURE','LITERATURE_FORMAT','LITERATURE_FORMAT','Literature Format'
UNION SELECT 'LITERATURE','LITERATURE_MATERIAL','LITERATURE_MATERIAL','Literature Material'
UNION SELECT 'LITERATURE','LITERATURE_TYPE','LITERATURE_TYPE','Literature Type'
UNION SELECT 'MAT','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'MAT','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'MAT','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'MAT','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'MAT','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'MAT','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'MEMORY_FG','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'MEMORY_FG','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'MEMORY_FG','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'MEMORY_FG','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'MEMORY_FG','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'MEMORY_FG','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'MEMORY_FG','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'MEMORY_FG','MEMORY_DATA_RATE','MEMORY_DATA_RATE','Memory Data Rate'
UNION SELECT 'MEMORY_FG','MEMORY_DATA_RATE_UOM','MEMORY_DATA_RATE_UOM','Memory Data Rate UOM'
UNION SELECT 'MEMORY_FG','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'MEMORY_FG','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'MEMORY_FG','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'MEMORY_FG','PRODUCT_MODEL_CODE','PRODUCT_MODEL_CODE','Product Model Code'
UNION SELECT 'MEMORY_FG','SILICON_DIE_COUNT','SILICON_DIE_COUNT','Silicon Die Count'
UNION SELECT 'P_ASSEMBLY','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'P_ASSEMBLY','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'P_ASSEMBLY','INDIVIDUAL_MEMORY_CAPACITY_UOM','INDIVIDUAL_MEMORY_CAPACITY_UOM','Individual Memory Capacity UOM'
UNION SELECT 'P_ASSEMBLY','INTEGRATED_GRAPHICS_CORES_UOM','INTEGRATED_GRAPHICS_CORES_UOM','Integrated Graphics Cores UOM'
UNION SELECT 'P_ASSEMBLY','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'P_ASSEMBLY','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'P_ASSEMBLY','LEGACY_DESCRIPTION','LEGACY_DESCRIPTION','Legacy Description'
UNION SELECT 'P_ASSEMBLY','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'P_ASSEMBLY','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'P_ASSEMBLY','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'P_ASSEMBLY','PHYSICAL_PERFORMANCE_PROFILE','PHYSICAL_PERFORMANCE_PROFILE','Physical Performance Profile'
UNION SELECT 'P_ASSEMBLY','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'P_ASSEMBLY','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'P_ASSEMBLY','SILICON_DIE_COUNT','SILICON_DIE_COUNT','Silicon Die Count'
UNION SELECT 'P_BUMP','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'P_BUMP','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'P_BUMP','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'P_BUMP','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'P_BUMP','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'P_BUMP','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'P_BUMP','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'P_DIE_PREP','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'P_DIE_PREP','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'P_DIE_PREP','INTEGRATED_GRAPHICS_CORES_UOM','INTEGRATED_GRAPHICS_CORES_UOM','Integrated Graphics Cores UOM'
UNION SELECT 'P_DIE_PREP','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'P_DIE_PREP','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'P_DIE_PREP','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'P_DIE_PREP','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'P_DIE_PREP','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'P_FAB','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'P_FAB','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'P_FAB','INTEGRATED_GRAPHICS_CORES_UOM','INTEGRATED_GRAPHICS_CORES_UOM','Integrated Graphics Cores UOM'
UNION SELECT 'P_FAB','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'P_FAB','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'P_FAB','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'P_FAB','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'P_FAB','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'P_SORT','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'P_SORT','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'P_SORT','INTEGRATED_GRAPHICS_CORES_UOM','INTEGRATED_GRAPHICS_CORES_UOM','Integrated Graphics Cores UOM'
UNION SELECT 'P_SORT','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'P_SORT','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'P_SORT','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'P_SORT','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'P_SORT','MEMORY_VOLTAGE_QUANTITY_UOM','MEMORY_VOLTAGE_QUANTITY_UOM','Memory Voltage Quantity UOM'
UNION SELECT 'P_SORT','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'P_SORT','PRINTED_DIE_PER_WAFER','PRINTED_DIE_PER_WAFER','Printed Die Per Wafer'
UNION SELECT 'P_STACK_COMBO','ADVANCED_PKG_PROCESS_TECH_CODE','ADVANCED_PKG_PROCESS_TECH_CODE','Advance Pkg Process Tech Code'
UNION SELECT 'P_STACK_COMBO','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'P_STACK_COMBO','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'P_STACK_COMBO','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'P_STACK_COMBO','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'P_STACK_COMBO','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'P_STACK_COMBO','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'P_STACK_COMBO','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'P_STACK_COMBO','MOLD_GRIND_THICKNESS_TARGET_Um','MOLD_GRIND_THICKNESS_TARGET_Um','Mold Grind Target Um'
UNION SELECT 'P_STACK_COMBO','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'P_STACK_SILICON','DESIGNATOR_CODE','DESIGNATOR_CODE','Designator Code'
UNION SELECT 'P_STACK_SILICON','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'P_STACK_SILICON','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'P_STACK_SILICON','INTEGRATED_GRAPHICS_CORES_UOM','INTEGRATED_GRAPHICS_CORES_UOM','Integrated Graphics Cores UOM'
UNION SELECT 'P_STACK_SILICON','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'P_STACK_SILICON','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'P_STACK_SILICON','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'P_STACK_SILICON','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'P_STACK_SILICON','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'P_STACK_SILICON','PROC_STACK_SI_GROUPING','PROC_STACK_SI_GROUPING','PROC Stack Si Grouping'
UNION SELECT 'P_TEST','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'P_TEST','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'P_TEST','INDIVIDUAL_MEMORY_CAPACITY_UOM','INDIVIDUAL_MEMORY_CAPACITY_UOM','Individual Memory Capacity UOM'
UNION SELECT 'P_TEST','INTEGRATED_GRAPHICS_CORES_UOM','INTEGRATED_GRAPHICS_CORES_UOM','Integrated Graphics Cores UOM'
UNION SELECT 'P_TEST','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'P_TEST','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'P_TEST','LEGACY_DESCRIPTION','LEGACY_DESCRIPTION','Legacy Description'
UNION SELECT 'P_TEST','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'P_TEST','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'P_TEST','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'P_TEST','PHYSICAL_PERFORMANCE_PROFILE','PHYSICAL_PERFORMANCE_PROFILE','Physical Performance Profile'
UNION SELECT 'P_TEST','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'P_TEST','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'P_TEST','SILICON_DIE_COUNT','SILICON_DIE_COUNT','Silicon Die Count'
UNION SELECT 'SV','DEFERRED_REVENUE_REQ_IND','DEFERRED_REVENUE_REQ_IND','Deferred Revenue Req Indicator'
UNION SELECT 'SV','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'SV','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'SV','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'SV','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'SY','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'SY','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'SY','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'SY','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'SY','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'SY','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'SY','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'SY','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'SY','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'SY','PRODUCT_MODEL_CODE','PRODUCT_MODEL_CODE','Product Model Code'
UNION SELECT 'WAFER','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Name'
UNION SELECT 'WAFER','DESIGN_PRODUCT_TYPE','DESIGN_PRODUCT_TYPE','Design Product Type'
UNION SELECT 'WAFER','DESIGN_PROFIT_CENTER','DESIGN_PROFIT_CENTER','Design Profit Center'
UNION SELECT 'WAFER','ITEM_DIFFERENTIATOR','ITEM_DIFFERENTIATOR','Item Differentiator'
UNION SELECT 'WAFER','ITEM_ORDER_POINT','ITEM_ORDER_POINT','Item Order Point'
UNION SELECT 'WAFER','LEGAL_CODE_NAME','LEGAL_CODE_NAME','Legal Code Name'
UNION SELECT 'WAFER','LEGAL_CODE_NAME_ABBR','LEGAL_CODE_NAME_ABBR','Legal Code Name Abbrev'
UNION SELECT 'WAFER','PHYSICAL_DESIGN_CODE_NAME','PHYSICAL_DESIGN_CODE_NAME','Physical Design Code Name'
UNION SELECT 'WAFER','PRIMARY_DOT_PROCESS','PRIMARY_DOT_PROCESS','Primary Dot Process'
UNION SELECT 'WAFER','PRIMARY_TECHNOLOGY_NODE','PRIMARY_TECHNOLOGY_NODE','Primary Technology Node'
UNION SELECT 'WAFER','DIE_CODE_NAME','DIE_CODE_NAME','Die Code Name'
UNION SELECT 'WAFER','IC_CATEGORY_TYPE','IC_CATEGORY_TYPE','IC Category Type'
UNION SELECT 'WAFER','PRODUCT_GRADE','PRODUCT_GRADE','Product Grade'
UNION SELECT 'WAFER','PINCOUNT','PINCOUNT','Pincount'
UNION SELECT 'WAFER','CUSTOM_INDICATOR','CUSTOM_INDICATOR','Custom Indicator'
UNION SELECT 'WAFER','CUSTOMER_CUSTOM_PRODUCT','CUSTOMER_CUSTOM_PRODUCT','Customer Custom Product'
UNION SELECT 'WAFER','SHIPMENT_MEDIA','SHIPMENT_MEDIA','Shipment Media'
UNION SELECT 'WAFER','TRANSISTOR_FAB_PROCESS_TECH','TRANSISTOR_FAB_PROCESS_TECH','Transistor Fab Process Tech'
UNION SELECT 'WAFER','BRANDED_INDICATOR','BRANDED_INDICATOR','Branded Indicator'
UNION SELECT 'WAFER','ITEM_MARKET_NAME','ITEM_MARKET_NAME','Item Market Name'
UNION SELECT 'WAFER','ENCRYPTION','ENCRYPTION','Encryption'
UNION SELECT 'WAFER','ROYALTY_RECEIVABLE','ROYALTY_RECEIVABLE','Royalty Receivable'
UNION SELECT 'WAFER','ROYALTY_PAYABLE','ROYALTY_PAYABLE','Royalty Payable'
UNION SELECT 'WAFER','SPEC_CODE','SPEC_CODE','Spec Code'
UNION SELECT 'WAFER','SPEC_SEQUENTIAL_NUMBER','SPEC_SEQUENTIAL_NUMBER','Spec Sequential Number'
UNION SELECT 'WAFER','MARKETING_PACKAGE_DESIGNATOR','MARKETING_PACKAGE_DESIGNATOR','Marketing Package Designator'
UNION SELECT 'WAFER','INTEL_INSIDE_INDICATOR','INTEL_INSIDE_INDICATOR','Intel Inside Indicator'
UNION SELECT 'WAFER','TRADEMARK_NAME','TRADEMARK_NAME','Trademark Name'
UNION SELECT 'WAFER','PACKAGE_SHORT_TEXT','PACKAGE_SHORT_TEXT','Package Short Text'
UNION SELECT 'WAFER','ENCRYPTION_CODE_NAME','ENCRYPTION_CODE_NAME','Encryption Code Name'
UNION SELECT 'WAFER','PRODUCT_VISIBILITY_CODE','PRODUCT_VISIBILITY_CODE','Product Visibility Code'
UNION SELECT 'WAFER','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'WAFER','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'WAFER','MANUFACTURING_STAGE','MANUFACTURING_STAGE','Manufacturing Stage'
UNION SELECT 'WAFER','PACKAGE_TECHNOLOGY','PACKAGE_TECHNOLOGY','Package Technology'
UNION SELECT 'WAFER','FAB_PROCESS_TECHNOLOGY','FAB_PROCESS_TECHNOLOGY','Fab Process Technology'
UNION SELECT 'WAFER','INTERNAL_STEPPING','INTERNAL_STEPPING','Internal Stepping'
UNION SELECT 'WAFER','VERTICAL_SEGMENT','VERTICAL_SEGMENT','Vertical Segment'
UNION SELECT 'WAFER','LEAD_FREE_INDICATOR','LEAD_FREE_INDICATOR','Lead Free Indicator'
UNION SELECT 'WAFER','EXTERNAL_STEPPING','EXTERNAL_STEPPING','External Stepping'
UNION SELECT 'WAFER','INTEGRATED_HEAT_SPREADER_IND','INTEGRATED_HEAT_SPREADER_IND','Integrated Heat Spreader Ind'
UNION SELECT 'WAFER','FINSHED_GOOD_CATEGORY_TYPE','FINSHED_GOOD_CATEGORY_TYPE','Finished Good Category Type';

    -- Step 1: Get attribute ID for each attribute name
    UPDATE tgt
    SET tgt.att_idn = ud.att_idn,tgt.att_dsc = ud.att_dsc
    FROM #Inserted tgt
    LEFT JOIN dbo.uda_definition ud 
    ON ud.att_nme = tgt.att_nme;

    -- Step 2: Get item type code from item class description
    UPDATE tgt
    SET tgt.item_typ_cde = ui.item_typ_cde
    FROM #Inserted tgt
    LEFT JOIN item_type ui 
    ON ui.item_typ_dsc = tgt.itm_class;

    -- Step 3: Initialize all records as FAIL by default
    UPDATE #Inserted 
    SET assert = 'FAIL', 
        result = 'Match not Found';

    -- Step 4: Mark as PASS only when the attribute-item type combination exists
    UPDATE tgt
    SET tgt.assert = 'PASS', 
        tgt.result = 'Match Found'
    FROM #Inserted tgt
    INNER JOIN dbo.uda_item_type uit 
    ON uit.att_idn = tgt.att_idn 
       AND uit.item_typ_cde = tgt.item_typ_cde;

   
    -- =====================================================================================
    -- TEST 3: EXTENDED RIGID CONTAINER ATTRIBUTE VALIDATION
    -- Purpose: Validates extended attributes specifically for rigid containers
    -- Focus: Additional rigid container attributes including printing and art specifications
    -- =====================================================================================
    


    -- Insert test data: Extended rigid container attributes to validate
    INSERT INTO #Deleted (itm_class, att_nme, expected_att_nme,expected_att_dsc)
           SELECT 'BOX-PROCR-KIT-ASSY','BP-CACHE','BP-CACHE','Boxed Processor Cache'
UNION SELECT 'BOX-PROCR-KIT-ASSY','BP-FAN-HEATSINK-IND','BP-FAN-HEATSINK-IND','BP Fan Heatsink Indicator'
UNION SELECT 'BOX-PROCR-KIT-ASSY','BP-SPEED','BP-SPEED','Speed'
UNION SELECT 'BOX-PROCR-KIT-ASSY','ECC-IND','ECC-IND','ECC Indicator'
UNION SELECT 'BOX-PROCR-KIT-ASSY','GEOGRAPHY','GEOGRAPHY','Geography'
UNION SELECT 'BOX-PROCR-KIT-ASSY','DEVICE-SPEED-UOM','DEVICE-SPEED-UOM','Speed UOM'
UNION SELECT 'BOX-PROCR-KIT-ASSY','RAM_INDICATOR','RAM_INDICATOR','Ram Indicator'
UNION SELECT 'BOX-PROCR-KIT-ASSY','CACHE_VALUE_INDICATOR','CACHE_VALUE_INDICATOR','CACHE VALUE INDICATOR'
UNION SELECT 'BOX-PROCR-KIT-ASSY','RDRAM_QTY','RDRAM_QTY','RDRAM Oty'
UNION SELECT 'BOX-PROCR-KIT-ASSY','PRODUCT_TYPE_INDICATOR','PRODUCT_TYPE_INDICATOR','PRODUCT TYPE INDICATOR'
UNION SELECT 'CHIPSETS_IC','MM-SPEED-UOM','MM-SPEED-UOM','Speed Unit of Measure'
UNION SELECT 'CHIPSETS_IC','MM-SPEED-TYPE','MM-SPEED-TYPE','Speed Type'
UNION SELECT 'CHIPSETS_IC','MM-BRANDED','MM-BRANDED','Branded Product Indicator'
UNION SELECT 'CHIPSETS_IC','MM-SPEED','MM-SPEED','Speed'
UNION SELECT 'CHIPSETS_IC','MM-INTEL-INSIDE','MM-INTEL-INSIDE','Intel Inside Indicator'
UNION SELECT 'CHIPSETS_IC','MM-CACHE','MM-CACHE','Cache'
UNION SELECT 'CHIPSETS_IC','MM-CACHE-UOM','MM-CACHE-UOM','Cache UOM'
UNION SELECT 'CHIPSETS_IC','MM-GID-PROGRAM','MM-GID-PROGRAM','GID Program'
UNION SELECT 'CHIPSETS_IC','MM-GID-GROUPING','MM-GID-GROUPING','GID Grouping'
UNION SELECT 'CHIPSETS_IC','MM-ENCRY-KEY','MM-ENCRY-KEY','Encryption Key Length'
UNION SELECT 'CHIPSETS_IC','PS-PROCESS','PS-PROCESS','Fab Process'
UNION SELECT 'CHIPSETS_IC','PS_PLATFORM','PS_PLATFORM','Package Platform'
UNION SELECT 'CHIPSETS_IC','EPM_ID','EPM_ID','External Product ID'
UNION SELECT 'CHIPSETS_IC','PROCESSOR_NUMBER','PROCESSOR_NUMBER','Processor Number'
UNION SELECT 'CHIPSETS_IC','THERMAL_DESIGN_POWER','THERMAL_DESIGN_POWER','Thermal Design Power'
UNION SELECT 'CHIPSETS_IC','THERMAL_DESIGN_POWER_UOM','THERMAL_DESIGN_POWER_UOM','Thermal Design Power Unit of M'
UNION SELECT 'CHIPSETS_IC','SMLL_FORM_FCTR','SMLL_FORM_FCTR','Small Form Factor'
UNION SELECT 'CHIPSETS_IC','AES_INSTR_SET_IND','AES_INSTR_SET_IND','AES Instruction Set Indicator'
UNION SELECT 'CHIPSETS_IC','INTEL_TRST_EXEC_TECH_IND','INTEL_TRST_EXEC_TECH_IND','Intel Trusted Exec Tech Ind'
UNION SELECT 'CHIPSETS_IC','PCSR_BASE_CD','PCSR_BASE_CD','Processor Base Code'
UNION SELECT 'CHIPSETS_IC','PERFORMANCE_UPGRADE_INDICATOR','PERFORMANCE_UPGRADE_INDICATOR','PERFORMANCE UPGRADE INDICATOR'
UNION SELECT 'CHIPSETS_IC','PROTECT_AUDIO_VIDEO_PATH','PROTECT_AUDIO_VIDEO_PATH','PROTECT AUDIO VIDEO PATH'
UNION SELECT 'CHIPSETS_IC','HIGH_BNDWDT_DGTL_CONTENT_PRTCT','HIGH_BNDWDT_DGTL_CONTENT_PRTCT','HIGH BNDWDT DGTL CONTENT PRTCT'
UNION SELECT 'CHIPSETS_IC','SER_ADVNC_TECH_ATTCH_REV2_QTY','SER_ADVNC_TECH_ATTCH_REV2_QTY','SER ADVNC TECH ATTCH REV2 QTY'
UNION SELECT 'CHIPSETS_IC','SER_ADVNC_TECH_ATTCH_REV3_QTY','SER_ADVNC_TECH_ATTCH_REV3_QTY','SER ADVNC TECH ATTCH REV3 QTY'
UNION SELECT 'CHIPSETS_IC','UNIVERSAL_SERIAL_BUS2_QTY','UNIVERSAL_SERIAL_BUS2_QTY','UNIVERSAL SERIAL BUS2 QTY'
UNION SELECT 'CHIPSETS_IC','UNIVERSAL_SERIAL_BUS3_QTY','UNIVERSAL_SERIAL_BUS3_QTY','UNIVERSAL SERIAL BUS3 QTY'
UNION SELECT 'CHIPSETS_IC','UNIVERSAL_SERIAL_BUS3_IND','UNIVERSAL_SERIAL_BUS3_IND','UNIVERSAL SERIAL BUS3 IND'
UNION SELECT 'CHIPSETS_IC','SECURE_KEY_IND','SECURE_KEY_IND','SECURE KEY IND'
UNION SELECT 'CHIPSETS_IC','INTEL_SOFTWARE_GUARD_EXTN_IND','INTEL_SOFTWARE_GUARD_EXTN_IND','INTEL SOFTWARE GUARD EXTN IND'
UNION SELECT 'CHIPSETS_IC','PREV_REF_ID','PREV_REF_ID','PREVIOUS REFERENCE ID'
UNION SELECT 'CPU','MM-BRANDED','MM-BRANDED','Branded Product Indicator'
UNION SELECT 'CPU','MM-INTEL-INSIDE','MM-INTEL-INSIDE','Intel Inside Indicator'
UNION SELECT 'CPU','MM-GID-PROGRAM','MM-GID-PROGRAM','GID Program'
UNION SELECT 'CPU','MM-GID-GROUPING','MM-GID-GROUPING','GID Grouping'
UNION SELECT 'CPU','CUSTOMER-CODE','CUSTOMER-CODE','customer-code'
UNION SELECT 'CPU','MM-ENCRY-KEY','MM-ENCRY-KEY','Encryption Key Length'
UNION SELECT 'CPU','PS-PROCESS','PS-PROCESS','Fab Process'
UNION SELECT 'CPU','PS_PLATFORM','PS_PLATFORM','Package Platform'
UNION SELECT 'CPU','EPM_ID','EPM_ID','External Product ID'
UNION SELECT 'CPU','MARKETING_VOLT_NAME','MARKETING_VOLT_NAME','Marketing Voltage Name'
UNION SELECT 'CPU','SUB_VERTICAL_SEGMENT','SUB_VERTICAL_SEGMENT','Sub Vertical Segment'
UNION SELECT 'GPU','MM-BRANDED','MM-BRANDED','Branded Product Indicator'
UNION SELECT 'GPU','MM-INTEL-INSIDE','MM-INTEL-INSIDE','Intel Inside Indicator'
UNION SELECT 'GPU','MM-GID-PROGRAM','MM-GID-PROGRAM','GID Program'
UNION SELECT 'GPU','MM-GID-GROUPING','MM-GID-GROUPING','GID Grouping'
UNION SELECT 'GPU','CUSTOMER-CODE','CUSTOMER-CODE','customer-code'
UNION SELECT 'GPU','MM-ENCRY-KEY','MM-ENCRY-KEY','Encryption Key Length'
UNION SELECT 'GPU','PS-PROCESS','PS-PROCESS','Fab Process'
UNION SELECT 'GPU','PS_PLATFORM','PS_PLATFORM','Package Platform'
UNION SELECT 'GPU','EPM_ID','EPM_ID','External Product ID'
UNION SELECT 'GPU','MARKETING_VOLT_NAME','MARKETING_VOLT_NAME','Marketing Voltage Name'
UNION SELECT 'HEATSINK_ASSEMBLY','DEVICE-SPEED-UOM','DEVICE-SPEED-UOM','Speed UOM'
UNION SELECT 'HEATSINK_ASSEMBLY','DEVICE-SPEED','DEVICE-SPEED','Device Speed'
UNION SELECT 'NEW_BIZ_RDV','BUSINESS_UNIT','BUSINESS_UNIT','Business Unit'
UNION SELECT 'NEW_BIZ_RDV','BOM_TYPE','BOM_TYPE','BOM Type'
UNION SELECT 'SV','MM-ITEM-MARKET-NAME','MM-ITEM-MARKET-NAME','Item Market Name'
UNION SELECT 'SV','MM-ENCRYPT','MM-ENCRYPT','Encryption'
UNION SELECT 'SV','MM-FEATURE','MM-FEATURE','Feature'
UNION SELECT 'SV','MM-ENCRY-CODE','MM-ENCRY-CODE','Encryption Code Name'
UNION SELECT 'SV','MM-ENCRY-KEY','MM-ENCRY-KEY','Encryption Key Length'
UNION SELECT 'SV','PS-COMMENTS','PS-COMMENTS','Comments'
UNION SELECT 'SV','MM_PROD_CAT_SV_TYPE','MM_PROD_CAT_SV_TYPE','Category Service Group'
UNION SELECT 'SV','MM_PROD_CAT_SV','MM_PROD_CAT_SV','Service Category Type'
UNION SELECT 'SV','MM_SV_PROD_GROUP','MM_SV_PROD_GROUP','Service Product Group'
UNION SELECT 'SV','MM_SV_PROD_NAME','MM_SV_PROD_NAME','Product Name'
UNION SELECT 'SV','MM_SV_PROD_CMP','MM_SV_PROD_CMP','Product Component'
UNION SELECT 'SV','MM_LICENSE_SPEC','MM_LICENSE_SPEC','License Spec'
UNION SELECT 'SV','MM_SV_TYPE','MM_SV_TYPE','Service Type'
UNION SELECT 'SV','MM_SV_TYPE','MM_SV_TYPE','Service Type'
UNION SELECT 'SV','MM_DURATION','MM_DURATION','Duration'
UNION SELECT 'SV','MM_MEDIA_METHOD','MM_MEDIA_METHOD','Media Method'
UNION SELECT 'SV','MM_MEDIA_UPDATE_MTD','MM_MEDIA_UPDATE_MTD','Media Update Method'
UNION SELECT 'SV','MM_SERVICE_LOCATION','MM_SERVICE_LOCATION','Service Location'
UNION SELECT 'SV','MM_SERV_OPTIONS','MM_SERV_OPTIONS','Service Options'
UNION SELECT 'SV','EPM_ID','EPM_ID','External Product ID'
UNION SELECT 'SV','AES_INSTR_SET_IND','AES_INSTR_SET_IND','AES Instruction Set Indicator'
UNION SELECT 'SV','WARRANTY_ONSITE_SLA_CD','WARRANTY_ONSITE_SLA_CD','WARRANTY ONSITE SLA CD'
UNION SELECT 'SV','ADVANCED_WRNTY_REPLACEMENT_IND','ADVANCED_WRNTY_REPLACEMENT_IND','ADVANCED WRNTY REPLACEMENT IND'
UNION SELECT 'SV','WARRANTY_PARTS_SLA_CD','WARRANTY_PARTS_SLA_CD','WARRANTY PARTS SLA CD'
UNION SELECT 'SV','WARRANTY_MASTER_IND','WARRANTY_MASTER_IND','WARRANTY MASTER IND'
UNION SELECT 'SV','WARRANTY_RENEWABLE_IND','WARRANTY_RENEWABLE_IND','WARRANTY RENEWABLE IND'
UNION SELECT 'SV','SERIAL_NUMBER_REQUIRED_IND','SERIAL_NUMBER_REQUIRED_IND','SERIAL NUMBER REQUIRED IND'
UNION SELECT 'SV','FGR_GROUPING_CODE','FGR_GROUPING_CODE','FGR GROUPING CODE'
UNION SELECT 'SV','SUB_COMPONENT_CATEGORY_NAME','SUB_COMPONENT_CATEGORY_NAME','SUB COMPONENT CATEGORY NAME'
UNION SELECT 'SV','PREV_REF_ID','PREV_REF_ID','PREVIOUS REFERENCE ID'
UNION SELECT 'SV','SOLUTION_LEVEL_ENTITLEMENT','SOLUTION_LEVEL_ENTITLEMENT','SOLUTION LEVEL ENTITLEMENT'
UNION SELECT 'SV','SOFT_SKU_UPGRADE_IND','SOFT_SKU_UPGRADE_IND','SOFT SKU UPGRADE INDICATOR'
UNION SELECT 'WAFER','MM-REV','MM-REV','EXTERNAL REVISION'
UNION SELECT 'WAFER','MM-ENCRY-KEY','MM-ENCRY-KEY','Encryption Key Length'
UNION SELECT 'WAFER','EPM_ID','EPM_ID','External Product ID'
UNION SELECT 'WAFER','CUSTOMER_PART_NUM','CUSTOMER_PART_NUM','CUSTOMER PART NUMBER';


    -- Step 1: Get attribute ID for each attribute name
    UPDATE tgt
    SET tgt.att_idn = ud.att_idn
    FROM #Deleted tgt
    LEFT JOIN dbo.uda_definition ud 
    ON ud.att_nme = tgt.att_nme;

    -- Step 2: Get item type code from item class description
    UPDATE tgt
    SET tgt.item_typ_cde = ui.item_typ_cde
    FROM #Deleted tgt
    LEFT JOIN item_type ui 
    ON ui.item_typ_dsc = tgt.itm_class;

    -- Step 3: Initialize all records as FAIL by default
    UPDATE #Deleted 
    SET assert = 'FAIL', 
        result = 'Match not Found';

    -- Alternative error handling (commented out): Specific error messages for NULL cases
    -- Handle NULL cases with specific messages
    --UPDATE #Deleted 
    --SET result = 'Attribute not found in uda_definition'
    --WHERE att_idn IS NULL;

    --UPDATE #Deleted 
    --SET result = 'Item type not found'
    --WHERE item_typ_cde IS NULL AND att_idn IS NOT NULL;

    -- Step 4: Mark as PASS only when the attribute-item type combination exists
    UPDATE tgt
    SET tgt.assert = 'PASS', 
        tgt.result = 'Match Found'
    FROM #Deleted tgt
    INNER JOIN dbo.uda_item_type uit 
    ON uit.att_idn = tgt.att_idn 
       AND uit.item_typ_cde = tgt.item_typ_cde;

    -- =====================================================================================
    -- RESULTS: Display validation results for all three tests
    -- =====================================================================================
    
    -- Test 1 Results: Attribute name and description validation
    SELECT 
        att_idn,                -- Attribute ID
        item_typ_cde,          -- Item type code
        itm_class,             -- Item class name
        expected_att_nme,      -- Expected attribute name
        att_nme,               -- Actual attribute name
        expected_att_dsc,      -- Expected attribute description
        att_dsc,               -- Actual attribute description
        assert,                -- Test result (PASS/FAIL)
        result                 -- Result message
    FROM #Updated;

    -- Test 2 Results: Attribute-to-item-type association validation
    SELECT 
        att_idn,                -- Attribute ID
        item_typ_cde,          -- Item type code
        itm_class,             -- Item class name
        expected_att_nme,      -- Expected attribute name
        att_nme,               -- Actual attribute name
        expected_att_dsc,      -- Expected attribute description
        att_dsc,               -- Actual attribute description
        assert,                -- Test result (PASS/FAIL)
        result                 -- Result message
    FROM #Inserted;

    -- Test 3 Results: Extended rigid container attribute validation
    SELECT 
        att_idn,                -- Attribute ID
        item_typ_cde,          -- Item type code
        itm_class,             -- Item class name
        expected_att_nme,      -- Expected attribute name
        att_nme,               -- Actual attribute name
        expected_att_dsc,      -- Expected attribute description
        att_dsc,               -- Actual attribute description
        assert,                -- Test result (PASS/FAIL)
        result                 -- Result message
    FROM #Deleted;

END TRY
BEGIN CATCH
    -- =====================================================================================
    -- ERROR HANDLING: Display error information if any step fails
    -- =====================================================================================
    PRINT 'Error occurred during execution.';
    PRINT 'Message     : ' + ERROR_MESSAGE();
    PRINT 'Line        : ' + CAST(ERROR_LINE() AS VARCHAR);
        
END CATCH
END

